kubeflow/kfp-tekton

OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfp-tekton/1)
=> Adding Andrea as a reviewer

OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfp-tekton/2)
=> Adding more reviewers

README.md, samples/kfp-tekton/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfp-tekton/8)
=> Pointing to current samples

sdk/README.md, sdk/python/kfp/compiler/_k8s_helper.py, sdk/python/kfp/compiler/_op_to_template.py, sdk/python/kfp/compiler/compiler.py, sdk/samples/sequential/sequential.py
1. Add draft code for compiler
2. Add README.md
3. Add `sequential` sample for try
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfp-tekton/9)
=> Init commit for Compiler for tekton

sdk/python/kfp/compiler/_op_to_template.py
Fix: #11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfp-tekton/12)
=> Add "step.name" to the generated "task"

.gitignore, sdk/README.md, sdk/python/kfp/compiler/_k8s_helper.py, sdk/python/kfp/compiler/_op_to_template.py, sdk/python/kfp/compiler/compiler.py
Also adding more detailed setup instructions using a separate build directory for the KFP compiler files to not override the `$GOPATH/../kubeflow/pipelines/sdk`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfp-tekton/13)
=> Update to latest KFP SDK release (0.2.2)

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfp-tekton/14)
=> updating comparision link

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfp-tekton/15)
=> add the design doc

README.md
and concise
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfp-tekton/21)
=> make goal and deliverable more pointed

OWNERS
@animeshsingh -- please add me as a reviewer. Thank you.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfp-tekton/25)
=> Add ckadner as a reviewer

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfp-tekton/26)
=> Initial Travis CI for sdk unittest

OWNERS
I am very interesting with kfp-tekton, and I would like take high priority to contribute for it. Adding me as reviewer for more contributions. Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfp-tekton/31)
=> Add reviewer from IBM China

README.md, sdk/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfp-tekton/36)
=> streamline and add to instructions

sdk/README.md, sdk/python/tests/README.md
=> instructions to run tests 

sdk/python/tests/compiler/testdata/init_container.py, sdk/python/tests/compiler/testdata/pipelineparams.py, sdk/python/tests/compiler/testdata/retry.py, sdk/python/tests/compiler/testdata/sidecar.py, sdk/python/tests/compiler/testdata/volume.py
Just to enhance deliveried testdata scripts
=> enhance testdata scripts

README.md, sdk/README.md, sdk/python/tests/README.md
- Tekton version should be 0.11
- Update report cards.
=> Update report card and fix typos

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/questions.md, .github/PULL_REQUEST_TEMPLATE.md, .github/issue_label_bot.yaml
Github Template for Issue, Pull Request, and issue label bot.
=> Add initial github template

OWNERS
Both Christian and Tommy have done an excellent job in leading the KFP Tekton project, with design, code contributions and reviews
Currently we are hitting 70% mark in terms of getting closer to getting the first phase of compiler implemented, and their leadership is instrumental in getting this done
=> Promoting Christian and Tommy to be the approvers

Makefile
Resolves #97 
create makefile for testing.
Python 3.7.4
Client version: 0.8.0
Pipeline version: v0.11.0-rc2
openshift 4.3.1
OS (e.g. from /etc/os-release):
macOS Mojave 10.14.6
=> create sdk/python makefile

sdk/README.md, sdk/kfp-tekton-limitation.md
Resolves #44 
List the current limitation in the kfp-tekton
this is a doc change
=> Add limitation doc 

samples/katib/README.md, samples/katib/katib.py
Resolves #
Add simple katib example for doing HPO.
=> Add Simple Katib example

.travis.yml, sdk/README.md, sdk/python/tests/README.md
Since @kevinyu98 added a neat new `Makefile` we should _make_ use it in our docs and for CI/CD with Travis 😄
=> Use make commands for tests and report

sdk/FEATURES.md
Resolves #
- Fix broken links
- Rearrange and hyperlink issues
=> Feature doc patch

samples/watson-train-serve/README.md, samples/watson-train-serve/watson_train_serve_pipeline.py
Resolves #
- Add wml train and serve example
- Update the default tensorflow version to 1.15. WML V4 api is no longer supporting 1.14
* Tekton Version (use `tkn version`): 0.11.3
=> Add wml sample

README.md, samples/README.md, samples/e2e-mnist/README.md, samples/trusted-ai/README.md
add the list of currently tested pipelines, and reorient the main readme pointing to implementation details and test results, both compilation tests and execution tests
=> tested pipeline samples

README.md
and point to the backend repository
=> Make the intent of the repository clear

tekton-catalog/kubectl-wrapper/deploy/taskrun.yaml
Will cause exception when applied.
Resolves #
=> Fix tiny issue for kubectl-wrapper

sdk/FEATURES.md, sdk/README.md
Resolves #
Update feature doc for:
- Affinity, Node Selector, and Tolerations implementation
- Official KFP removal for ArtifactLocation and explicit output artifact features.
- Add notes for API version on conditions
=> Update feature doc related to the recently changes

sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/testdata/condition.yaml, tekton-catalog/condition/README.md, tekton-catalog/condition/condition.yaml
Addresses task 1 of #165: Generalize the current condition into a more catalog task design.
Creates a "super-condition" which all other condition extend by passing in the parameters necessary for individual conditions
=> Update conditional feature with the catalog condition approach

OWNERS
I would like to apply to be an approver in kfp-tekton, I committed serveral PRs, also some of them are key projects. I want to keep moving and contribute more for kubeflow community, make tekton could be used in kfp stable and popular, wish you could approve. Big Thanks!
=> Apply to be kfp-tekton approver

sdk/python/kfp_tekton/__init__.py, sdk/python/setup.py
**Changes:**
- updated the version from `0.0.1` to `0.1.0`
- updated `description` and `long_description`
---
**Possible things to improve **_before_** we push to PyPi:**
Generate the `long_description` from the `sdk/README.md`. I will give that a try:
```Python
import setuptools
with open("sdk/README.md", "r") as f:
long_description = f.read()
setuptools.setup(
name="...",
description="...",
long_description=long_description,
long_description_content_type="text/markdown",
)
```
=> Prepare release 0.1.0

sdk/README.md, sdk/python/kfp_tekton/compiler/main.py
Resolves #183 
Update artifact docs to use the new example. Also fix a small bug on the pyfile function.
* Tekton Version (use `tkn version`): 0.13
=> Update artifact docs and fix minor bug

sdk/README.md, sdk/python/README.md, sdk/python/kfp_tekton/__init__.py, sdk/python/setup.py
**Description of Changes:**
* Update version from 0.1.0 to 0.2.0
* Upload SDK to Test-PyPi (upload to real PyPi index once release is signed off)
**Additional Information:**
* `kfp-tekton` package on Test-PyPi:
https://test.pypi.org/project/kfp-tekton/0.2.0rc2/
=> Prepare release 0.2.0

samples/big_data_passing/big_data_passing_description.ipynb, samples/big_data_passing/constant_to_consumer_pipeline.yaml, samples/big_data_passing/pipeline_parameter_to_consumer_pipeline.yaml, samples/big_data_passing/print_repeating_lines_pipeline.yaml, samples/big_data_passing/processing_pipeline.yaml, samples/big_data_passing/producers_to_consumers_pipeline.yaml, samples/big_data_passing/sum_pipeline.yaml, samples/big_data_passing/task_output_to_consumer_pipeline.yaml, samples/big_data_passing/text_splitting_pipeline.yaml, samples/big_data_passing/text_splitting_pipeline2.yaml
Resolves #193 
Update the samples of big data since the design changed #166 and #194
=> Update the samples of big data since the design changed

Makefile, sdk/FEATURES.md, tools/mdtoc.sh
* Add TOC marker to `sdk/FEATURES.md`
* Update `tools/mdtoc.sh`:
* Include 1st level headings
* Exclude triple-tick code blocks when looking for headings (`# ...`)
* Update `make check_mdtoc`:
* Tolerate `+` and `*` as TOC bullet points
* Tolerate additional links appended to TOC entries,
i.e. "` - [Text](#anchor-link) [Tracking issue][...]`"
**Markdown files included in `make check_mdtoc` after this PR:**
* Python Version: `3.7.5`
* Tekton Version: `0.14.0`
* Kubernetes Version: `0.16.0`
* OS: `MacOS 10.15.5`
---
/cc @Tomcli
=> Include sdk/FEATURES.md in Table-of-Contents check

README.md, tekton_kfp_guide.md
first in the series of simplifying deployment and usage instructions
=> Simplify deployment and usage instructions

backend/Dockerfile, backend/metadata_writer/src/metadata_writer.py, backend/src/common/util/workflow.go, go.sum, manifests/kustomize/base/kustomization.yaml, manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
Related #224 
Api and manifest rebase patch. Multi-user support will come in a different PR since it needs a new design change.
=> Api and manifest rebase patch

sdk/python/kfp_tekton/compiler/_op_to_template.py
Resolves #256
Changed the TODO comment to point to where the tekton image is maintained. 
* Tekton Version (use `tkn version`): 1.15
**Checklist:**
* `test: fix CI failure. Part …
=> Update comment for kfp-tekton image 

Makefile, README.md, sdk/README.md, sdk/python/README.md, sdk/python/tests/compiler/compiler_tests_e2e.py
* Update SDK, `README`s, `Makefile`, and E2E tests for [Tekton Pipelines v0.15.0](https://github.com/tektoncd/pipeline/releases/tag/v0.15.0)
* Tekton Version (use `tkn version`): `v0.15.0`
* Kubernetes Version (use `kubectl version`): `v1.16.13+IKS`
* OS (e.g. from `/etc/os-release`): Mac OS Catalina
/cc @Tomcli
=> Upgrade SDK to Tekton Pipelines v0.15.0

samples/e2e-mnist/README.md, samples/e2e-mnist/mnist.ipynb
Resolves #270 
Add storageclass as one of the configurable parameter for e2e-mnist example. This way is more flexible to change storageclass on a per pipeline basis.
* Tekton Version (use `tkn version`): 1.15
**Checklist:**
Use `chore` to indicate that this PR …
=> feat(samples): parameterize storageclass for the e2e-mnist example

.travis.yml, sdk/README.md, sdk/python/kfp_tekton/compiler/_op_to_template.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/old_kfp_volume.py
Resolves #280 
Throw errors on deprecated volume definitions. Add test case to check this deprecation error.
Also update Travis to install pytest to test failure cases.
**Checklist:**
Use `chore` to indicate that this PR makes some …
=> fix(sdk): throw errors on deprecated volume definition

tekton_kfp_guide.md
update installation instructions to point to openshift and simplify installation flow
=> update kfp tekton install steps

sdk/python/kfp_tekton/compiler/_op_to_template.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/hidden_output_file.log, sdk/python/tests/compiler/testdata/hidden_output_file.py, sdk/python/tests/compiler/testdata/hidden_output_file.yaml
related #274
Fix a formatting bug with showing the bad output-file underscore format. Possibly related to #274.
**Checklist:**
* `test: fix CI …
=> fix(sdk): fixes outputfile key formatting

sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/condition_error.py
Related #310 
Check whether the dependent component is a tekton task. If not, prompt an error to suggest user to run after a Tekton task(ContainerOp).
In Argo, tasks and conditions are both treated as Argo template (equivalent of Tekton Task) where both can be treated as parent tasks. However, Tekton "runAfter" only allowed to run after a Tekton Task. (Not Tekton condition or pipelineResource)
https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#using-the-runafter-parameter 
**Checklist:** …
=> fix(sdk): Check whether the dependent component is a tekton task

README.md, developer_guide.md, manifests/kustomize/base/application/kustomization.yaml, manifests/kustomize/base/cache-deployer/kustomization.yaml, manifests/kustomize/base/kustomization.yaml, manifests/kustomize/base/pipeline/kustomization.yaml, manifests/kustomize/env/platform-agnostic/metadata-writer-deployment.yaml
Resolves #
Since the original KFP dev manifests and docs are not very friendly for new comers, I did some improvement based on my experience and convert it in a way that can be installed with `kubectl -k` alone. 
Also, I changed few minor things in the dev manifests:
- removed Argo since we don't need it until the main KFP repo can upgrade their Argo version.
- The dev images are pointing to latest which is built on the latest commit.
* Tekton Version (use `tkn version`): 0.15
**Checklist:**
* `fix(frontend): fixes empty page. …
=> Improve development manfests and docs

README.md
The acronym CRD is used in markdown documents throughout the repo, but 
should be expanded and linked at least once at the top level to add 
clarity. A standard writing practice for documentation
Resolves #
**Checklist:**
Use `chore` …
=> chore: Update the README to expand and link to CRDs

samples/big_data_passing/big_data_passing_description.ipynb, samples/big_data_passing/constant_to_consumer_pipeline.yaml, samples/big_data_passing/pipeline_parameter_to_consumer_pipeline.yaml, samples/big_data_passing/print_repeating_lines_pipeline.yaml, samples/big_data_passing/processing_pipeline.yaml, samples/big_data_passing/producers_to_consumers_pipeline.yaml, samples/big_data_passing/sum_pipeline.yaml, samples/big_data_passing/task_output_to_consumer_pipeline.yaml, samples/big_data_passing/text_splitting_pipeline.yaml, samples/big_data_passing/text_splitting_pipeline2.yaml, sdk/README.md, sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py, sdk/python/tests/compiler/testdata/big_data_passing.yaml
Resolves #312 
- Update big data passing to also update the workspace path in annotations
- Add docs on how to configure workspace pvc settings
- Update big data passing samples
* Tekton Version (use `tkn version`): 0.14
**Checklist:**
Use `chore` to indicate that …
=> Fix big data annotations and update docs/samples

backend/src/common/util/workflow.go
Resolves #
Update the list of Tekton Final state to indicate what pipelines need to be periodically push to MySQL and clean up.
List of Tekton execution status:
https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#monitoring-execution-status
**Checklist:**
* …
=> fix(api): Update list of Tekton final status for api and persistent agent.

samples/kfp-user-guide/README.md
Resolves #
Add some best practice to address #330 for some of the volume problem for Tekton and Argo executors that need volume mount. Currently the root path artifact/parameter files only works well with Argo's docker executor, so we need to find a way to parametrize the volume path inside the kale sdk. 
**Checklist:**
Use `feat` to …
=> Add best practice for tekton and other argo executors

kfp-admin-guide.md
Resolves #
**Checklist:**
Use `part of` to indicate that a PR is working on an issue, but shouldn't close …
=> Add s3 endpoint instructions for admin use case

samples/titanic-ml-dataset/titanic-ml.py
updated .py file with latest kale 0.5.1
currently won't compile with kfp-tekton 0.3 sdk
=> updated titanic-ml generated with kale 0.5.1

sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/testdata/condition.py, sdk/python/tests/compiler/testdata/condition.yaml
Resolves #341 
Big data passing didn't sanitize all the inputs/outputs variables. Here is a quick fix to unblock #341. Refactor will be in another PR to move the sanitization out of big data passing to cover #342 . 
**Checklist:**
Use …
=> fix(sdk): Quick fix for sanitizing conditional variables

frontend/src/pages/RunDetails.tsx
Resolves #
There's a small UI merge conflict that breaks one of the image builds. This PR fixes this bug to make the build passes.
**Checklist:**
* …
=> Fix UI merge conflict that blocks the UI image build.

Makefile, install/v0.4.0/kfp-tekton.yaml, manifests/kustomize/env/kfp-template/kustomization.yaml, manifests/kustomize/env/kfp-template/namespace.yaml, release.md, tekton_kfp_guide.md
Resolves #
Add KFP Tekton release deployment yaml that can be used with basic `kubectl` without knowing how to use kustomize. Also adding a makefile command to generate the deployment yaml.
**Checklist:**
Use `chore` to indicate that …
=> Add KFP Tekton release deployment yaml

backend/src/apiserver/common/config.go, backend/src/apiserver/resource/resource_manager.go
Extend artifacts copy step configuration with the container template.
Resolves #333
The new `ARTIFACT_COPY_STEP_TEMPLATE` configuration option is introduced that allow to provide a customisable copy step container template. It is extremely useful in case of custom steps that require access to specific secrets or env variables.
**Checklist:**
* `feat(backend): configurable service account. Fixes #1234, fixes …
=> feat(backend): ARTIFACT_COPY_STEP_TEMPLATE - custom template for copy step

samples/kfp-user-guide/README.md
Documentation on migration from Argo.
=> docs: migration from Argo

OWNERS
Promoting @drewbutlerbb4 as a Committer in KFP-Tekton project. He  has contributed heavily to the Kubeflow Pipelines Tekton project,  supporting KFP UI, Tekton Conditions in the compiler, parser for the Tekton equivalent of the Argo workflow in the KFP-Tekton frontend, parsing and displaying the DAG, retrieving archived logs etc.
Additionally he has sustained record of reviewing PRs and maintaining the project.
**PRs Committed**
https://github.com/kubeflow/kfp-tekton/pull/84
https://github.com/kubeflow/kfp-tekton/pull/91
https://github.com/kubeflow/kfp-tekton/pull/105
https://github.com/kubeflow/kfp-tekton/pull/167
https://github.com/kubeflow/kfp-tekton/pull/178
https://github.com/kubeflow/kfp-tekton/pull/196
https://github.com/kubeflow/kfp-tekton/pull/220 …
=> Making Andrew Butler a committer in KFP-Tekton project

sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/create_component_from_func.py, sdk/python/tests/compiler/testdata/create_component_from_func.yaml, sdk/python/tests/compiler/testdata/create_component_from_func_component.yaml
Resolves #340
Handle big data passing with multi dependencies
Before fix, there is error if the task depends on multi dependencies, as picture:
After fix, as below, it is correct now:
Add it as our test cases and UT PASS:
```
>> ./run_tests.sh
test_affinity_workflow (compiler.compiler_tests.TestTektonCompiler) ... /Users/fengli/go/src/github.com/kubeflow/kfp-tekton/.venv/lib/python3.6/site-packages/kfp/dsl/_container_op.py:1025: DeprecationWarning: Please create reusable components instead of constructing ContainerOp instances directly. Reusable components are shareable, portable and have compatibility and support guarantees. Please see the documentation: …
```
=> Fix #340: handle big data passing with multi dependencies

frontend/src/lib/StaticGraphParser.ts, frontend/src/lib/WorkflowParser.ts
Resolves #327
Adds an edge between dependencies based on the `when` expression.
**Checklist:**
Use `part of` …
=> feat(ui) Update UI to account for the When expression

frontend/src/pages/PipelineDetails.tsx, frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
Resolves #364
Yaml file cannot show with Safari browser
Root-Cause: react-ace Editor doesn't support in Safari when height or width is a percentage
After fixed, both Chrome and Safari browser are OK now:
**Checklist:**
Use `chore` to …
=> Fix the yaml cannot show in Safari browser issue

frontend/src/lib/WorkflowParser.ts, frontend/src/pages/RunDetails.tsx
Resolves #372
Make the skipped tasks more accurate in UI display.
The flow is more meanful now:
**Checklist:**
* `test: fix CI failure. Part of …
=> fix(frontend): enhance the when condition UI display

guides/developer_guide.md
Resolves # n/a
Update broken link used to clone this repo.
* Python Version (use `python --version`): n/a
* OS (e.g. from `/etc/os-release`): n/a
**Checklist:**
Use `part of` to …
=> Fix broken clone link

guides/kfp_tekton_install.md, install/v0.4.0/kfp-tekton.yaml, manifests/kustomize/env/kfp-template/application-crd.yaml, manifests/kustomize/env/kfp-template/kustomization.yaml, manifests/kustomize/env/kfp-template/scheduled-workflow-crd.yaml, manifests/kustomize/env/kfp-template/viewer-crd.yaml
Resolves #375
Following the Knative approach to deploy the crd first in order to avoid the race condition. 
**Checklist:**
* `test: fix CI failure. …
=> Fix race condition on stand alone deployment

.travis.yml, Makefile
Resolves # n/a
Add build test for apiserver, agent, and workflow to travis
* Python Version (use `python --version`): n/a
* OS (e.g. from `/etc/os-release`): n/a
**Checklist:** …
=> test: Add build test for apiserver, agent, and workflow

sdk/python/README.md
Resolves #
One of the links in the python dev readme is broken. Update the link to make the travis test pass.
**Checklist:**
* `test: fix CI …
=> Update broken link to pass travis test

install/v0.4.0/kfp-tekton.yaml, manifests/kustomize/env/platform-agnostic/kfp-pipeline-config.yaml
Resolves #
15 hours ago, Minio released their new image with redhat ubi as their based image. The ubi image doesn't come with the `tar` command for packaging artifacts into tar.gz files. Therefore, we make minio to use a fixed version for now, and may need to create our own custom minio image in the future if this becomes the default behavior. 
This only happens with kfp-tekton because we are using the minio image to package our artifacts because we don't have any custom sidecar image.
**Checklist:**
* …
=> Use fixed version of minio image

backend/README.md
Resolves #
KFP moved away from Bazel for all the non-api testing. Updating the instructions to fit with the current kfp-tekton codebase.
**Checklist:**
Use `chore` to indicate that this PR makes some changes that users don't need to …
=> Update the backend test instructions with go test

guides/kfp_tekton_install.md, install/v0.5.0/kfp-tekton.yaml, manifests/kustomize/env/kfp-template/kustomization.yaml
Resolves #
Previously the release yaml gen didn't merge correctly with the kfp 1.0.4. So it was pointing to the latest tag image.
**Checklist:**
* …
=> Update 0.5 release reference

.travis.yml, Makefile, scripts/check_diff.sh
Resolves # n/a
Add docker image build tests for backend to travis
* Python Version (use `python --version`): n/a
* OS (e.g. from `/etc/os-release`): n/a
**Checklist:**
Use `part …
=> test: Add docker image build tests for backend

sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/testdata/condition.py, sdk/python/tests/compiler/testdata/condition.yaml, sdk/python/tests/compiler/testdata/condition_dependency.yaml
Resolves #397 
Fix neted condition bug and update unit tests to cover the new edge cases.
* Tekton Version (use `tkn version`): 0.16
**Checklist:**
* `test: fix CI failure. Part …
=> fix(sdk): Fix nested condition bug

backend/src/agent/persistence/worker/metrics_reporter.go, backend/src/agent/persistence/worker/metrics_reporter_test.go, backend/src/agent/persistence/worker/persistence_worker_test.go, backend/src/agent/persistence/worker/workflow_saver_test.go
Related #388
Update persistence agent unit tests to remove argo related code.
**Checklist:**
Use `part of` …
=> test: update persistence agent unit tests. Part of #388

tekton-catalog/any-sequencer/Makefile, tekton-catalog/any-sequencer/cmd/main.go
Resolves #409 
The PR is going to enhance `Any Sequencer`:
1. If all dependencies failed, the Any Sequencer should be marked to "Failed" and exit.
2. Since the k8s `watch` while timeout sometimes, we should add a loop to renew the watch. Thanks.
**Checklist:**
* `chore: set up …
=> Enhance Any Sequencer

sdk/FEATURES.md
point to any sequencer design, and correct some verbiage
=> add any sequencer design pointer

Makefile
n/a
`run-go-unittests` did not previously include running the persistence agent unit tests. This includes them with the run.
**Checklist:**
* `test: …
=> test: include persistence agent unit tests in makefile run

sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py, sdk/python/kfp_tekton/compiler/_tekton_hander.py, sdk/python/kfp_tekton/compiler/any_sequencer.py, sdk/python/tests/compiler/testdata/any_sequencer.yaml
With the PR https://github.com/kubeflow/kfp-tekton/pull/421 changes, the Tekton pipeline level variables can be used in `containerOps` directly, the PR is going to update `Any Sequencer` to use the Tekton pipeline level variables directly, instead of defining that as `params`
**Checklist:**
Use `feat` to indicate that this PR adds a …
=> Enhance Any Sequencer by using Tekton Pipeline Variables Fature

install/v0.6.0/kfp-tekton.yaml, manifests/kustomize/env/kfp-template/kustomization.yaml
=> generate init 0.6.0 release manifests

samples/exit-handler-email/send-email.py, sdk/K8S_CLIENT_HELPER.md, sdk/README.md, sdk/python/kfp_tekton/compiler/_k8s_helper.py, sdk/python/kfp_tekton/k8s_client_helper.py
Resolves #366
For some commonly used k8s resources, it's annoying to ask users to add their copy the example helper functions when they are creating their own custom pipeline. Thus, This PR set up the ground work and added the helper function for loading env from k8s secrets to begin with.
@jinchihe 
**Checklist:**
=> Add user helper functions for loading env from k8s secrets

sdk/FEATURES.md
=> Rephrase sidecars doc and fix some grammar

.tekton/listener.yaml, .tekton/pipeline.yaml, .tekton/task.yaml, scripts/deploy/iks/build-image.sh, scripts/deploy/iks/e2e-test.sh
In order to run tekton pipeline on IKS, need to define
listener, pipeline and task YAMLs. Inside the pipeline YAML,
it defines a series of tasks to git clone, run unittest, build images,
deploy tekton, deploy kfp-tekton, run e2e test and undeploy.
Resolves #
**Checklist:**
=> test: Add pipeline yaml for tekton pipeline

sdk/FEATURES.md, sdk/python/kfp_tekton/compiler/_tekton_hander.py, sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.py, sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml, sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving_pipelineloop_cr1.yaml, sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving_pipelineloop_cr2.yaml, sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving_pipelineloop_cr3.yaml, sdk/python/tests/compiler/testdata/withparam_global_dict.log, sdk/python/tests/compiler/testdata/withparam_global_dict.py, sdk/python/tests/compiler/testdata/withparam_global_dict.yaml, sdk/python/tests/compiler/testdata/withparam_global_dict_pipelineloop_cr1.yaml, sdk/python/tests/compiler/testdata/withparam_output_dict.log, sdk/python/tests/compiler/testdata/withparam_output_dict.py, sdk/python/tests/compiler/testdata/withparam_output_dict.yaml, sdk/python/tests/compiler/testdata/withparam_output_dict_pipelineloop_cr1.yaml, tekton-catalog/pipeline-loops/examples/pipelinespec-with-nested-loop.yaml, tekton-catalog/pipeline-loops/examples/pipelinespec-with-run-dict-value.yaml, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Resolves #413
Support loop pipelineruns of defining dictionaries params
Now all kinds of for_loop dsl are supported.
/cc @Tomcli 
**Checklist:**
=> feat(backend): Support loop pipelineruns of defining dictionaries params

api/v2alpha1/python/setup.py, sdk/python/setup.py, sdk/python/tests/compiler/testdata/basic_no_decorator.py, sdk/python/tests/compiler/testdata/basic_no_decorator.yaml, sdk/python/tests/compiler/testdata/compose.py, sdk/python/tests/compiler/testdata/compose.yaml, sdk/python/tests/compiler/testdata/imagepullsecrets.py, sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
Updating a few SDK files remaining after #463
Related #463
/cc @Tomcli 
/assign @Tomcli
=> Remove Python 3.5 support (2)

.tekton/listener.yaml, .tekton/pipeline.yaml, .tekton/task.yaml, scripts/deploy/iks/e2e-test.sh
Send the e2e-test results to slack channel. The
message also encloses the link to details page of the
pipeline run.
Resolves #
**Checklist:**
=> test: Send results to slack channel

guides/kfp-user-guide/README.md
Fixed the example code to be PEP compliant.
* Tested by compiling and running the produced yaml on kubeflow pipelines on IKS cluster.
* Python Version (use `python --version`): Python 3.8.5
* Tekton Version (use `tkn version`): 
```
Client version: 0.15.0
Pipeline version: unknown, pipeline controller may be installed in another namespace please use tkn version -n {namespace}
Dashboard version: v0.7.1
```
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: …
```
=> docs: Fixed the code formatting of the echo example.

guides/kfp_tekton_install.md
Resolves #
There no cloud installation link anymore, replace it with the top level installation link
**Checklist:**
=> Fix deprecated link

samples/trusted-ai/trusted-ai.py
Resolves #
1.18 k8s with kubeflow 1.2.0
1.19 k8s with kubeflow 1.2.0
**Checklist:**
=>  fix: Migrate away from old katib api to ResourceOp.

samples/README.md, samples/nested-loops/README.md, samples/nested-loops/withitem_nested.py
Resolves #
This is an example to demonstrate how to use loops in KFP-Tekton and the complexity loops can be. This example also highlights the limitation of the current Tekton API and the importance to have custom task spec. 
**Checklist:**
=> Add nested loops example

sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/testdata/withitem_nested.py, sdk/python/tests/compiler/testdata/withitem_nested.yaml, sdk/python/tests/compiler/testdata/withitem_nested_pipelineloop_cr1.yaml, sdk/python/tests/compiler/testdata/withitem_nested_pipelineloop_cr2.yaml
Resolves #490
Handle the case of nested loop defined the dict parameters
**Checklist:**
/cc @Tomcli
=> fix(sdk): fix issue of nested dict param defined

sdk/python/kfp_tekton/compiler/_op_to_template.py
Resolves #493 
Just add guard code
=> Fix the copy result issue when it's already tekton result path

tekton-catalog/pipeline-loops/go.mod, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Resolves #
Upgrade tekton version to v0.20.0 to make consistency with other experiment projects
**Checklist:**
=> Upgrade tekton version to v0.20.0 for pipeline-loop

guides/kfp_tekton_install.md
related #509 #507
There's one github link broken after the kubeflow website refactor, updating it to the new correct link.
**Checklist:**
=> Fix broken links from kubeflow website

sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/recursion_while.py, sdk/python/tests/compiler/testdata/recursion_while.yaml, sdk/python/tests/compiler/testdata/recursion_while_pipelineloop_cr1.yaml
1: Support graph dsl for tekton backend
2: Support recursive graph for tekton backen
Resolves #501
=> Support graph and recursion for tekton backend

sdk/python/kfp_tekton/compiler/_k8s_helper.py, sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/k8s_helper_tests.py, sdk/python/tests/compiler/testdata/long_pipeline_name.py, sdk/python/tests/compiler/testdata/long_pipeline_name.yaml, sdk/python/tests/compiler/testdata/long_pipeline_name_pipelineloop_cr1.yaml, sdk/python/tests/compiler/testdata/recursion_while.yaml
Resolves #518 
Fix resource names that will go beyond the k8s 63 chars limit. On both local and KFP runs.
* Tekton Version (use `tkn version`): 0.21.0
**Checklist:**
=> fix(sdk): Fix long resource name

sdk/python/kfp_tekton/compiler/compiler.py
Resolves #
Remove the unnecessary print statements and the deprecated telemetry code from the SDK.
**Checklist:**
=> Clean up sdk

sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/withitem_multi_nested.py, sdk/python/tests/compiler/testdata/withitem_multi_nested.yaml, sdk/python/tests/compiler/testdata/withitem_multi_nested_pipelineloop_cr1.yaml, sdk/python/tests/compiler/testdata/withitem_multi_nested_pipelineloop_cr2.yaml, sdk/python/tests/compiler/testdata/withitem_multi_nested_pipelineloop_cr3.yaml, sdk/python/tests/compiler/testdata/withitem_multi_nested_pipelineloop_cr4.yaml
Resolves #519
Fix nested loop params issue, and ensure multi nested loop works well
**Checklist:**
=> Fix(sdk): Fix nested loop params issue, and ensure multi nested loop works well

manifests/kustomize/env/platform-agnostic/kfp-pipeline-config.yaml, samples/README.md, samples/tekton-custom-task/README.md, samples/tekton-custom-task/tekton-custom-task.py, sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py, sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/kfp_tekton/tekton.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/tekton_custom_task.py, sdk/python/tests/compiler/testdata/tekton_custom_task.yaml
Resolves #498
This PR introduces new ways to define Tekton custom task. It's extracted from PR #478 to unblock issue #498 since it's considered as a separate feature.
Design doc for user definable custom task: https://docs.google.com/document/d/14PEuKY6T1ku4uFZx12FLFEPNE8poTdZRlzj6RDT3YKk/edit#
**Checklist:**
=> feature(sdk): Add custom task definition support

samples/tekton-custom-task/tekton-custom-task.py, sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/testdata/tekton_custom_task.py, sdk/python/tests/compiler/testdata/tekton_custom_task.yaml
Resolves #527
Fix regex parsing for custom task to handle multiple pipeline params
cc @Udiknedormin 
**Checklist:**
=> fix(sdk): Fix regex parsing for custom task to handle multiple pipeline params

.tekton/tekton-catalog/pipeline.yaml, scripts/deploy/iks/tekton-catalog/deploy-pipeline-loops-e2e.sh
update the script to adopt a change in
`open-toolchain/tekton-catalog` repo
Resolves #
**Checklist:**
=> [test] fix tekton-catalog test script

.tekton/listener.yaml, .tekton/pipeline.yaml, .tekton/task.yaml, scripts/deploy/iks/build-image.sh, scripts/deploy/iks/publish-image.sh
the kfp-tekton deployment manifest already includes
tekton, therefore, remove the tekton deploy/undeploy tasks
also add tasks to build cacheserver and frontend
Resolves #
**Checklist:**
=> [test] Remove tekton installation task

sdk/python/tests/compiler/testdata/any_sequencer.log, sdk/python/tests/compiler/testdata/any_sequencer.py, sdk/python/tests/compiler/testdata/any_sequencer.yaml
I uploaded image and did E2E test. Found the example is not reasonable, because the flip-coin to show the condition will never run because task1 just succeed quickly.
Here update the example then it make more sense, thanks.
=> Adjust the any sequencer example to make it more reasonable

samples/katib/early-stopping.ipynb
Update the notebook to use newer packages and image.
Also add instructions for multi-user environment.
=> Update katib sample

Makefile, guides/kfp_tekton_install.md, install/v0.8.0/kfp-tekton.yaml, manifests/kustomize/base/pipeline/kustomization.yaml, manifests/kustomize/env/kfp-template/application-crd.yaml, manifests/kustomize/env/kfp-template/kustomization.yaml, manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml, sdk/README.md
Resolves #
Create release 0.8.0 standalone install and remove the application crd from kubeflow 1.2 deployment.
**Checklist:**
=> Create release 0.8.0 standalone install

sdk/FEATURES.md, sdk/python/kfp_tekton/tekton.py, tekton-catalog/any-sequencer/cmd/root.go
1: Add log when condition check suceeded.
2: Fix the issue when task list is not provided.
3: Fix the issue when there's multiple results provided
4: Update the document
Resolves #551 #552 #553
=> Fix multiple any-sequencer issues

sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/cond_recur.py, sdk/python/tests/compiler/testdata/cond_recur.yaml, sdk/python/tests/compiler/testdata/cond_recur_pipelineloop_cr1.yaml
Resolves #547 
Fix the second issue in #547. Notice this can be common issue for custom task and now there's only loop.
=> Fix the issue when there's a conditional loop

OWNERS
Plan to keep contributing on the kfp-tekton project and want to apply to be reviewer now, please approve.
=> Apply to be reviewer

.tekton/listener.yaml, .tekton/pipeline.yaml, .tekton/task.yaml, scripts/deploy/iks/helper-functions.sh, scripts/deploy/iks/tekton-catalog/cleanup.sh, scripts/deploy/iks/tekton-catalog/deploy-kubectl-wrapper-e2e.sh
move kubeclient test case to e2e toolchain pipelines. consolidate two testing pipelines into
one pipeline.
**Checklist:**
- [x ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 
=> [test] move kubeclient test case

sdk/README.md, sdk/python/README.md
**Description of changes:**
Adding badges to the SDK `README.md`. Why? Looks cool! 😎 
[![PyPI](https://img.shields.io/pypi/v/kfp-tekton?label=PyPI)](https://pypi.org/project/kfp-tekton/) [![PyPI - Downloads](https://img.shields.io/pypi/dm/kfp-tekton?label=Downloads)](https://pypi.org/project/kfp-tekton/#files) [![PyPI - License](https://img.shields.io/pypi/l/kfp-tekton?label=License)](https://www.apache.org/licenses/LICENSE-2.0)
**Tested how:**
Visual inspection, manual clicking of links.
/cc @Tomcli
=> Add bagdes to SDK Readme

scripts/deploy/iks/README.md, scripts/deploy/iks/deploy-ibm-vpc.sh, scripts/deploy/iks/deploy-kfp-ibm-vpc.sh
Resolves #
Added a script to create a vpc-gen2 cluster and deploy kubeflow on IBM Cloud IKS.
=> feat(script): Deploy kubeflow to IBM Cloud IKS vpc-gen2, using this script.

guides/kfp_tekton_install.md, manifests/kustomize/base/installs/multi-user/cache/cluster-role.yaml
=> Add instructions on upgrade kfp-tekton multi-users and fix new multi-users permission

tekton-catalog/any-sequencer/cmd/root.go
Resolves #
Currently the Any Sequencer support watching taskrun and conditions, do not support watching run, the PR is going to support that.
**Checklist:**
=> Enhance Any Sequencer to support watching run

sdk/python/kfp_tekton/tekton.py, sdk/python/tests/compiler/testdata/any_sequencer.py, sdk/python/tests/compiler/testdata/any_sequencer.yaml
=> Support expose status for any sequencer(DSL side)

sdk/FEATURES.md, tekton-catalog/any-sequencer/cmd/root.go, tekton-catalog/any-sequencer/go.sum
Resolves #594 
The backend changes, will do more test.
=> Support expose status for any sequencer(backend)

sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/long_pipeline_name.yaml, sdk/python/tests/compiler/testdata/recur_nested.py, sdk/python/tests/compiler/testdata/recur_nested.yaml, sdk/python/tests/compiler/testdata/recur_nested_pipelineloop_cr1.yaml, sdk/python/tests/compiler/testdata/recur_nested_pipelineloop_cr2.yaml
=> Fix and verify nested recursive workflow

tekton-catalog/any-sequencer/cmd/root.go
=> Change status for successful from "Succeeded" to "Completed"

guides/kfp-user-guide/README.md, sdk/README.md
Resolved typos in the files.
Updated guides/kfp-user-guide/README.md and sdk/README.md
Visually inspected the files.
**Checklist:**
=> doc: Update README.md typos

tekton-catalog/pipeline-loops/go.mod, tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_validation_test.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Need to fix the tests.
Resolves #
**Checklist:**
=> fix(pipelineLoop): Update to latest tekton release v0.25.0.

.github/workflows/kfp-tekton-unittests.yml
Resolves #
Just realized the Github Actions won't run on branches that don't have push permission. Change to another method to trigger actions for all the PR in this repo.
**Checklist:**
=> Update Github Action PR trigger

sdk/python/kfp_tekton/tekton.py
Support custom image for any Seq, as for security scan, user may need to use the internal image.
**Checklist:**
=> Support custom image for any Seq

OWNERS
I implemented some features and committed some PRs in the repo, and now my projects is using the kfp-tekton projects. 
Applying to reviewer for more contributions. Thanks.
=> Add jinchihe in the OWNER list

OWNERS
I have implemented some features like recursion/graph/parallel loop/any-sequencer, and resolved some issues which make me familiar with the code and features. Would like to be approver and will continue contributing in future. Thanks!
=> Add Gang Pu as approver

sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/loop_in_recursion.py, sdk/python/tests/compiler/testdata/loop_in_recursion.yaml, sdk/python/tests/compiler/testdata/loop_in_recursion_noninlined.yaml, sdk/python/tests/compiler/testdata/loop_in_recursion_pipelineloop_cr1.yaml
Resolves #647 
It's not related to inline custom task feature, it's because the loop task does not added to a conditional graph. This PR fix it.
=> Fix the issue when loop/graph inside a graph

.github/workflows/kfp-tekton-unittests.yml, samples/watson-train-serve/README.md, tekton-catalog/pipeline-loops/Makefile, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
#644
Fixed tests,
And for those tests, that are not yet fixed. ADDED a TODO to do it later.
Following failures:
```
pipelinelooprun_test.go:1261: Error reconciling: 1 error occurred:
177
* error creating PipelineRun from Run run-pipelineloop: pipelineruns.tekton.dev "run-pipelineloop-00001-9l9zj" already exists
```
**Checklist:**
=> Fix: go tests for pipelineLoop controller.

frontend/src/lib/StaticGraphParser.ts, frontend/src/lib/WorkflowParser.ts, sdk/FEATURES.md, sdk/python/kfp_tekton/tekton.py, sdk/python/tests/compiler/testdata/any_sequencer.yaml, sdk/python/tests/compiler/testdata/any_sequencer_noninlined.yaml, tekton-catalog/any-sequencer/Dockerfile, tekton-catalog/any-sequencer/Makefile, tekton-catalog/any-sequencer/README.md, tekton-catalog/any-sequencer/cmd/root.go, tekton-catalog/any-sequencer/main.go
Resolves #652 
Enhance Any Sequencer to hanle cases that some tasks skipped. For example, Any Seq depends on task1 and task2, task1 failed and task2 skipped, the Any Seq will hangs. The pr is going to fix the issue.
**Checklist:**
=> Enhance Any Sequencer to hanle cases that some tasks skipped

sdk/python/kfp_tekton/compiler/compiler.py
Resolves #661
Sorted params in `PipelineRun.Spec.Params`.
**Checklist:**
=> fix(sdk): sort params to fix flaky tests.

tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
=> fix(pipelineloop): restored pipelineloop conditions test.

Makefile, sdk/python/tests/compiler/testdata/conditions_and_loops.py, sdk/python/tests/compiler/testdata/conditions_and_loops.yaml, sdk/python/tests/compiler/testdata/conditions_and_loops_noninlined.yaml, sdk/python/tests/compiler/testdata/conditions_with_global_params.py, sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml, sdk/python/tests/compiler/testdata/conditions_with_global_params_noninlined.yaml, tekton-catalog/pipeline-loops/Makefile, tekton-catalog/pipeline-loops/cmd/cli/main.go
=> feat(sdk): Add pipelineloop validation for testdata yamls.

sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/conditions_and_loops.py, sdk/python/tests/compiler/testdata/conditions_and_loops.yaml, sdk/python/tests/compiler/testdata/conditions_and_loops_noninlined.yaml, sdk/python/tests/compiler/testdata/conditions_with_global_params.py, sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml, sdk/python/tests/compiler/testdata/conditions_with_global_params_noninlined.yaml
Resolves #664 
In test to dump yaml should use the same method as is in compile which is customized to process the boolean values.
=> Fix the yaml dump issue of boolean value

samples/nested-loops/README.md
Resolves #
Update loop instructions to use inline spec, so users no longer need to apply the loop crd separately.
**Checklist:**
=> Update loop instructions to use inline spec

tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Resolves #668
Sort params at all levels in a PipelineRun.
**Checklist:**
=> fix(pipelineloop): sort params to fix flakiness in tests.

sdk/python/kfp_tekton/tekton.py
Part of  #670 
containerOp is going to be deprecated in the next few months, This PR demonstrates how to migrate the helper function for defining user custom task from the containerOp to component yaml.
There should be no functional change and produce the exact same Tekton yaml for this migration.
**Checklist:**
=> Convert user custom task from containerOp to component yaml

samples/flip-coin/condition.py, samples/nested-pipeline/compose.py, samples/trusted-ai/trusted-ai.py
update flip-coin, nested-pipeline and trusted-ai
related to issue #670
remove `contaionOp` in these samples.
Python 3.9.6
Client version: 0.8.0
=> remove ContainerOp in some samples

samples/lightweight-component/calc_pipeline.py, samples/nested-loops/withitem_nested.py
Part of #670
Nested loop and lightweight component are examples that doesn't depend on any external component and sdk changes. Thus moving them to follow the component.yaml format.
**Checklist:**
=> Convert loop and lightweight example to component yaml

sdk/python/kfp_tekton/tekton.py, sdk/python/tests/compiler/testdata/any_sequencer.py, sdk/python/tests/compiler/testdata/any_sequencer.yaml, sdk/python/tests/compiler/testdata/any_sequencer_noninlined.yaml
=> Change to use component to replace containerOp for any sequencer

samples/e2e-mnist/README.md, samples/flip-coin-custom-task/condition.py, samples/tekton-custom-task/tekton-custom-task.py, sdk/python/kfp_tekton/tekton.py
Related #670
Move custom task examples to use component.yaml only and make them compilable on v2 compiler. 
**Checklist:**
=> Update custom task to work with v2 compiler

sdk/python/kfp_tekton/compiler/_k8s_helper.py, sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/kfp_tekton/tekton.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/long_pipeline_name.yaml, sdk/python/tests/compiler/testdata/long_pipeline_name_noninlined.yaml, sdk/python/tests/compiler/testdata/long_recursive_group_name.py, sdk/python/tests/compiler/testdata/long_recursive_group_name.yaml, sdk/python/tests/compiler/testdata/long_recursive_group_name_noninlined.yaml, sdk/python/tests/compiler/testdata/long_recursive_group_name_pipelineloop_cr1.yaml, sdk/python/tests/compiler/testdata/loop_in_recursion.yaml, sdk/python/tests/compiler/testdata/loop_in_recursion_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_recur_runafter.yaml, sdk/python/tests/compiler/testdata/nested_recur_runafter_noninlined.yaml, sdk/python/tests/compiler/testdata/recur_nested.yaml, sdk/python/tests/compiler/testdata/recur_nested_noninlined.yaml, sdk/python/tests/compiler/testdata/recur_nested_separate.yaml, sdk/python/tests/compiler/testdata/recur_nested_separate_noninlined.yaml, sdk/python/tests/compiler/testdata/recursion_while.yaml, sdk/python/tests/compiler/testdata/recursion_while_noninlined.yaml
Resolves #683 
The current loop resource group name mapping has to be exact in a lot of placing because those information is not part of the Python DSL attribute. Thus, updating the code to change the loop resource pipeline name limit to 40 and add new mapping to introduce loop resource group name limit.
The loop resource group name limit is truncated reversely because the Python DSL introduced the unique ID at the end of each group name where we need to keep it.
**Checklist:**
[Learn more about cherry-picking updates into …
=> Update code to limit loop resource group name

.github/workflows/kfp-tekton-unittests.yml, Makefile, tekton-catalog/pipeline-loops/cmd/cli/main.go
Related #137 
Since the Tekton community doesn't validate the yaml without Tekton deployment, we need to have a new way to validate all the generated Tekton yaml in our unit tests without using Kubernetes. Thus, we enhance the pipelineloop cli validator command to also include regular Tekton pipelineSpec. 
This PR also breaks down the Makefile unit_test command so that developers don't need golang to regenerate Python yaml.
* Tekton Version (use `tkn version`): Don't rely on Tekton deployment
* Kubernetes Version (use `kubectl version`): Don't rely on Kubernetes
* OS (e.g. from `/etc/os-release`): MacOS
**Checklist:**
[Learn more about …
=> Enhance unit tests with local Tekton pipeline spec validation

samples/README.md, samples/k8s-downstream-api/README.md, samples/k8s-downstream-api/k8s-downstream-api.py
Resolves #
Add an example for how to use Kubernetes downstream API to get metadata information such as kfp name and id.
**Checklist:**
=> Add kfp name and id example

sdk/python/tests/compiler/testdata/resourceop_basic.py, sdk/python/tests/compiler/testdata/resourceop_basic.yaml, sdk/python/tests/compiler/testdata/resourceop_basic_noninlined.yaml
Resolves #
One of the test cases was broken due to mismatching resource name. Fix it by renaming the tests.
**Checklist:**
=> Fix e2e test case

sdk/python/kfp_tekton/compiler/_op_to_template.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/many_results.py, sdk/python/tests/compiler/testdata/many_results.yaml, sdk/python/tests/compiler/testdata/many_results_noninlined.yaml
Resolves #710 
When the parameter is not yet part of the Tekton results, the sanitization should not remove capital and underscore letters. We should only sanitize the name for Tekton results when it actually treated as a Tekton variable.
**Checklist:**
=> Fix(sdk): Tekton copy result step sanitization

sdk/python/tests/compiler/testdata/input_artifact_raw_value.py, sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml, sdk/python/tests/compiler/testdata/input_artifact_raw_value_noninlined.yaml, sdk/python/tests/compiler/testdata/pipelineparams.py, sdk/python/tests/compiler/testdata/pipelineparams.yaml, sdk/python/tests/compiler/testdata/pipelineparams_noninlined.yaml
Related #670 
Remove containerOp from pipelineparam and input artifact raw samples based on the KFP community's suggestions. 
**Checklist:**
=> Remove containerOp for pipelineparam and raw input samples

README.md
refer the project as Kubeflow Pipelines on Tekton, plus rearrange a bit
=> name consistency

samples/katib/early-stopping.ipynb
Update pip packages and remove the usage of
`dsl.ContainerOp`.
**Checklist:**
=> [test] update sample for katib

sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/kfp_tekton/compiler/compiler.py
Resolves #735 
Reduce the number of writing and loading into YAML/JSON during compile time. This should reduce the compile time for 0.08-0.1s. 
E.g. The flip-coin example is reduced from 0.25s to 0.13s. 
**Checklist:**
=> Optimize kfp-tekon SDK compile time

sdk/python/kfp_tekton/compiler/_op_to_template.py, sdk/python/tests/compiler/testdata/many_results.yaml, sdk/python/tests/compiler/testdata/many_results_noninlined.yaml
Resolves #738
Sanitise output paths passed to `tekton.dev/artifact_items` annotation, as they seem to be sanitised in the actual step's implementation.
**Checklist:**
=> fix(sdk) sanitize paths in artifact_items. Fixes #738

sdk/python/kfp_tekton/compiler/_op_to_template.py
Feature request.
Factor out the images used for copying steps, both the ones in multi-step and the copy-artefacts. Thanks to that, they can be easily overwritten if needed, without adding additional parameters to the already complex `compile` method.
**Checklist:**
=> feat(sdk): factor out the images to use in copying steps

README.md, tekton-catalog/pipeline-loops/examples/loop-example-workspaces.yaml, tekton-catalog/pipeline-loops/go.mod, tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Resolves #786
Added support for supporting workspaces in pipelineLoopSpec. 
Added tests and examples.
**Checklist:**
=> feat(pipelineloop): Support workspaces for pipelineLoop.

sdk/python/tests/compiler/performance_tests.py
Get taskRun and run details into the output CSV
Related to: #779
=> [test] Add taskRun and run into the report

sdk/python/tests/compiler/performance_tests.py, sdk/python/tests/compiler/testdata/calc_pipeline.py, sdk/python/tests/compiler/testdata/condition_custom.py, sdk/python/tests/compiler/testdata/condition_sample.py, sdk/python/tests/compiler/testdata/trusted_ai.py, sdk/python/tests/perf_test_config.yaml
Resolves #
Fix the custom task bug in the performance test script and update the list of testing example to be sequential. 
**Checklist:**
=> Fix performance test script and update testing examples

.github/workflows/kfp-tekton-unittests.yml, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
=> feat(pipelineloop): Break operation for pipelineloop.

tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Resolves #775
How to configure:
```
apiVersion: custom.tekton.dev/v1alpha1
kind: PipelineLoop
metadata:
name: pipelineloop
annotations:
maxNestedStackDepth: "10"
spec:
```
**Checklist:**
=> fix(pipelineloop): Nested call stack depth limit

sdk/python/tests/compiler/testdata/tekton_loop_dsl.yaml, sdk/python/tests/compiler/testdata/tekton_loop_dsl_noninlined.yaml
Resolves #
Regenerate python tests from the last few commit merges.
**Checklist:**
=> Chore: regenerate python tests

tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Resolves #819
Cancel all the running pipelines started by the current Run.
**Checklist:**
=> fix(pipelineloop): break loop should cancel all pipeline runs.

OWNERS
Resolves #
Clean up owners file so PR can assign to the correct reviewers
**Checklist:**
=> Clean up owners file

sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/kfp_tekton/tekton.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/loop_literal_separator.py, sdk/python/tests/compiler/testdata/loop_literal_separator.yaml, sdk/python/tests/compiler/testdata/loop_literal_separator_noninlined.yaml
Resolves one of two options described in #791.
Handle `separator` field in `Loop` class of Tekton DSL extensions.
A new, uniquely-named separator param is added to the parameters. Its name is added as the value for a new field, `iterateParamStringSeparator`.
* Python Version (use `python --version`): 3.9.7
**Checklist:**
=> feat(sdk): implement loop DSL ext: from_string. Part of #791

tekton-catalog/pipeline-loops/examples/loop-example-basic.yaml
add double quotes to the value of `true`
Resolves #
**Checklist:**
=> [test] fix typo in pipeline-loop example

sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/loop_empty.py, sdk/python/tests/compiler/testdata/loop_empty.yaml
Resolves #863.
Treat no-tasks and `tasks: []` the same.
* Python Version (use `python --version`): 3.9.7
**Checklist:**
=> fix(sdk) add test for empty loops

tekton-catalog/objectstore/README.md, tekton-catalog/objectstore/go.mod, tekton-catalog/objectstore/pkg/writer/objectstore_writer.go
Resolves #
Part 2. of #873 
New object store package with readme on how to write artifacts/results of custom tasks to object store.
Tested on IBM Cloud:
**Checklist:**
=> feat(objectstore) Metadata object store

samples/e2e-mnist/README.md, samples/e2e-mnist/e2e-mnist.py, samples/e2e-mnist/mnist.ipynb
Use KServe for the model serving
=> [test] Update mnist-e2e sample

OWNERS
Resolves #
@yhwang has been contributed to KFP-Tekton for most of the testing and V2 features. Thus, adding him as the approver as more V2 features are coming soon.
**Checklist:**
=> Add yhwang as approver

sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/kfp_tekton/tekton.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/separator_from_param.py, sdk/python/tests/compiler/testdata/separator_from_param.yaml, sdk/python/tests/compiler/testdata/separator_from_param_noninlined.yaml, sdk/python/tests/compiler/testdata/separator_from_task.py, sdk/python/tests/compiler/testdata/separator_from_task.yaml, sdk/python/tests/compiler/testdata/separator_from_task_noninlined.yaml
Resolves #895
Processes `separator` just like `from`-`step`-`to`, enabling non-literals in it.
**Checklist:**
=> fix(sdk) add tests for non-literal separator

tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
=> fix(controller): Added fields serviceAccountName and PodTemplate to PipelineLoop.

sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/kfp_tekton/tekton.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/loop_with_enumerate_basic.py, sdk/python/tests/compiler/testdata/loop_with_enumerate_basic.yaml, sdk/python/tests/compiler/testdata/loop_with_enumerate_basic_noninlined.yaml, sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested.py, sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested.yaml, sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested_noninlined.yaml, sdk/python/tests/compiler/testdata/loop_with_numeric_enumerate.py, sdk/python/tests/compiler/testdata/loop_with_numeric_enumerate.yaml, sdk/python/tests/compiler/testdata/loop_with_numeric_enumerate_noninlined.yaml
Add helper function: `enumerate()` in Loop to
return indices and item. It could be used to get
the current iteration number and item value.
Resolves #890
**Checklist:**
=> feat(sdk): extension function `Loop.enumerate()`

tekton-catalog/pipeline-loops/examples/pipelinespec-with-run-iterate-numeric.yaml, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Resolves #903 
Changed implementation of IterationNumeric to contain the value of current iteration item.
IBM Cloud.
**Checklist:**
=> IterateNumeric behavior changed to contain the value of current interation item.

sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/node_selector_from_pipeline.py, sdk/python/tests/compiler/testdata/node_selector_from_pipeline.yaml, sdk/python/tests/compiler/testdata/node_selector_from_pipeline_override.py, sdk/python/tests/compiler/testdata/node_selector_from_pipeline_override.yaml
Handle the node selector info from PipelineConf in
the compiler. Node selector info in Op level could override
PipelineConf.
Resolves #915 
handle the node selector info in PipelineConf and
merge the Op level node selector as well.
* Python Version (use `python --version`): 3.9
**Checklist:**
=> fix(sdk): handle the node selectors

tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Resolves #902
1.  Support loop ranges with -ve values
2. Added validations and corresponding tests.
**Checklist:**
=> feat: Support loop ranges with -ve values.

sdk/python/README.md, sdk/python/kfp_tekton/__init__.py, sdk/python/setup.py, sdk/python/tests/compiler/testdata/resourceop_basic.yaml, sdk/python/tests/compiler/testdata/volume_op.yaml
Resolves #
Update SDK release to 1.2.1 to address some of the recent bugs we have fixed for resource op and loops. No changes on the backend and deployment side.
**Checklist:**
=> Update sdk release to 1.2.1

guides/advanced_user_guide.md, sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/kfp_tekton/tekton.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/exception.py, sdk/python/tests/compiler/testdata/exception.yaml
add a helper class for users to write a custom OpsGroup which maps to a custom task
in Tekton.
Resolves #912
Add a base class for custom OpsGroup and provide detailed usage under `Advanced User Guide`
* Python Version (use `python --version`): 3.9
**Checklist:**
=> feat(sdk): Add helper class AddOnGroup

.tekton/task.yaml
upgrade the golang to 1.17.6 and other
ibmcloud plugins
=> [build] update toolchain image

tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Resolves #
https://github.com/kubeflow/kfp-tekton/issues/943
as the title, add number of iterations limit support, set the default limit to 10000.
The value could be configured by environment `IterationLimit`
**Checklist:**
=> iteration limit support, default limit is 10000

sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/param_same_prefix.py, sdk/python/tests/compiler/testdata/param_same_prefix.yaml, sdk/python/tests/compiler/testdata/param_same_prefix_noninlined.yaml
Resolves #947 
Fix param prefix replacement code to only replace the task prefix once.
**Checklist:**
=> fix(sdk): Fix param prefix replacement

.github/workflows/kfp-tekton-unittests.yml, backend/Dockerfile, manifests/kustomize/env/platform-agnostic-kind/kustomization.yaml, scripts/deploy/github/build-images.sh, scripts/deploy/github/deploy-kfp.sh, scripts/deploy/github/e2e-test.sh
Add backend integration test to the GitHub workflow. it builds backend images, deploys, and runs a simple flip coin test.
**Checklist:**
=> feat(test): add backend integration test

guides/kfp_tekton_install.md
Resolves #
The lowest k8s cluster version I can create is `v1.21`. And also adding a local deployment.
**Checklist:**
=> update install guide

tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Resolves #
This is the supplement fix of PR https://github.com/kubeflow/kfp-tekton/pull/961
Cover the case `step from other task results`, previous PR only covered `from` and `to`
**Checklist:**
=> handle step from task results

sdk/python/requirements.txt, sdk/python/setup.py
Resolves #998
Update kfp dependency to latest fixpack version
* 3.8
**Checklist:**
=> `chore(sdk) Bump kfp dependency to 1.8.13`

sdk/python/README.md, sdk/python/kfp_tekton/__init__.py, sdk/python/setup.py, sdk/python/tests/compiler/testdata/resourceop_basic.yaml, sdk/python/tests/compiler/testdata/volume_op.yaml
Resolves #
Update KFP-Tekton SDK to include the new KFP 1.8.13 release for fixing urgent python typing bug.
**Checklist:**
=> Update sdk version to 1.2.3

sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py, sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/artifact_passing_using_volume.py, sdk/python/tests/compiler/testdata/artifact_passing_using_volume.yaml
Resolves #994 
Big data passing with user volume was not properly implemented in kfp-tekton. This feature is specifically for removing argo spec and replace the data passing with k8s pvc mount. Since kfp-tekton already using pvc mount for big data passing, we only need to apply the pipeline config to the workspace config.
Note in the original Argo version, the name of the volume is always fixed like our tekton big data passing since we need consistency names for the pipeline volume. Hence the volume name in kfp-tekton is also fixed to retain the same behavior.
https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/deprecated/compiler/_data_passing_using_volume.py#L54-L55
Also updating the …
=> sdk(feat): Add big data passing with custom volume on kfp-tekton

sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py, sdk/python/kfp_tekton/compiler/_op_to_template.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/big_data_multi_volumes_1.py, sdk/python/tests/compiler/testdata/big_data_multi_volumes_1.yaml, sdk/python/tests/compiler/testdata/big_data_multi_volumes_2.py, sdk/python/tests/compiler/testdata/big_data_multi_volumes_2.yaml
Resolves #990 
Fix the update volume function in op to template and data passing rewriter to make sure big data passing with multiple type of volume templates are working properly
**Checklist:**
=> fix(sdk): Fix big data passing with multiple type of volume templates

sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py, sdk/python/kfp_tekton/compiler/_k8s_helper.py, sdk/python/kfp_tekton/compiler/_op_to_template.py, sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/kfp_tekton/tekton.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/any_sequencer.yaml, sdk/python/tests/compiler/testdata/artifact_passing_using_volume.yaml, sdk/python/tests/compiler/testdata/big_data_passing.yaml, sdk/python/tests/compiler/testdata/conditions_and_loops.yaml, sdk/python/tests/compiler/testdata/conditions_and_loops_noninlined.yaml, sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml, sdk/python/tests/compiler/testdata/create_component_from_func.yaml, sdk/python/tests/compiler/testdata/custom_task_long_name.yaml, sdk/python/tests/compiler/testdata/custom_task_output.py, sdk/python/tests/compiler/testdata/custom_task_output.yaml, sdk/python/tests/compiler/testdata/data_passing_pipeline_complete.yaml, sdk/python/tests/compiler/testdata/katib.yaml, sdk/python/tests/compiler/testdata/loop_with_params_in_json.yaml, sdk/python/tests/compiler/testdata/many_results.yaml, sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml, sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving_noninlined.yaml
Resolves #1007 
Make output value to be case sensitive as some custom task might return case sensitive value and we cannot sanitize them as part of the compiler. 
**Checklist:**
=> Update result name to be case sensitive

sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/custom_task_exit.py, sdk/python/tests/compiler/testdata/custom_task_exit.yaml
=> fix(sdk): fix exit handler param with empty exit task

sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/condition_depend.py, sdk/python/tests/compiler/testdata/condition_depend.yaml, sdk/python/tests/compiler/testdata/loop_with_conditional_dependency.yaml, sdk/python/tests/compiler/testdata/loop_with_conditional_dependency_noninlined.yaml, sdk/python/tests/compiler/testdata/multi_nested_loop_condi.yaml
Resolves #1014 
Since Tekton 0.33, conditions for runafter tasks has different behavior where it only guard the task itself, not the whole chained dependency. Hence, we need to populate all the conditions for all the chained runafter tasks as well
**Checklist:**
=> fix(sdk): Add new logic to cover new tekton runafter condition

sdk/python/tests/compiler/testdata/condition_depend.yaml
=> fix(sdk): fix unit test merging conflicts

manifests/kustomize/third-party/kfp-csi-s3/csi-s3-deployment.yaml
Resolves #983 
Update s3 csi deployment to avoid conflicts with other s3-csi driver projects. Also update the s3-csi deployment config with the latest datashim 0.3.0 driver to support multi-arch cpu.
**Checklist:**
=> Update s3 csi deployment

.tekton/pipeline.yaml, scripts/deploy/iks/expect-cache.json, scripts/deploy/iks/expect-condition-depend.json, scripts/deploy/iks/test-cache.sh, scripts/deploy/iks/test-condition-depend.sh, sdk/python/tests/verify_result.py
add two test cases to verify
- taskruns/runs execution sequence
- caching function
**Checklist:**
=> Add test cases for sequence and cache

sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py, sdk/python/tests/compiler/testdata/artifact_outputs.yaml, sdk/python/tests/compiler/testdata/artifact_passing_using_volume.yaml, sdk/python/tests/compiler/testdata/big_data_passing.yaml, sdk/python/tests/compiler/testdata/create_component_from_func.yaml, sdk/python/tests/compiler/testdata/data_passing_pipeline_complete.yaml, sdk/python/tests/compiler/testdata/many_results.yaml, sdk/python/tests/compiler/testdata/many_results_with_warnings.yaml
Resolves #1008 
Rewrite the open source contribution of big data passing into more efficient way. This can help us reduce overall yaml size in etcd.
**Checklist:**
=> optimize(sdk): Rewrite data passing script into more optimized code

sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/finally_context_var.py, sdk/python/tests/compiler/testdata/finally_context_var.yaml
Resolves #
Add finally context var test case for #1035 so we can cover this edge case.
**Checklist:**
=> Add finally context var test case for #1035

backend/src/cache/server/watcher.go
Add check for type cast. make sure the watcher
receives Pod events.
**Checklist:**
=> fix(backend): add check for casting

guides/kfp_tekton_install.md, manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/kustomization.yaml, manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-default.yaml
=> Update tekton default timeout in global config

sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/nested_loop_counter.py, sdk/python/tests/compiler/testdata/nested_loop_counter.yaml, sdk/python/tests/compiler/testdata/nested_loop_counter_noninlined.yaml
Resolves #1046 
Numeric loop has populate parameters to handle the index param in that loop. However, in the nested loop scenario, the index parameter might get treated as global parameter due to some old logic assuming numeric loop param doesn't exist. Hence, update the logic to handle numeric loops in nested loop scenarios.
**Checklist:**
=> fix(sdk): Fix nested numeric parameters

README.md, backend/third_party_licenses/apiserver.csv, backend/third_party_licenses/cache_server.csv, backend/third_party_licenses/persistence_agent.csv, backend/third_party_licenses/swf.csv, go.mod, go.sum, guides/kfp_tekton_install.md, manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml, tekton-catalog/pipeline-loops/go.mod
Resolves #
Update Tekton to 0.38.4 to address the Tekton webhook validation degrade issue.
**Checklist:**
=> fix(backend): Update Tekton to 0.38.4

sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/kfp_tekton/tekton.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/last_idx.py, sdk/python/tests/compiler/testdata/last_idx.yaml, sdk/python/tests/compiler/testdata/last_idx_noninlined.yaml, sdk/python/tests/compiler/testdata/long_recursive_group_name.py, sdk/python/tests/compiler/testdata/long_recursive_group_name.yaml, sdk/python/tests/compiler/testdata/long_recursive_group_name_noninlined.yaml, tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Resolves #1041
**Checklist:**
cc @Tomcli
=> feat(pipelineloop): Support last_idx and last_elem

.tekton/pipeline.yaml, scripts/deploy/iks/test-many-edges.sh, scripts/deploy/iks/test/many-edges.py
Add a test to verify the performance of webhook
validation. huge amount of edges in DAG causes
a performance issue in tekton earlier. adding
this test case to avoid the performance degradation.
**Checklist:**
=> test: Add a test case for the validation

manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/204-cache-config.yaml, manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/301-breaktask.yaml, manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/kustomization.yaml
Resolves #
Patch cache config and break custom task to default pipelineloop deployment. So users can control the configuration more easily in the overall kustomization file.
**Checklist:**
=> fix(manifests): Patch cache config and break ct to default pl deployment

sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/kfp_tekton/tekton.py, sdk/python/tests/compiler/testdata/loop_with_numeric.py, sdk/python/tests/compiler/testdata/loop_with_numeric.yaml, sdk/python/tests/compiler/testdata/loop_with_numeric_noninlined.yaml
Resolves #1058 
Add new sdk support for new pipelineloop syntax. Two new fields iterateParamPassStyle and itemPassStyle, both of which can be either inline (default value) or file will sit on the same spec level as parallelism. The initial implementation is sdk support only.
**Checklist:**
=> feat(sdk): add iterateParamPassStyle and itemPassStyle params to loop

tekton-catalog/cache/go.mod, tekton-catalog/cache/pkg/db/db_conn_manager.go, tekton-catalog/cache/pkg/db/mysql.go, tekton-catalog/cache/pkg/db/sqlite.go, tekton-catalog/cache/pkg/task_cache_store.go, tekton-catalog/cache/pkg/task_cache_store_test.go, tekton-catalog/pipeline-loops/go.mod, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Resolves #1053 
**Checklist:**
=> fix(pipelineloop): caching should include the params for making caching key.

OWNERS
Resolves #
Remove Animesh as reviewer so PRs won't get assigned to him
**Checklist:**
=> chore(OWNERS): Remove Animesh as reviewer

backend/src/apiserver/common/const.go, backend/src/apiserver/template/tekton_template.go, samples/lightweight-component/calc_pipeline.py, sdk/FEATURES.md
Resolves #940 
Add new annotation flags to enable artifact tracking at pipeline and task level with backward compatibility.
**Checklist:**
=> feat(backend): add new annotation flags to enable artifact tracking at pipeline and task level

.github/workflows/kfp-tekton-unittests.yml
=> chore(CI): Update go version in CI to 1.19.x

.tekton/task.yaml
update pkg, utilities, commands to newer version, including:
- base image ubuntu:20.04
- kubectl 1.25.3
- ibmcloud
- node 18.6
- go v1.19.2
**Checklist:**
=> update toolchain image

sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/nested_loop_with_underscore.py, sdk/python/tests/compiler/testdata/nested_loop_with_underscore.yaml, sdk/python/tests/compiler/testdata/nested_loop_with_underscore_noninlined.yaml
Resolves #1075 
Fix nested loop underscore param as we should use the upstream param name. We should only generate the nested param when it's built by the condition or other custom task.
**Checklist:**
=> fix(sdk): fix nested loop underscore param

sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/tests/compiler/testdata/nested_loop_with_underscore.py, sdk/python/tests/compiler/testdata/nested_loop_with_underscore.yaml, sdk/python/tests/compiler/testdata/nested_loop_with_underscore_noninlined.yaml
Resolves #1075 
I made a mistake by checking the underscore name with the task param name instead of pipelinerun param name. The correct implementation should come from the pipelinerun param name since we are using tekton pipeline param.
**Checklist:**
=> fix(bug): fix underscore param by checking pipeline param instead of task param

.github/workflows/kfp-tekton-unittests.yml, tekton-catalog/pipeline-loops/go.mod, tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
=> chore(PipelineLoop): upgrade to tekton v0.41.0

sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/nested_loop_counter_param.py, sdk/python/tests/compiler/testdata/nested_loop_counter_param.yaml, sdk/python/tests/compiler/testdata/nested_loop_counter_param_noninlined.yaml
=> cheerypick(sdk): Fix counter param cherrypick (#1080)

sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/tests/compiler/testdata/loop_with_numeric.yaml, sdk/python/tests/compiler/testdata/loop_with_numeric_noninlined.yaml
=> chore(cherrypick): fix inline spec for new features

sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested.yaml, sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_loop_counter.yaml, sdk/python/tests/compiler/testdata/nested_loop_counter_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_loop_global_param.yaml, sdk/python/tests/compiler/testdata/nested_loop_global_param_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_loop_param.py, sdk/python/tests/compiler/testdata/nested_loop_param.yaml, sdk/python/tests/compiler/testdata/nested_loop_param_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_loop_same_arg.yaml, sdk/python/tests/compiler/testdata/nested_loop_same_arg_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_loop_with_underscore.yaml, sdk/python/tests/compiler/testdata/nested_loop_with_underscore_noninlined.yaml, sdk/python/tests/compiler/testdata/withitem_multi_nested.yaml, sdk/python/tests/compiler/testdata/withitem_multi_nested_noninlined.yaml
Resolves #1046 
Fix nested param generation issue by only checking nested param logic when generating parent parameters. This new logic should avoid conflicts on https://github.com/kubeflow/kfp-tekton/pull/917 when fixing the nested param issue.
**Checklist:**
=> fix(sdk): fix nested param generation issue

sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested.yaml, sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_loop_counter.yaml, sdk/python/tests/compiler/testdata/nested_loop_counter_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_loop_global_param.yaml, sdk/python/tests/compiler/testdata/nested_loop_global_param_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_loop_param.yaml, sdk/python/tests/compiler/testdata/nested_loop_param_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_loop_same_arg.yaml, sdk/python/tests/compiler/testdata/nested_loop_same_arg_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_loop_with_underscore.yaml, sdk/python/tests/compiler/testdata/nested_loop_with_underscore_noninlined.yaml, sdk/python/tests/compiler/testdata/withitem_multi_nested.yaml, sdk/python/tests/compiler/testdata/withitem_multi_nested_noninlined.yaml
Resolves #1046 #1089 
update logic to fix #1089 with the regex param name instead of the sdk internal param name.
**Checklist:**
=> fix(sdk): fix nested param logic for pl

sdk/python/kfp_tekton/compiler/_tekton_handler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested.yaml, sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_loop_counter_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_loop_global_param.yaml, sdk/python/tests/compiler/testdata/nested_loop_global_param_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_loop_param.py, sdk/python/tests/compiler/testdata/nested_loop_param.yaml, sdk/python/tests/compiler/testdata/nested_loop_param_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_loop_same_arg.yaml, sdk/python/tests/compiler/testdata/nested_loop_same_arg_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_loop_with_underscore.yaml, sdk/python/tests/compiler/testdata/nested_loop_with_underscore_noninlined.yaml, sdk/python/tests/compiler/testdata/withitem_multi_nested.yaml, sdk/python/tests/compiler/testdata/withitem_multi_nested_noninlined.yaml
* fix nested param generation issue
* change logic to only apply to parent counter
Resolves #
**Checklist:**
=> chore(cherrypick): fix nested param generation issue (#1089)

sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/custom_task_dash_args.py, sdk/python/tests/compiler/testdata/custom_task_dash_args.yaml
Resolves #1110 
Update custom task arg parsing for bad dash arguments in custom task.
**Checklist:**
=> fix(sdk): Update custom task arg parsing for dash arguments

backend/src/agent/persistence/client/workflow_client.go, tekton-catalog/pipeline-loops/go.mod, tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go, tekton-catalog/pipeline-loops/test/controller.go
Resolves #1113 
**Checklist:**
=> Feat(pipelineloop): upgrade to tekton version 0.43.2, tekton v1beta1 customRun .

sdk/python/requirements.txt
Resolves #
update sdk requirement.txt to get rid of old vulnerability. 
**Checklist:**
=> chore(sdk): Update sdk requirement packages

backend/src/agent/persistence/client/workflow_client.go, tekton-catalog/pipeline-loops/go.mod, tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go, tekton-catalog/pipeline-loops/test/controller.go
Reverts kubeflow/kfp-tekton#1119 due to some critical rbac/k8s api issues on certain k8s versions.
=> Revert "Feat(pipelineloop): upgrade to tekton version 0.43.2, tekton v1beta1 customRun ."

sdk/python/kfp_tekton/compiler/_op_to_template.py, sdk/python/tests/compiler/testdata/resourceop_basic.yaml, sdk/python/tests/compiler/testdata/volume_op.yaml
Resolves #
add command to resource op spec so that tekton doesn't have to lookup image metadata to inject unwanted env variables.
**Checklist:**
=> fix(sdk): add command to resource op spec

backend/src/agent/persistence/client/workflow_client.go, tekton-catalog/pipeline-loops/go.mod, tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go, tekton-catalog/pipeline-loops/test/controller.go
Add back kubeflow/kfp-tekton#1119 with the new patch that can make the e2e test pass
=> Revert "Revert "Feat(pipelineloop): upgrade to tekton version 0.43.2, tekton v1beta1 customRun .""

tekton-catalog/pipeline-loops/config/500-controller.yaml, tekton-catalog/pipeline-loops/config/500-webhook.yaml, tekton-catalog/pipeline-loops/examples/pipelinespec-with-run-arrary-value.yaml, tekton-catalog/pipeline-loops/examples/pipelinespec-with-run-condition.yaml, tekton-catalog/pipeline-loops/examples/pipelinespec-with-run-dict-value.yaml, tekton-catalog/pipeline-loops/examples/pipelinespec-with-run-iterate-numeric.yaml, tekton-catalog/pipeline-loops/examples/pipelinespec-with-run-string-value.yaml, tekton-catalog/pipeline-loops/examples/simplepipelineloop.yaml, tekton-catalog/pipeline-loops/examples/simplepipelineloop_taskspec.yaml, tekton-catalog/pipeline-loops/go.mod, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Resolves #1124 
**Checklist:**
=> Custom run migration for examples of PipelineLoop custom task.

tekton-catalog/pipeline-loops/config/500-controller.yaml, tekton-catalog/pipeline-loops/config/500-webhook.yaml
Resolves #
Update security context with group id for the testing template or else it would fail on k8s 1.24.
**Checklist:**
=> fix(pipelineloop): Update security context with group id

guides/advanced_user_guide.md, sdk/python/kfp_tekton/compiler/_op_to_template.py, sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/tests/compiler/testdata/tekton_pipeline_conf.py, sdk/python/tests/compiler/testdata/tekton_pipeline_conf.yaml
Resolves #1150 
**Checklist:**
=> feat(sdk): Add task workspace support

.github/workflows/kfp-tekton-unittests.yml
Resolves #
KFP is now testing python 3.10 as well since 3.7 is going to be out of support in June. Hence add the 3.10 test here and move away all the default env to 3.8. We will drop 3.7 tests and support in June when Python community officially dropped it.
**Checklist:**
=> chore(test): add python 3.10 into github actions

manifests/kustomize/base/installs/multi-user/api-service/cluster-role.yaml, manifests/kustomize/base/installs/multi-user/persistence-agent/cluster-role.yaml, manifests/kustomize/base/installs/multi-user/scheduled-workflow/cluster-role.yaml, manifests/kustomize/base/pipeline/ml-pipeline-apiserver-role.yaml, manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-role.yaml, manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
Add the permissions to access customruns for the following roles/clusterroles:
- ml-pipeline
- ml-pipeline-persistenceagent-role
- ml-pipeline-scheduledworkflow-role
**Checklist:**
=> fix(backend): Add the permissions to access customruns

.github/workflows/kfp-tekton-unittests.yml, backend/Dockerfile
Resolves #
Update github action kube test to 1.26 and backend python image to 3.8
**Checklist:**
=> Chore(backend) update kube and python dependency for backend

backend/src/agent/persistence/client/workflow_client.go
When setting embedded-status feature flag to minimal, customrun could have either customRef or customSpec which stores the kind information. The change mproves the logic of handling the customruns' statuses in these cases.
verified on a kind cluster with k8s v1.25
**Checklist:**
=> fix(backend): proper handle customrun status

manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-config.yaml
Resolves #
Since Tekton 0.45 won't have full status anymore, update embedded status to minimal so that our daily e2e test can be tested against the minimal status. 
**Checklist:**
=> chore(manifests): Update embedded status to minimal

sdk/python/tests/verify_result.py
When enabling `embedded-status: minimal`, there is no run/taskrun status under
a pipelinerun's status. However, persistenagent aggregates that information into a run's rundetails.
Change the code to use kfp API to retrieve rundetails instead of kube API. 
Verified this script on a kind cluster
**Checklist:**
=> fix(test): call kfp api instead of kube api

manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml
=> chore(manifests): upgrade mysql image to kfp v2 standards for cves mitigation

sdk/python/kfp_tekton/_client.py
Resolves #
There was a typo bug on using the v1 api package. The `v1_resource_type` should start with a lower case.
**Checklist:**
=> fix(sdk): fix v1 api sdk client package bug

sdk/python/kfp_tekton/_client.py
=> fix(sdk): fix v1 api package typo

guides/advanced_user_guide.md
Related #1183 
Update docs on custom task parameters with the new features #1061 to define custom task parameters in `command` section. 
**Checklist:**
=> chore(docs): Update docs on custom task parameters

sdk/python/kfp_tekton/compiler/_op_to_template.py, sdk/python/kfp_tekton/tekton.py, sdk/python/tests/compiler/testdata/any_sequencer.yaml, sdk/python/tests/compiler/testdata/any_sequencer_looped.yaml, sdk/python/tests/compiler/testdata/any_sequencer_looped_noninlined.yaml, sdk/python/tests/compiler/testdata/finally_context_var.yaml, sdk/python/tests/compiler/testdata/resourceop_basic.yaml, sdk/python/tests/compiler/testdata/volume_op.yaml
Resolves #
Update aipipeline images to quay since we no longer can host docker images for free.
**Checklist:**
=> fix(sdk): Update aipipeline images to quay

.tekton/listener.yaml, .tekton/pipeline.yaml, .tekton/task.yaml, .tekton/tekton-catalog/tasks.yaml, scripts/deploy/iks/deploy-kfp.sh, scripts/deploy/iks/publish-image.sh, scripts/deploy/iks/tekton-catalog/deploy-any-sequencer-e2e.sh
update the toolchain image and update the script to be able to specify the URL of the public container registry
**Checklist:**
=> fix(test): update toolchain image/script

.tekton/task.yaml
fix the typo of one of the params in the deploy task
**Checklist:**
=> fix(test): fix typo in the toolchain task

.tekton/listener.yaml, .tekton/pipeline.yaml, .tekton/task.yaml, .tekton/tekton-catalog/tasks.yaml, scripts/deploy/iks/deploy-kfp.sh, scripts/deploy/iks/publish-image.sh, scripts/deploy/iks/tekton-catalog/deploy-any-sequencer-e2e.sh, sdk/python/kfp_tekton/__init__.py, sdk/python/setup.py
=> chore(sdk): Add sdk 1.5.3 patch

guides/release.md, manifests/kustomize/base/cache-deployer/kustomization.yaml, manifests/kustomize/base/installs/generic/kustomization.yaml, manifests/kustomize/base/installs/multi-user/kustomization.yaml, manifests/kustomize/base/metadata/overlays/db/kustomization.yaml, manifests/kustomize/base/pipeline/kustomization.yaml, manifests/kustomize/env/kfp-template/kustomization.yaml, manifests/kustomize/env/plain-multi-user/kustomization.yaml, manifests/kustomize/env/plain/kustomization.yaml, manifests/kustomize/env/platform-agnostic-emissary/kustomization.yaml, manifests/kustomize/env/platform-agnostic-kind/kustomization.yaml, manifests/kustomize/env/platform-agnostic-kind/plain-kind/kustomization.yaml, manifests/kustomize/env/platform-agnostic-multi-user-emissary/kustomization.yaml, manifests/kustomize/env/platform-agnostic-multi-user/kustomization.yaml, manifests/kustomize/env/platform-agnostic/kustomization.yaml, manifests/kustomize/third-party/kfp-csi-s3/csi-s3-deployment.yaml, manifests/kustomize/third-party/kfp-csi-s3/kustomization.yaml, manifests/kustomize/third-party/kfp-csi-s3/params.yaml, manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml, manifests/kustomize/third-party/tekton/base/kustomization.yaml, manifests/kustomize/third-party/tekton/installs/cluster/kustomization.yaml, manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/kustomization.yaml
remove deprecated fields in manifests, including
- base
- vars
- patchesStrategicMerge
- patchesJson6903
**Checklist:**
=> feat(manifests): use kustomize v5

backend/src/apiserver/client/minio.go, backend/src/apiserver/client_manager.go, backend/src/apiserver/storage/minio_client.go, backend/src/apiserver/storage/minio_client_fake.go, backend/src/apiserver/storage/object_store.go, backend/src/apiserver/storage/object_store_test.go, backend/src/apiserver/template/tekton_template.go, backend/src/apiserver/template/template.go, backend/src/common/client/api_server/run_client.go, backend/src/common/util/template_util.go, backend/test/integration/pipeline_api_test.go, backend/test/integration/pipeline_version_api_test.go, backend/test/integration/upgrade_test.go, backend/third_party_licenses/apiserver.csv, backend/third_party_licenses/cache_server.csv, backend/third_party_licenses/persistence_agent.csv, backend/third_party_licenses/swf.csv, go.mod, go.sum, manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml, tekton-catalog/any-sequencer/go.mod, tekton-catalog/any-sequencer/go.sum, tekton-catalog/pipeline-loops/go.mod
Resolves #
Update Tekton 0.44.2 patch and dependencies update on deprecated go packages based on upstream kfp.
**Checklist:**
=> fix(deps): Tekton 0.44.2 patch and dependencies update

.github/workflows/kfp-tekton-unittests.yml, backend/update_requirements.sh, guides/advanced_user_guide.md, sdk/README.md, sdk/python/README.md, sdk/python/kfp_tekton/__init__.py, sdk/python/setup.py
Resolves #
Python 3.7 will be EOL in June, so we are dropping its support for kfp-tekton 1.7 release and beyond. 
**Checklist:**
=> fix(python): Remove python 3.7 support

backend/src/v2/compiler/tektoncompiler/container.go, backend/src/v2/compiler/tektoncompiler/dag.go, backend/src/v2/compiler/tektoncompiler/tekton.go
Detect if a condition exits in a DAG and provide
the API for downstream tasks to know if they
are guarded by a condition.
**Checklist:**
=> Properly add WhenExpress to handle condition

README.md
=> chore(docs): Remove inactive community links

.tekton/task.yaml, scripts/deploy/iks/build-image-dind.sh, scripts/deploy/iks/build-image.sh, scripts/deploy/iks/deploy-dind.sh, scripts/deploy/iks/deploy-kfp.sh, scripts/deploy/iks/deploy-tekton.sh, scripts/deploy/iks/e2e-test.sh, scripts/deploy/iks/publish-image.sh, scripts/deploy/iks/run-test.sh, scripts/deploy/iks/undeploy-kfp.sh, scripts/deploy/iks/undeploy-tekton.sh
remove depreciated options for ibmcloud CLI which causes the toolchain failure
**Checklist:**
=> fix(test): update ibmcloud command

manifests/kustomize/env/kfp-template-openshift-pipelines/kustomization.yaml
=> fix(manifests): fix unsaved kustomization.yaml for openshift pipelines

manifests/kustomize/base/pipeline/cluster-scoped/scheduled-workflow-crd.yaml, manifests/kustomize/base/pipeline/cluster-scoped/viewer-crd.yaml, manifests/kustomize/env/platform-agnostic/kustomization.yaml, manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml, manifests/kustomize/third-party/openshift-pipelines-custom-task/kustomization.yaml, manifests/kustomize/third-party/openshift/standalone/anyuid-scc.yaml, manifests/kustomize/third-party/openshift/standalone/kustomization.yaml, manifests/kustomize/third-party/openshift/standalone/privileged-scc.yaml, manifests/kustomize/third-party/tekton-custom-task/configmap.yaml, manifests/kustomize/third-party/tekton-custom-task/driver-controller/201-role.yaml, manifests/kustomize/third-party/tekton-custom-task/driver-controller/500-controller.yaml, manifests/kustomize/third-party/tekton-custom-task/exit-handler/201-clusterrole.yaml, manifests/kustomize/third-party/tekton-custom-task/exit-handler/201-role.yaml, manifests/kustomize/third-party/tekton-custom-task/exit-handler/300-exithandler-crd.yaml, manifests/kustomize/third-party/tekton-custom-task/exit-handler/500-controller.yaml, manifests/kustomize/third-party/tekton-custom-task/exit-handler/500-webhook.yaml, manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml, manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/201-clusterrole.yaml, manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/201-role.yaml, manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/300-pipelineloop.yaml, manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-controller.yaml, manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-webhook.yaml
Add manifests for `openshift-pipelines` which deploys kfp-tekton v2 to a openshift cluster with openshift-pipelines 1.0
**Checklist:**
=> v2: add manifests for `openshift-pipelines`

manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml, manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml, manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
build and update images to the latest
commit.
**Checklist:**
=> v2: update images

guides/kfp_tekton_install.md, manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-config.yaml
=> feat(manifests): opt-out sidecar injection feature flag to increase performance

sdk/python/README.md, sdk/python/requirements.in, sdk/python/requirements.txt, sdk/python/setup.py, sdk/python/tests/test_kfp_samples.sh
=> fix(sdk): Update kfp version to fix appengine bug

sdk/python/kfp_tekton/_client.py
Resolves #1223 
**Checklist:**
=> fix(sdk): Update wait_for_run_completion function to handle tekton status;

backend/src/v2/compiler/tektoncompiler/container.go, backend/src/v2/compiler/tektoncompiler/dag.go, manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml, manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml, manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
remove the `name: kfp-driver` under `CustomRef` to avoid custom task lookup.
**Checklist:**
=> v2: fix kfp driver

backend/src/apiserver/template/v2_template.go, backend/src/v2/compiler/tektoncompiler/container.go, backend/src/v2/compiler/tektoncompiler/tekton.go, backend/src/v2/compiler/tektoncompiler/tekton_test.go, backend/src/v2/controller/run.go, samples/v2/pipeline_with_secret_as_env.py, samples/v2/pipeline_with_secret_as_volume.py
platform spec is used to pass kubernetes specification, ie. env, volume, volume mount, and etc.
support this feature in tekton compiler and kfp-driver.
**Checklist:**
=> v2: support platform spec

backend/src/agent/persistence/client/workflow_client.go, backend/src/agent/persistence/persistence_agent.go
Resolves #1226
use SharedInformer to optimize the query of childreference, including:
- TaskRun
- CustomRun
**Checklist:**
=> feat(backend): Use Informer in persistence agent

.tekton/task.yaml
use new docker image for CI build
**Checklist:**
=> fix(test): update docker image for dind

samples/lightweight-component/calc_pipeline.py, samples/lightweight-component/lightweight_component.ipynb
use `create_component_from_func` instead
**Checklist:**
=> samples(fix): update lightweight component sample

backend/src/v2/compiler/tektoncompiler/dag.go, backend/src/v2/compiler/tektoncompiler/testdata/nestedloop_ir.yaml
pass down iteratorPolicy.parallelismLimit to
PipelineLoop
**Checklist:**
=> feat(v2 backend): support loop parallelism

manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml, manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml
update apiserver image
**Checklist:**
=> v2: update apiserver image

frontend/src/components/viewers/Tensorboard.tsx
=> fix(fronted): Fix Tensorboard.tsx endpoint

guides/advanced_user_guide.md, sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/kfp_tekton/compiler/pipeline_utils.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/condition.yaml, sdk/python/tests/compiler/testdata/condition_depend.yaml, sdk/python/tests/compiler/testdata/conditions_and_loops.yaml, sdk/python/tests/compiler/testdata/conditions_and_loops_noninlined.yaml, sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml, sdk/python/tests/compiler/testdata/loop_in_recursion.yaml, sdk/python/tests/compiler/testdata/loop_in_recursion_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_recur_runafter.yaml, sdk/python/tests/compiler/testdata/nested_recur_runafter_noninlined.yaml, sdk/python/tests/compiler/testdata/recur_nested.yaml, sdk/python/tests/compiler/testdata/recur_nested_noninlined.yaml, sdk/python/tests/compiler/testdata/recursion_while.yaml, sdk/python/tests/compiler/testdata/recursion_while_noninlined.yaml
Resolves #1264 
**Checklist:**
=> feat(sdk): Parametrize Tekton condition "task" image name

sdk/python/README.md, sdk/python/kfp_tekton/__init__.py, sdk/python/setup.py
=> chore(sdk): Add sdk 1.7.1 release

backend/src/v2/compiler/tektoncompiler/container.go, backend/src/v2/compiler/tektoncompiler/dag.go, backend/src/v2/compiler/tektoncompiler/tekton.go, backend/src/v2/compiler/tektoncompiler/testdata/exit_handler.yaml, backend/src/v2/compiler/tektoncompiler/testdata/mnist_pipeline.yaml, manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml, manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml
Resolves #1266
The compiler passes down the MLMD host/port from the apiserver to DAG/Container drivers. In the apiserver, this information is from env vars which are generated by k8s.
Also, update the apiserver image.
**Checklist:**
=> fix(v2 backend): progagate MLMD host/port to the driver

backend/src/v2/compiler/tektoncompiler/tekton_test.go, backend/src/v2/compiler/tektoncompiler/testdata/loop_static.yaml, backend/src/v2/compiler/tektoncompiler/testdata/nestedloop.yaml
add test case for tekton compiler
**Checklist:**
=> test(v2): add test case for tekton compiler

backend/src/apiserver/client/argo_fake.go, backend/src/common/util/execution_spec_test.go, backend/src/v2/compiler/tektoncompiler/tekton_test.go, backend/src/v2/compiler/tektoncompiler/testdata/hello_world.yaml, backend/src/v2/compiler/tektoncompiler/testdata/importer.yaml, backend/src/v2/component/launcher_v2_test.go, backend/src/v2/expression/expression_test.go, backend/src/v2/objectstore/object_store.go
Make tektoncompiler_test more stable. also fixed
some failed test cases
**Checklist:**
=> test(v2): fix failed test cases

.github/workflows/backend.yml, .github/workflows/codeql.yml, .github/workflows/pipelineloop.yml, tekton-catalog/pipeline-loops/test/controller.go
only add go unit tests for now. add end-2-end test later.
**Checklist:**
=> test(v2): enable ghaction for v2 branch

manifests/kustomize/base/pipeline/kustomization.yaml
for v2 in kfp-tekton, no v1 support is needed.
remove metadata-writer.
**Checklist:**
=> v2: remote metadata-writer

guides/kfp_tekton_install.md
=> chore(docs): Update kfp-tekton openshift instructions for openshift v1.11

.github/workflows/backend.yml, scripts/deploy/github/build-images.sh, scripts/deploy/github/deploy-kfp.sh, scripts/deploy/github/e2e-test.sh, scripts/deploy/github/helper-functions.sh, scripts/deploy/github/manifests/kustomization.yaml, scripts/deploy/github/test-flip-coin.sh
Add a GitHub action for end-2-end test:
- compile flip coin Python script
- submit IR to api server
- create a run
- verify the run result
**Checklist:**
=> test(v2): add end-2-end test

backend/third_party_licenses/apiserver.csv, backend/third_party_licenses/cache_server.csv, backend/third_party_licenses/persistence_agent.csv, backend/third_party_licenses/swf.csv, backend/third_party_licenses/tekton-driver.csv, backend/third_party_licenses/tekton-exithandler-controller.csv, backend/third_party_licenses/tekton-exithandler-webhook.csv, backend/third_party_licenses/tekton-kfptask-controller.csv, backend/third_party_licenses/tekton-kfptask-webhook.csv, go.mod, go.sum, manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml, manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml, manifests/kustomize/third-party/tekton-custom-task/configmap.yaml, manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml, manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
Update the tekton version to 0.47.3
**Checklist:**
=> feat(v2:backend): update tekton version

.github/workflows/backend.yml, scripts/deploy/github/e2e-test.sh, scripts/deploy/github/test-pipeline.sh, scripts/deploy/github/test-static-loop.sh
Add static loop test case into the GitHub action.
**Checklist:**
=> test(v2): add end-2-end test case

backend/src/v2/compiler/tektoncompiler/importer.go, backend/src/v2/compiler/tektoncompiler/testdata/importer.yaml
the input value of `importer_spec` is incorrect. It was component spec. Changed it to importer spec.
**Checklist:**
=> fix(v2:backend): fix importer

manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml, manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml
built and published new image for api-server
**Checklist:**
=> feat(v2:backend): update api-server image

.github/workflows/backend.yml, scripts/deploy/github/test-dynamic-loop.sh
Add the dynamic loop test case to the GitHub action.
The loop data is generated from the previous task.
It's an existing test case. Just add it into
the GitHub action.
**Checklist:**
=> test(v2): add dynamic loop test case

.github/workflows/backend.yml, scripts/deploy/github/build-images.sh, scripts/deploy/github/e2e-test.sh, scripts/deploy/github/helper-functions.sh, scripts/deploy/github/test-pipeline.sh, scripts/deploy/github/test-secret-as-env.sh, scripts/deploy/github/test-secret-as-volume.sh
Add a test case for verifying the scenario of
using a secret as an env var.
**Checklist:**
=> test(v2): use secret as env

.github/workflows/backend.yml, scripts/deploy/github/test-secret-as-volume.sh
Add a test case to use a secret as a volume.
**Checklist:**
=> test(v2): secret as volume

samples/README.md, samples/huggingface-prompt-tuning/README.md, samples/peft-modelmesh-pipeline/README.md
Resolves #
Add readme for prompt tuning samples since the IBM Developer blogs are all published now.
**Checklist:**
=> chore(samples): Add readme for prompt tuning samples

README.md
=> chore(readme): Add kfp-tekton v2 branch link

.github/workflows/backend.yml, scripts/deploy/github/test-env.sh
Adding the env test case into GitHub action
**Checklist:**
=> test(v2): add env test case

.github/workflows/backend.yml, manifests/kustomize/third-party/tekton-custom-task/driver-controller/201-clusterrole.yaml, scripts/deploy/github/test-volume.sh
Adding the volume test case to the GitHub action
**Checklist:**
=> test(v2): use volume

manifests/kustomize/base/installs/multi-user/api-service/cluster-role.yaml, manifests/kustomize/base/installs/multi-user/kustomization.yaml, manifests/kustomize/base/installs/multi-user/persistence-agent/cluster-role.yaml, manifests/kustomize/base/installs/multi-user/scheduled-workflow/cluster-role.yaml, manifests/kustomize/env/platform-agnostic-tekton-multi-user/kustomization.yaml, manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml, manifests/kustomize/third-party/kfp-csi-s3/csi-s3-deployment.yaml, manifests/kustomize/third-party/kfp-csi-s3/csi-s3-secret.yaml, manifests/kustomize/third-party/kfp-csi-s3/kustomization.yaml, manifests/kustomize/third-party/kfp-csi-s3/params.yaml
Add multi-user manifests and remove cache and metadata-writer.
**Checklist:**
=> v2: add multi-user manifests

backend/src/apiserver/resource/resource_manager.go, backend/src/apiserver/template/template_test.go, backend/src/apiserver/template/v2_template.go, backend/src/crd/controller/scheduledworkflow/controller.go, backend/src/crd/controller/scheduledworkflow/main.go, backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/types.go, scripts/deploy/github/manifests/kustomization.yaml
Change the behavior of the run creation in scheduledworkflow: submit the run creation request to apiserver.
**Checklist:**
=> v2(backend): fix scheduledworkflow

guides/advanced_user_guide.md, sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/kfp_tekton/compiler/pipeline_utils.py, sdk/python/setup.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/condition.yaml, sdk/python/tests/compiler/testdata/condition_depend.yaml, sdk/python/tests/compiler/testdata/conditions_and_loops.yaml, sdk/python/tests/compiler/testdata/conditions_and_loops_noninlined.yaml, sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml, sdk/python/tests/compiler/testdata/loop_in_recursion.yaml, sdk/python/tests/compiler/testdata/loop_in_recursion_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_recur_runafter.yaml, sdk/python/tests/compiler/testdata/nested_recur_runafter_noninlined.yaml, sdk/python/tests/compiler/testdata/recur_nested.yaml, sdk/python/tests/compiler/testdata/recur_nested_noninlined.yaml, sdk/python/tests/compiler/testdata/recursion_while.yaml, sdk/python/tests/compiler/testdata/recursion_while_noninlined.yaml
=> cherrypick task image into 1.5.x branch

guides/advanced_user_guide.md, sdk/python/kfp_tekton/__init__.py, sdk/python/kfp_tekton/compiler/compiler.py, sdk/python/kfp_tekton/compiler/pipeline_utils.py, sdk/python/setup.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/condition.yaml, sdk/python/tests/compiler/testdata/condition_depend.yaml, sdk/python/tests/compiler/testdata/conditions_and_loops.yaml, sdk/python/tests/compiler/testdata/conditions_and_loops_noninlined.yaml, sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml, sdk/python/tests/compiler/testdata/loop_in_recursion.yaml, sdk/python/tests/compiler/testdata/loop_in_recursion_noninlined.yaml, sdk/python/tests/compiler/testdata/nested_recur_runafter.yaml, sdk/python/tests/compiler/testdata/nested_recur_runafter_noninlined.yaml, sdk/python/tests/compiler/testdata/recur_nested.yaml, sdk/python/tests/compiler/testdata/recur_nested_noninlined.yaml, sdk/python/tests/compiler/testdata/recursion_while.yaml, sdk/python/tests/compiler/testdata/recursion_while_noninlined.yaml
=> add sdk 1.5.5

OWNERS, backend/OWNERS, manifests/kustomize/OWNERS
**Description of your changes:** 
The OWNERS files in the v2 branch come from upstream.
Update some of the OWNERS to reflect the ownership in kfp-tekton repo.
**Checklist:**
=> update OWNERS files

backend/src/agent/persistence/client/workflow_client.go, backend/src/common/util/workflow.go
Resolves #
Update backend to be backward compatible with old status so that the v1 UI doesn't need to change its current logic to render the graph.
**Checklist:**
=> feature(backend): update backend to be backward compatible with old status

sdk/python/kfp_tekton/_client.py
Related #1316 
Support Tekton specific config class in sdk client function as well. Will patch this into older kfp sdk version once merged.
**Checklist:**
=> feat(sdk): add tekton pipeline config into sdk client function

.readthedocs.yml
Resolves #
Update read the docs yaml due to recent deprecation
https://blog.readthedocs.com/use-build-os-config/
**Checklist:**
=> chore(build): Update .readthedocs.yml to build.os format to avoid warning.

.tekton/listener.yaml, .tekton/pipeline.yaml, .tekton/task.yaml, README.md, scripts/deploy/iks/test-many-edges.sh, tekton-catalog/pipeline-loops/examples/break-task-example.yaml, tekton-catalog/pipeline-loops/examples/loop-example-basic-retry.yaml, tekton-catalog/pipeline-loops/examples/loop-example-basic.yaml, tekton-catalog/pipeline-loops/examples/loop-example-basic_taskspec.yaml, tekton-catalog/pipeline-loops/examples/loop-example-numeric-param.yaml, tekton-catalog/pipeline-loops/examples/loop-example-with-parallelism.yaml, tekton-catalog/pipeline-loops/examples/loop-example-workspaces.yaml, tekton-catalog/pipeline-loops/examples/pipelinespec-with-nested-loop-embedded.yaml, tekton-catalog/pipeline-loops/examples/pipelinespec-with-nested-loop.yaml, tekton-catalog/pipeline-loops/examples/simplepipelineloop.yaml, tekton-catalog/pipeline-loops/examples/simplepipelineloop_taskspec.yaml
Resolves #
update ci script to parameterize the many edge example.
**Checklist:**
=> chore(test): update ci script

guides/kfp_tekton_install.md
=> chore(docs): Add grpc gateway version to user guides.

README.md
Add an extra section at the top of the README to
introduce kfp-tekton v2 and its installation instructions.
**Checklist:**
=> v2(doc): Add installation instructions

guides/kfp_tekton_install.md
=> fix(docs) Update Kind install command to use kubectl -k

manifests/kustomize/env/plain-multi-user/kustomization.yaml, manifests/kustomize/env/plain/kustomization.yaml, manifests/kustomize/env/platform-agnostic-tekton-multi-user/kustomization.yaml, manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
=> fix(manifest): update manifests for proper third party app role

manifests/kustomize/env/plain-multi-user/kustomization.yaml, manifests/kustomize/env/plain/kustomization.yaml, manifests/kustomize/env/platform-agnostic-tekton-multi-user/kustomization.yaml, manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
=> (cherrypick): fix(manifest): update manifests for proper third party app role (#1352)

manifests/kustomize/env/platform-agnostic-tekton-multi-user/kustomization.yaml, manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml, manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml, manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
After syncing up with kubeflow/pipelines release-2.0.1, build new images and update manifests to use them.
**Checklist:**
=> v2(images): update image tag to 2.0.1

manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml
=> Update openshift manifests for kfp-tekton v2

manifests/kustomize/v1/base/installs/multi-user/istio-authorization-config.yaml
=> fix(manifests): Update istio-authorization-config.yaml

manifests/kustomize/base/installs/multi-user/istio-authorization-config.yaml
=> fix(manifests): Update istio-authorization-config.yaml for multi-user

guides/kfp_tekton_install.md
=> chore(docs): Update kfp_tekton_install.md with kfp-tekton v2 install instructions

SECURITY.md
=> chore(docs): Add SECURITY.md to tell supporting kfp-tekton version

.github/workflows/kfp-tekton-unittests.yml
Resolves #
Update github action deps to reduce random ci errors.
**Checklist:**
=> chore(github): Update github action deps

backend/third_party_licenses/apiserver.csv, backend/third_party_licenses/cache_server.csv, backend/third_party_licenses/persistence_agent.csv, backend/third_party_licenses/swf.csv, go.mod, go.sum, manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml, tekton-catalog/pipeline-loops/go.mod, tekton-catalog/tekton-exithandler/go.mod, tekton-catalog/tekton-exithandler/go.sum, tekton-catalog/tekton-kfptask/go.mod, tekton-catalog/tekton-kfptask/go.sum
Resolves #
Update to Tekton 0.50.2 to address the regression and security fix we found in the last tekton release.
**Checklist:**
=> fix(deps): Update to Tekton 0.50.2 to fix regression and security bugs

.tekton/pipeline.yaml, guides/release.md, scripts/deploy/iks/publish-image.sh
=> chore(docs): update manual release process and minor ci display name change

README.md
=> chore(docs): Update main readme entrypoint

backend/third_party_licenses/apiserver.csv, backend/third_party_licenses/cache_server.csv, backend/third_party_licenses/persistence_agent.csv, backend/third_party_licenses/swf.csv, go.mod, go.sum, tekton-catalog/tekton-driver/go.mod, tekton-catalog/tekton-driver/go.sum, tekton-catalog/tekton-exithandler/go.mod, tekton-catalog/tekton-exithandler/go.sum, tekton-catalog/tekton-kfptask/go.mod, tekton-catalog/tekton-kfptask/go.sum
=> chore(deps): update golang grpc deps to 1.56.3

guides/kfp_tekton_install.md
=> chore(docs): Update kfp-tekton v2 version in the docs

.tekton/pipeline.yaml, Makefile
=> chore(ci): remove driver build code since it is no longer necessary

sdk/python/kfp_tekton/_client.py
Resolves #1427 
**Checklist:**
=> fix(sdk): Fix datetime import

README.md
=> chore(README.md): Update kfp upstream version for v2 branch

tekton-catalog/pipeline-loops/Dockerfile, tekton-catalog/pipeline-loops/Makefile, tekton-catalog/pipeline-loops/config/201-clusterrole.yaml, tekton-catalog/pipeline-loops/go.mod, tekton-catalog/pipeline-loops/pkg/controller/klog.patch, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go, tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go, tekton-catalog/tekton-kfptask/pkg/reconciler/kfptask/reconciler.go
=> feat(pipeline-loop v2): Merge loop driver and publisher into the pipelineloop controller logic

backend/src/v2/compiler/tektoncompiler/container.go, backend/src/v2/compiler/tektoncompiler/dag.go, backend/src/v2/compiler/tektoncompiler/tekton.go, backend/src/v2/compiler/tektoncompiler/tekton_test.go, backend/src/v2/compiler/tektoncompiler/testdata/loop_static.yaml, backend/src/v2/compiler/tektoncompiler/testdata/nestedloop.yaml, manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/201-clusterrole.yaml, manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-controller.yaml
=> feat(v2 backend): Reduce Tekton loop graph complexity with new design

manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
=> chore(v2 manifests): Update v2 staging image

tekton-catalog/tekton-kfptask/go.mod, tekton-catalog/tekton-kfptask/go.sum, tekton-catalog/tekton-kfptask/pkg/common/common_test.go
=> feat(tekton-catalog): Add basic test to kfptask

sdk/python/kfp_tekton/__init__.py, sdk/python/setup.py
=> chore(release): Add sdk 1.9.2 release

tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Resolves #1357 
Make pipelineloop rely on Lister more often to improve the controller scalability. 
**Checklist:**
=> feat(pipelineloop): Optimize pipelineloop get performance with Lister

backend/src/apiserver/template/tekton_template.go, backend/src/apiserver/template/tekton_template_test.go
Resolves #
generate basic golang tests using vscode plugins.
**Checklist:**
=> chore(tests): add unit tests for tekton template v1

README.md
Resolves #
Remove deprecated MLX wording as we proposing a new model/asset registry project
**Checklist:**
=> chore(README): Remove deprecated MLX wording

tekton-catalog/tekton-kfptask/go.mod, tekton-catalog/tekton-kfptask/go.sum, tekton-catalog/tekton-kfptask/pkg/common/common.go, tekton-catalog/tekton-kfptask/pkg/reconciler/kfptask/reconciler.go
=> feat(tekton-kfptask): Update kfptask to support pod metadata

.github/workflows/kfp-tekton-unittests.yml, sdk/README.md, sdk/python/setup.py
=> feat(ci): Update github actions to also test python 3.12

backend/Dockerfile, backend/Dockerfile.cacheserver, backend/Dockerfile.conformance, backend/Dockerfile.driver, backend/Dockerfile.launcher, backend/Dockerfile.persistenceagent, backend/Dockerfile.scheduledworkflow, backend/Dockerfile.viewercontroller, go.mod, go.sum
=> feat(backend): Upgrade KFP V2 to go 1.21

sdk/python/kfp_tekton/_client.py
Resolves #
Back patch kfp v2 feature for v1 users.
add verify_ssl flag to support self cert
**Checklist:**
=> feat(sdk): add verify_ssl flag to support self cert

sdk/python/kfp_tekton/__init__.py, sdk/python/setup.py
=> chore(sdk): Add sdk 1.9.3 release

.tekton/task.yaml
=> chore(ci): Add clean up step for tekton ci

OWNERS
=> chore(owners): Promote rafalbigaj as the approver
