kubeflow/kfp-tekton

- sdk/README.md
- sdk/python/kfp_tekton/compiler/__init__.py
- sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/sequential.py
- sdk/python/tests/compiler/testdata/sequential.yaml
- sdk/samples/sequential/sequential.py
Replace `steps` with `tasks` to allow _parallel_ task execution.
Use `runAfter` to support _sequential_ task execution.
The compile now generates multiple documents in one YAML file, one per `Task` and one for the `Pipeline`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfp-tekton/17)
> Generate Tekton Pipeline with Tasks

- sdk/README.md
- sdk/python/kfp_tekton/__init__.py
- sdk/python/kfp_tekton/compiler/__init__.py
- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/parallel_join.py
- sdk/python/tests/compiler/testdata/parallel_join.yaml
- sdk/python/tests/compiler/testdata/sequential.py
- sdk/python/tests/compiler/testdata/sequential.yaml
- sdk/samples/parallel_join.py
- sdk/samples/sequential.py
This PR adds the capability to compile the `file_outputs` of `dsl.ContainerOp`s into Tekton `Task` `results` which can then be used as input parameters in subsequent pipeline tasks.
The Tekton API version is now at `v1beta1`.
`sdk/samples/parallel_join.py`:
```Python
def gcs_download_op(url):
return dsl.ContainerOp(
name='GCS - Download',
image='google/cloud-sdk:279.0.0',
command=['sh', '-c'],
arguments=['gsutil cat $0 | tee $1', url, '/tmp/results.txt'],
file_outputs={
'data': '/tmp/results.txt',  # <--- output file
}
)
def echo2_op(text1, text2):
return dsl.ContainerOp(
name='echo',
image='library/bash:4.4.23',
command=['sh', '-c'],
arguments=['echo "Text 1: $0"; echo "Text 2: $1"', text1, text2]
)
@dsl.Pipeline(name='Parallel pipeline',
description='parallel join.')
def …
```
> Task output parameters as input for subsequent tasks

- .gitignore
- samples/kfp-tfx/tfx-taxi-on-prem/pvc/filebrowser.yaml
Change deployment by using apps/v1 instead of extensions/v1beta1, as mentioned here : https://github.com/kubernetes/kubernetes/issues/61430
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfp-tekton/43)
> Use apps/v1 instead of extensions/v1beta1

- samples/kfp-tekton/flip-coin/README.md
When run the [flip-coin example ](https://github.com/kubeflow/kfp-tekton/tree/master/samples/kfp-tekton/flip-coin) on openshift using openshift pipeline, it needs to setup the storage in the [flip-coin-tekton-resources.yaml](https://github.com/kubeflow/kfp-tekton/blob/master/samples/kfp-tekton/flip-coin/tekton/flip-coin-tekton-resources.yaml) before running this step:
```
kubectl apply -f samples/kfp-tekton/flip-coin/tekton/flip-coin-tekton-resources.yaml
```
So I add the information in the readme to clarify.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfp-tekton/47)
> add instructions to install tekton pipeline and storage

- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/init_container.py
- sdk/python/tests/compiler/testdata/init_container.yaml
Adding init_container as initial steps since the execution order is the same. 
Since init_container is not a valid field in Tekton task, I prepend all the init_containers to run them before the main step. Also moving the initContainers before inputs/outputs processing in order to process params for all steps.
> Add init_container support

- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/pipelineparams.py
- sdk/python/tests/compiler/testdata/pipelineparams.yaml
- sdk/python/tests/test_kfp_samples_report.txt
Since we fixed the issue of multi params in one pipeline task (PR #40), and support sidecars (PR #42),  we can run pipelineparams sucessfully now. Let me add pipelineparams to our testdata and integrate test incidentally.
Record my test result here as well.
```
Name:           pipelineparams-run-v8cb5
Namespace:      default
Pipeline Ref:   pipelineparams
🌡️  Status
STARTED        DURATION   STATUS
1 minute ago   1 minute   Succeeded
📦 Resources
No resources
⚓ Params
NAME         VALUE
∙ tag        latest
∙ sleep_ms   10
🗂  Taskruns
NAME                                        TASK NAME   STARTED        DURATION     STATUS
∙ pipelineparams-run-v8cb5-echo-2vxfx       echo        1 minute ago   29 seconds   Succeeded
∙ pipelineparams-run-v8cb5-download-5q9td   download    1 minute ago   47 …
```
> Add pipelineparams which contains multi params and sidecars support

- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/timeout.py
- sdk/python/tests/compiler/testdata/timeout.yaml
Add suuport for timeout. 
Tekton pipeline already supported timeout property, doc refer to [here](https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md) (pipeline), and [here](https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md) (pipelinerun).
But there are some differences with argo. In tekton, the Timeout property of a Pipeline Task allows a timeout to be defined for a TaskRun. and whole pipeline timeout need to be defined in pipelinerun. So:
1. timeout for task: implemented in this PR.
2. timeout for whole pipeline:  run `tkn p start pipeline-includes-two-steps-which-fail-randomly --showlog --timeout 180s`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Extend compiler to support timeout defining for pipeline tasks

- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/retry.py
- sdk/python/tests/compiler/testdata/retry.yaml
Sometimes you need a policy for retrying tasks which have problems such as network errors, missing dependencies or upload problems. Any of those issues must be reflected as False (corev1.ConditionFalse) within the TaskRun Status Succeeded Condition. For that reason there is an optional attribute called retries which declares how many times that task should be retried in case of failure.
UT PASS:
```
Name:           retry-random-failures-run-s9zdc
Namespace:      default
Pipeline Ref:   retry-random-failures
🌡️  Status
STARTED         DURATION     STATUS
2 minutes ago   35 seconds   Succeeded
📦 Resources
No resources
⚓ Params
No params
🗂  Taskruns
NAME                                                       TASK NAME          STARTED         DURATION     STATUS
∙ …
```
> Extend compiler to support retries for tasks

- .travis.yml
- sdk/python/tests/test_kfp_samples.sh
- sdk/python/tests/test_kfp_samples_report.txt
This PR adds two additional jobs to the Travis CI script:
- ensure that no fewer KFP DSL scripts pass the compilation than before
- ensure Python scripts formatting passes the lint check (though very relaxed)
I also added job names to make it easier to distinguish the Travis jobs.
We have a total of 4 Travis CI build jobs now:
.
Job | Python | ENV | OS | State
-- | -- | -- | -- | --
Unit tests, Python 3.6 | 3.6 | TOXENV=py36 | Linux | passed
Unit tests, Python 3.7 | 3.7 | TOXENV=py37 | Linux | passed
Progress report on compiling KFP DSL test scripts | 3.7 |   | Linux | passed
Lint Python code with flake8 | 3.7 |   | Linux | passed
> Add compiler progress report to Travis

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/timeout.py
- sdk/python/tests/compiler/testdata/timeout_pipelinerun.yaml
Specifies timeout after which the PipelineRun will fail. If the value of timeout is empty, the default timeout will be applied. If the value is set to 0, there is no timeout.
as below, it's the result of:  task-1 was set timout as 20s, pipelinerun timeout was set as 40s.
```
Name:           pipeline-includes-two-steps-which-fail-randomly-run
Namespace:      default
Pipeline Ref:   pipeline-includes-two-steps-which-fail-randomly
🌡️  Status
STARTED          DURATION     STATUS
42 seconds ago   40 seconds   Failed
💌 Message
TaskRun pipeline-includes-two-steps-which-fail-randomly-run-rando-8r5ck has failed (TaskRun &#34;pipeline-includes-two-steps-which-fail-randomly-run-rando-8r5ck&#34; failed to finish within &#34;20s&#34;)
📦 Resources
No resources
⚓ Params
No params
🗂  Taskruns
NAME …
```
> Extend compiler to support workflow level timeout

- sdk/python/kfp_tekton/compiler/compiler.py
Resolves #
There was a bug on pipelinerun when the default parameter is not define. Fixing it with an empty default value.
* Tekton Version (use `tkn version`): 0.11
> Fix no default param bug on pipelinerun

- sdk/python/tests/README.md
- sdk/python/tests/test_kfp_samples.sh
- sdk/python/tests/test_kfp_samples_report.txt
Change the `test_kfp_samples.sh` script such that if returns exit code `1` if the the KFP testdata compilation report changes.
Previously it only checked if the number of `SUCCESS`ful compilations declined from the previous report. This behavior resulted in an outdated compilation report after several PRs missed to update the report.
> Have Travis/CI enforce that the compilation report is updated

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/katib.py
- sdk/python/tests/compiler/testdata/katib.yaml
Resolves #
The current regular expression for finding {{variable}} has some conflicts with Katib specific variables as well. Therefore, we need to update the regular expression to only map {{variable.(variable)+}} for Argo specific variables
* Tekton Version (use `tkn version`): 0.11
> Fix regular expression parsing to only fail on argo specific variables

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/imagepullsecrets.py
- sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
Related #54 
We need image pull secret so that we can pull images from private repo. kfp-tekton compiler will generated Tekton pipeline based on the kubeflow pipeline DSL, if the DSL contains image secret, the compiler will generate a service account, and store the secret under the service account. A better approach will be adding the image pull secret into a podtemplate, but currently Tekton doesn't have this support. We opened an issue [2339](https://github.com/tektoncd/pipeline/issues/2339) there.
Python 3.7.4
Client version: 0.8.0
Pipeline version: v0.11.0-rc2
* Kubernetes Version (use `kubectl …
> Add support for pulling the image secret

- sdk/README.md
- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/resourceop_basic.py
- sdk/python/tests/compiler/testdata/resourceop_basic.yaml
- sdk/python/tests/test_kfp_samples_report.txt
Resolves #49 
Based on [kubectl-wrapper](https://github.com/vincent-pli/kubectl-wrapper), we have following parameters in Tekton task right now, which are used for supporting Tekton resourceOps:
- **action**:  -- the action to perform to the resource
- **merge_strategy**:  -- the strategy used to merge a patch, defaults to "strategic"
- **success_condition**: a label selector expression which describes the success condition
- **failure_condition**: a label selector expression which describes the failure condition
- **manifest**: the kubernetes manifest
- **output**: An express to retrieval data from resource, all the `output`  will be writen to `tekton/result/output` file.
- **set-ownerreference**: Enable …
> Add support for dsl.ResourceOp

- sdk/README.md
- sdk/sa-and-rbac.md
Resolves #90 
Add readme about using serviceaccount and rbac for tekton pipeline
Openshift 4.3.1
Python 3.7.4
Client version: 0.8.0
Pipeline version: v0.11.0-rc2
Client Version: v4.3.1
Kubernetes Version: v1.16.2
OS (e.g. from /etc/os-release):
macOS Mojave 10.14.6
> Add README of ServiceAccount and RBAC

- sdk/python/tests/README.md
- sdk/python/tests/test_kfp_samples.sh
Fix bug in previous report where Python module `test_util` could not be run from outside the `sdk/python/tests` folder resulting in missing compile status of:
- `basic_no_decorator.py` 
- `compose.py`
```YAML
Success: 25
Failure: 5
Total:   30
```
Overall success rate: 83 %
> Update compiler report card

- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/affinity.yaml
- sdk/python/tests/compiler/testdata/artifact_location.yaml
- sdk/python/tests/compiler/testdata/condition.yaml
- sdk/python/tests/compiler/testdata/hidden_output_file.yaml
- sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
- sdk/python/tests/compiler/testdata/init_container.yaml
- sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
- sdk/python/tests/compiler/testdata/katib.yaml
- sdk/python/tests/compiler/testdata/loop_static.yaml
- sdk/python/tests/compiler/testdata/node_selector.yaml
- sdk/python/tests/compiler/testdata/parallel_join.yaml
- sdk/python/tests/compiler/testdata/parallel_join_pipelinerun.yaml
- sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
- sdk/python/tests/compiler/testdata/pipeline_transformers.yaml
- sdk/python/tests/compiler/testdata/pipelineparams.yaml
- sdk/python/tests/compiler/testdata/resourceop_basic.yaml
- sdk/python/tests/compiler/testdata/retry.yaml
- sdk/python/tests/compiler/testdata/sequential.yaml
- sdk/python/tests/compiler/testdata/sidecar.yaml
- sdk/python/tests/compiler/testdata/timeout.yaml
- sdk/python/tests/compiler/testdata/timeout_pipelinerun.yaml
- sdk/python/tests/compiler/testdata/tolerations.yaml
- sdk/python/tests/compiler/testdata/volume.yaml
- sdk/python/tests/compiler/testdata/volume_op.yaml
- sdk/python/tests/compiler/testdata/volume_snapshot_op.yaml
- sdk/python/tests/compiler/testdata/withitem_nested.yaml
Resolves #114 
- Add new annotation to disable istio-inject
- Remove literal string conversion for pyyaml since there could be conflicts with yaml 1.1 and 1.2 on some [edge cases](https://github.com/yaml/pyyaml/issues/98). If we want this feature back then we have to use ruamel.yaml. We are using pyyaml right now because we need to be consistent with the kfp package. 
- Add headers to golden test yaml
- Fix minor syntax bugs
* Tekton Version (use `tkn version`): 0.11.3
> Fix edge cases such as disable istio-inject for Tekton compiler

- OWNERS
Since @Tomcli and @ckadner were promoted to project `approvers` they no longer are added as (suggested) reviewers to pull requests and hence won't get notified for new PRs (unless watching all repository events). 
Since project `approvers` can also `reviewers`, I suggest reinstating `Tomcli` and `ckadner` as `reviewers` as well.
> Reinstate Tommy and Christian as reviewers

- sdk/python/tests/README.md
- sdk/python/tests/test_kfp_samples.sh
Enhance the `test_kfp_samples.sh` script to optionally include all DSL scripts found in the KFP repository.
./test_kfp_samples.sh \
--include-all-samples \
--dont-list-files
This will include all `core/samples`, 3rd-party contributed samples, tutorials, as well as the compiler `testdata`.
```YAML
Compilation status for testdata DSL scripts:
Success: 25
Failure: 5
Total:   30
Compilation status for core samples:
Success: 18
Failure: 5
Total:   23
Compilation status for 3rd-party contributed samples:
Success: 23
Failure: 5
Total:   28
Overall success rate: 69/84 = 82%
```
When the `--print-error-details` flag is used, a summary of all the compilation errors is appended to the console output -- sorted by their respective number of occurrences:
./test_kfp_samples.sh -a -s …
> Add compilation report for all KFP DSL scripts

- samples/katib/README.md
- samples/trusted-ai/README.md
- samples/trusted-ai/trusted-ai.py
- sdk/README.md
Resolves #
- Add trusted ai example
- Update feature flags when installing Tekton to disable work directory overwrite. Without this flag, work directory are overwritten to /workspace which might break some of the containers. This feature will be enabled by default in the future Tekton release (possibly 0.13)
* Tekton Version (use `tkn version`): 0.11.3
> Add trusted ai example

- OWNERS
@drewbutlerbb4 and @kevinyu98 have both made good contributions to this repo and both are helping with PR reviews. Yet currently they cannot be assigned as reviewers.
This PR proposes to fix that :-) 
/cc @animeshsingh 
---
**Pre-requisite issues:**
> Add Andrew and Kevin as reviewers

- samples/README.md
- samples/trusted-ai/README.md
- samples/watson-train-serve/README.md
- sdk/FEATURES.md
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/testdata/parallel_join.py
- sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.py
- sdk/python/tests/compiler/testdata/sequential.py
- sdk/python/tests/test_util.py
Resolves #
- Minor fixes for markdown format and typo
- Remove python usr/bin headers for consistency
- Remove conditional warnings since we no longer need master build for this feature.
> Minor fixes for markdown, headers, and warnings.

- sdk/FEATURES.md
- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/tests/compiler/testdata/affinity.yaml
- sdk/python/tests/compiler/testdata/artifact_location.yaml
- sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
- sdk/python/tests/compiler/testdata/compose.yaml
- sdk/python/tests/compiler/testdata/condition.yaml
- sdk/python/tests/compiler/testdata/hidden_output_file.yaml
- sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
- sdk/python/tests/compiler/testdata/init_container.yaml
- sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
- sdk/python/tests/compiler/testdata/katib.yaml
- sdk/python/tests/compiler/testdata/loop_static.yaml
- sdk/python/tests/compiler/testdata/node_selector.yaml
- sdk/python/tests/compiler/testdata/parallel_join.yaml
- sdk/python/tests/compiler/testdata/parallel_join_pipelinerun.yaml
- sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
- sdk/python/tests/compiler/testdata/pipeline_transformers.yaml
- sdk/python/tests/compiler/testdata/pipelineparams.yaml
- sdk/python/tests/compiler/testdata/resourceop_basic.yaml
- sdk/python/tests/compiler/testdata/retry.yaml
- sdk/python/tests/compiler/testdata/sequential.yaml
- sdk/python/tests/compiler/testdata/sidecar.yaml
- sdk/python/tests/compiler/testdata/timeout.yaml
- sdk/python/tests/compiler/testdata/timeout_pipelinerun.yaml
- sdk/python/tests/compiler/testdata/tolerations.yaml
- sdk/python/tests/compiler/testdata/volume.yaml
- sdk/python/tests/compiler/testdata/volume_op.yaml
- sdk/python/tests/compiler/testdata/volume_snapshot_op.yaml
- sdk/python/tests/compiler/testdata/withitem_nested.yaml
Resolves #154 
Since Tekton allows multiple step spec in a task whereas Argo only allows one container spec per task, it's not obvious for Tekton to tell which step is from the main ContainerOp. Therefore, we want to rename all the containerOp step name to "main" to distinguish between the initContainers and main step.
This has no impact to our existing examples because we just change the container name for logging with the API.
* Tekton Version (use `tkn version`): 0.11.3
> Rename main step name to "main"

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/testdata/affinity.yaml
- sdk/python/tests/compiler/testdata/node_selector.yaml
- sdk/python/tests/compiler/testdata/tolerations.yaml
This PR tries to resolve: https://github.com/kubeflow/kfp-tekton/issues/146 by using the taskRunSpec instead allowing for settings on task level. 
This PR replicates the usage with taskRun podTemplate spec. However the taskRunSpec also allow for further settings on task level. 
Update to use taskRunSpec podtemplate. Also update the tests to represent the new implementation. 
python version 3.7 is used for testing. 
> Update to use taskRunSpec for podTemplate spec. 

- .travis.yml
- Makefile
- sdk/python/tests/config.yaml
Add a `check_license` target to the `Makefile` to verify the source files (`*.py`, `*.yaml`) contain the license header.
Add the license check to Travis/CI.
* Tekton Version (use `tkn version`): 
- Client version: `0.9.0`
- Pipeline version: `v0.11.0-rc2`
* Kubernetes Version (use `kubectl version`): `1.16`
* OS (e.g. from `/etc/os-release`): `Darwin 19.3.0`
> Verify source files contain license header

- sdk/python/kfp_tekton/compiler/_k8s_helper.py
- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/k8s_helper_tests.py
- sdk/python/tests/compiler/testdata/loop_static.yaml
- sdk/python/tests/compiler/testdata/withitem_nested.yaml
- sdk/python/tests/run_tests.sh
Resolves #151 
`sanitize_k8s_name` cleans and converts the names in the workflow according to [K8s name and label spec](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names)
* Python Version (use `python --version`): `3.7`
* Tekton Version (use `tkn version`): `0.11`
* Kubernetes Version (use `kubectl version`): `0.15`
* OS (e.g. from `/etc/os-release`): `MacOS 10.15.3`
> Sanitize Kubernetes Names

- sdk/FEATURES.md
- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/affinity.yaml
- sdk/python/tests/compiler/testdata/artifact_location.yaml
- sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
- sdk/python/tests/compiler/testdata/node_selector.yaml
- sdk/python/tests/compiler/testdata/parallel_join_pipelinerun.yaml
- sdk/python/tests/compiler/testdata/parallel_join_with_artifacts.yaml
- sdk/python/tests/compiler/testdata/timeout_pipelinerun.yaml
- sdk/python/tests/compiler/testdata/tolerations.yaml
Resolves #168 
Add annotation to support artifacts from input/output parameters. Input artifacts with big data passing is ignored because we are pending #169. 
Change the output artifact location and add annotations for metadata tracking. The design of this approach is documented in this google docs
https://docs.google.com/document/d/1nx63yZzANk8yDAm_Cwx_UHu-SVFrg73GVeshhtaYNsM/edit#heading=h.d1ddt7vobtmu
Major changes:
- Moved `PODNAME` to `PIPELINETASK` as the secondary directory for S3 artifact key.
- Follow the [Argo standard](https://github.com/argoproj/argo/blob/6e5dd2e19a3094f88e6f927f786f866eccc5f500/workflow/controller/workflowpod.go#L877-L878) to compress artifacts into tgz file
- Add default …
> Add artifact annotation for metadata tracking

- README.md
- sdk/FEATURES.md
- sdk/README.md
- sdk/python/README.md
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/testdata/affinity.yaml
- sdk/python/tests/compiler/testdata/big_data_passing.yaml
- sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
- sdk/python/tests/compiler/testdata/node_selector.yaml
- sdk/python/tests/compiler/testdata/tolerations.yaml
Resolves #54 
- Fix taskRunSpecs bugs for v0.13.0 release (there's a missing `s` in the spec)
- Update imagepullsecret to use the Tekton v0.13.0 podTemplate (also help for the single PipelineRun PR)
- Update default Tekton version to v.0.13.0 since we will be moving forward with these new features.
* Tekton Version (use `tkn version`): v0.13.0
> Update imagepullsecret and update to v0.13.0

- samples/big_data_passing/big_data_passing_description.ipynb
- samples/big_data_passing/constant_to_consumer_pipeline.yaml
- samples/big_data_passing/pipeline_parameter_to_consumer_pipeline.yaml
- samples/big_data_passing/print_repeating_lines_pipeline.yaml
- samples/big_data_passing/processing_pipeline.yaml
- samples/big_data_passing/producers_to_consumers_pipeline.yaml
- samples/big_data_passing/sum_pipeline.yaml
- samples/big_data_passing/task_output_to_consumer_pipeline.yaml
- samples/big_data_passing/text_splitting_pipeline.yaml
- samples/big_data_passing/text_splitting_pipeline2.yaml
- sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/big_data_passing.py
- sdk/python/tests/compiler/testdata/big_data_passing.yaml
After PR #170 and PR #169 merged, the case of `test_bigger_data_workflow` will be failed as below, because of incompatibilities:
```
======================================================================
FAIL: test_bigger_data_workflow (compiler.compiler_tests.TestTektonCompiler)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/fengli/go/src/github.com/kubeflow/kfp-tekton/sdk/python/tests/compiler/compiler_tests.py", line 249, in test_bigger_data_workflow
self._test_pipeline_workflow(file_passing_pipelines, 'big_data_passing.yaml', generate_pipelinerun=True)
File "/Users/fengli/go/src/github.com/kubeflow/kfp-tekton/sdk/python/tests/compiler/compiler_tests.py", line 304, …
```
> Update big data failed cases due to changes of PR #170

- sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/testdata/artifact_location.yaml
- sdk/python/tests/compiler/testdata/big_data_passing.yaml
- sdk/python/tests/compiler/testdata/katib.yaml
- sdk/python/tests/compiler/testdata/loop_static.yaml
- sdk/python/tests/compiler/testdata/pipelineparams.py
- sdk/python/tests/compiler/testdata/pipelineparams.yaml
- sdk/python/tests/compiler/testdata/withitem_nested.yaml
Capital letters and underscore characters are supported for parameter name, but not for results in tekton pipelines, and we already coverted the results name/values before workflow created, this will lead to inputs and outputs inconsistency, which lead cases failed. This PR was consolidate the results value converting, by deleting the converting before workflow created, to avoid any underscore convering in params.
/cc @ckadner
> Consolidate the value of results to avoid underscore convering in params

- sdk/FEATURES.md
- sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
- sdk/python/tests/compiler/testdata/exit_handler.py
- sdk/python/tests/compiler/testdata/exit_handler.yaml
Resolves #85
Requirements from watson cases, this PR will support exit handler definiation in kfp-tekton.
The finally syntax is now supported in tekton preview mode as in the final tasks can be specified but not executed yet, implementation and execution of final tasks are tracked in separate PR in tekton are doing that
The exit handler cases below need to be tested after PR 2661 done, issue #180 to trace it:
sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
sdk/python/tests/compiler/testdata/exit_handler.yaml
> Support Exit Handler

- sdk/python/tests/compiler/testdata/condition.py
- sdk/python/tests/compiler/testdata/condition.yaml
The unit test for dsl.Condition previously used a random number generator to dictate which event occurred and therefore which condition would execute. This causes issues with consistent testing as there are multiple valid potential outputs. This test has been changed to be deterministic, to address this issue, by using pipeline parameters to dictate which event occurred and setting default values for the pipeline.
> Remove randomness from condition example

- Makefile
- sdk/README.md
- sdk/python/setup.py
Resolves #185
- Modify `setup.py` to read `long_description` from [`sdk/README.md`](https://github.com/kubeflow/kfp-tekton/blob/master/sdk/README.md)
- Replace relative links with absolute links to `kfp-tekton` GitHub repo
- Add anchor tags around headings for document-internal links from TOC
- Add `make distribution` target for upload to `testpypi`
**Updated SDK README:**
> [sdk/README.md](https://github.com/ckadner/kfp-tekton/blob/PyPi_description_from_Github_README/sdk/README.md)
**Result on Test-PyPi:**
> https://test.pypi.org/project/kfp-tekton/0.1.0rc5/
* Tekton Version (use `tkn version`): `0.13.0`
* Kubernetes Version (use …
> Generate long_description for PyPi from sdk/README.md

- sdk/python/kfp_tekton/__init__.py
- sdk/python/kfp_tekton/_client.py
- sdk/python/kfp_tekton/compiler/__init__.py
- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/kfp_tekton/compiler/compiler.py
- add `TektonClient` to SDK (extends `kfp._client.Client`)
- override `create_run_from_pipeline_func(...)` to run pipeline on Tekton cluster
**Related:**
- #197: [Produce SDK for KFP-Tekton that includes compile, upload, run](https://github.com/kubeflow/kfp-tekton/issues/197)
/cc @Tomcli
> Add TektonClient to SDK

- Makefile
- sdk/python/README.md
Added `verify` target to `Makefile` to have a one-stop-shop approach for pre-commit verification, which is running:
- `check_license`
- `lint`
- `unit_test`
- `report`
Updated the `sdk/README.md` with instruction how to use this new `Make` target.
/cc @Tomcli
> Make verify

- .travis.yml
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/k8s_helper_tests.py
- sdk/python/tests/compiler/testdata/big_data_passing.yaml
- sdk/python/tests/compiler/testdata/withitem_nested.yaml
**Problem:**
Python before `3.6` did not preserve insert order for dictionaries, which causes the generated YAML to be equivalent, yet it can not reliably be compared to the "golden" YAML via `unittest.assertDictEqual`.
**Solution:**
* Sort `dict`s (and `list`s) in unit tests if the Python test runtime predates version 3.6.0
* Ensure string-serialized values are sorted via `json.dumps(..., sort_keys=True)` in the compiler code
* Add unit tests for Python 3.5 to Travis/CI
* Exclude Katib workflow from py35 unit tests as it uses (string-serialized) dictionaries containing `dsl.PipelineParam` objects which can't be JSON-serialized so using `json.dumps(sort..)` is not an alternative
* Python Version (use `python --version`): `3.5`, `3.6`, `3.7` (via `tox`)
/cc @Tomcli
> Make unit tests run with Python 3.5

- frontend/src/lib/WorkflowParser.ts
Resolves #208 
The UI expected the runAfter specification to be a child of taskSpec. The UI now expects runAfter to be a sibling of taskSpec.
> Fix runAfter specification failing to be parsed

- samples/kfp-user-guide/README.md
The word "execute" conjures up images of people getting their life cut short involuntarily.
This PR suggests to use the terms "run" and "running" a pipeline instead. At least in the headings.
https://github.com/kubeflow/kfp-tekton/pull/211#discussion_r449325481
Also, title-casing headings.
/cc @Tomcli
> Don't kill no pipelines :-)

- README.md
- samples/README.md
- sdk/FEATURES.md
- sdk/README.md
- sdk/python/README.md
- sdk/python/tests/compiler/testdata/exit_handler.log
- tekton_kfp_guide.md
Tekton has just released version [`0.14.0`](https://github.com/tektoncd/pipeline/releases/tag/v0.14.0) which implements support for `finally`:
---
- ✨ **implementing pipeline level finally** ([tektoncd/pipelines#2661](https://github.com/tektoncd/pipeline/pull/2661))
Users can now specify Tasks within a Pipeline that will always execute, even if Tasks fail, via the new finally clause
- ✨ **adding finally type** (without implementation) at the pipeline level ([tektoncd/pipelines#2650](https://github.com/tektoncd/pipeline/pull/2650))
Introducing a new clause under pipeline named finally where users can specify a list of tasks that will always execute, even if pipeline tasks fail. Adding a new type and its validation here, stay tuned for this functionality. Without implementing the …
> Upgrade to Tekton version 0.14.0

- backend/Dockerfile
- backend/metadata_writer/src/metadata_writer.py
- backend/src/apiserver/config/sample_config.json
- backend/src/common/util/template_util.go
Resolves #
After the repo restructure, our Tekton examples are now located under /samples. Thus, update the sample_config.json and docker build to compile clip-coin as our init Tekton example in KFP. 
Also updating the default run time to Tekton so that it can run with the default upstream manifest for our dojo deployment.
> Add init tekton samples as part of the apiserver build

- samples/trusted-ai/trusted-ai.py
Resolves #
Trusted-AI projects recently moved to the new LFAI `Trusted-AI` organization. Thus, we need to update the url to pull from the new source
> Update trusted-ai sample to pull the component from new organization

- backend/src/apiserver/resource/resource_manager.go
- backend/src/common/util/workflow.go
Resolves #227 
Update the KFP terminate status because Tekton `cancel` introduced 2 new status  `PipelineRunCancelled`, `PipelineRunCouldntCancel` some time during v0.13 and v0.14 release.
Will open another issue for the UI to handle these new status.
* Tekton Version (use `tkn version`): 0.14
> Update terminate status using the latest tekton api spec

- frontend/src/lib/CompareUtils.ts
Hotfix for a crash coming from the Run Output page when Artifacts are used.
> Fix run output crash when artifacts are present

- Makefile
- sdk/README.md
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/compiler_tests_e2e.py
- sdk/python/tests/compiler/testdata/affinity.py
- sdk/python/tests/compiler/testdata/affinity.yaml
- sdk/python/tests/compiler/testdata/basic_no_decorator.log
- sdk/python/tests/compiler/testdata/basic_no_decorator.py
- sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
- sdk/python/tests/compiler/testdata/compose.log
- sdk/python/tests/compiler/testdata/exit_handler.log
- sdk/python/tests/compiler/testdata/node_selector.py
- sdk/python/tests/compiler/testdata/node_selector.yaml
- sdk/python/tests/compiler/testdata/pipelineparams.log
- sdk/python/tests/compiler/testdata/retry.py
- sdk/python/tests/compiler/testdata/sidecar.log
* Upgrade `tkn` CLI version to `0.11`
* Now including logs for `finally` tasks
* Add environment variable to modify `SLEEP_BETWEEN_TEST_PHASES` on cluster
* Add `retry.yaml` to ignored test cases since it is designed to fail randomly
* Change `node_selector`s to be more generic
* Use `pipelinerun` `status.conditions[].reason` instead of `.. [].type`
* Treat `pipelinerun` status `"Completed"` as `"Succeeded"`
- Pipeline version: `0.14.2`
- Client version: `0.11.0`
**Additional information:**
- Optional environment variables to configure `e2e_test`, examples:
``` …
```
> Upgrade E2E tests for tkn CLI version 0.11

- backend/metadata_writer/src/metadata_writer.py
- backend/src/apiserver/common/config.go
- backend/src/apiserver/common/const.go
- backend/src/apiserver/resource/resource_manager.go
- manifests/kustomize/env/platform-agnostic/apiserver-deployment.yaml
- manifests/kustomize/env/platform-agnostic/kfp-pipeline-install-config.yaml
- manifests/kustomize/env/platform-agnostic/kustomization.yaml
Resolves #269 
related: #277 
Implement our own configmap for things that are unique to kfp-tekton. This includes configurable artifact credentials on the server side (since Tekton doesn't support it) and other flags/settings that we want to add later on.  This PR builds the foundation for the artifact refactoring where we will be moving all the SDK client side logic to the server side.
* Tekton Version (use `tkn version`): 0.15
> Feature: Configurable artifact credentials and annotations

- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/volume_logging.yaml
Resolves #
There's a typo bug when both user and artifact volumes are present, the artifact volumes such as logging are ignored due to the typo on the dictionary key. Thus, update the key to the correct value and add a test case to cover it.
* Tekton Version (use `tkn version`): 1.14
**Checklist:**
* `chore: …
> fix(sdk): Fix volumes bug on wrong dict key

- .travis.yml
- Makefile
**Which issue is resolved by this Pull Request:**
Resolves #288
Move `pytest` dependency from `.travis.yml` to `Makefile`
* OS (e.g. from `/etc/os-release`): Mac OS
/cc @Tomcli
> Move pytest dependency into Makefile

- Makefile
- sdk/python/tests/compiler/compiler_tests_e2e.py
Resolves #284
Remove the dependency on `KUBECONFIG` environment variable but keep it as an option to easily target various clusters for end-to-end testing. 
* Tekton Version (use `tkn version`): `0.15.1`
* Kubernetes Version (use `kubectl version`): `0.16.14+IKS`
* OS (e.g. from `/etc/os-release`): Mac OS Catalina
/cc @Tomcli
> Remove dependency on KUBECONFIG environment variable

- OWNERS
removing andrea, jinchi and kevin as reviewer
reviews should be directed to folks who are active to optimize.
> Updating reviewers

- samples/logging_s3/pipeline_log_to_s3_by_fluentd_recommend/fluent-config.yaml
Resolves #276
**Reason:**
Log format is not json format in some k8s cluster, e.g. Kubernetes v1.16.2:
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"a02f27a", GitTreeState:"clean", BuildDate:"2020-04-13T12:04:13Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
cat /var/log/containers/parallel-pipeline-e2345-gcs-download-2-lgg4h-pod-vhsw2_tommy-chaoping-li_step-copy-artifacts-4eaa6e5ecad4770497b4e707b5bc6a1ef911aac2afc2ebc11ec1d16d24a850bc.log
2020-08-27T18:37:20.410919774Z stdout F Added `storage` successfully.
2020-08-27T18:37:20.419098255Z stdout F step-main.log
2020-08-27T18:37:20.477559075Z stdout F `main-log.tgz` -> …
```
> Address no logs achived to S3 with kubernets 1.6

- .travis.yml
- Makefile
- sdk/python/tests/compiler/compiler_tests_e2e.py
Update `.travis.yml` and `Makefile` to avoid duplicate/redundant `pip install steps` by making sure that the `make` targets use the already existing Python `virtualenv` created by Travis, instead of creating a second `VENV` inside the `make` process. This should speed up Travis build times and reduce resource consumption slightly, but at the very least it makes for more readable build logs.
* Python Version (use `python --version`): `3.5`, `3.6`, `3.7`
* OS (e.g. from `/etc/os-release`): Mac OS Catalina, Linux Ubuntu 16.04.6 LTS
/cc @Tomcli
> Make should use specified VENV

- samples/e2e-mnist/mnist.ipynb
Resolves #
The single user default service account is `pipeline-runner`, so fixing the typo in this example.
* Tekton Version (use `tkn version`): 1.14
**Checklist:**
* `test: …
> Fix permission typo in the e2e-mnist example

- sdk/README.md
- sdk/python/README.md
- sdk/python/setup.py
Documentation update for the 0.3.0 release on PyPi.
Preview release: https://test.pypi.org/project/kfp-tekton/0.3.0rc5/
* Python Version (use `python --version`): 3.7.5
* Tekton Version (use `tkn version`): 0.15
* OS (e.g. from `/etc/os-release`): Mac OS 10.15
/cc @animeshsingh
> Prepare PyPi distribution for release 0.3.0

- sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
- sdk/python/tests/compiler/testdata/big_data_passing.yaml
Resolves #181
Remove persistentVolumeClaim by volumeClaimTemplate, since we already used the Tekton version > 0.12
```
(.venv)  fengli@fenglis-MacBook-Pro  ~/go/src/github.com/kubeflow/kfp-tekton/sdk/python/tests   remove_pvc  kc get po |grep file
file-passing-pipelines-gen-params-mv8h8-pod-hqhnv         0/1     Completed   0          2d13h
file-passing-pipelines-print-params-25vkf-pod-zvpsm       0/1     Completed   0          2d13h
file-passing-pipelines-print-text-2-qsccx-pod-s5fkx       0/1     Completed   0          2d13h
file-passing-pipelines-print-text-3-xj69j-pod-mxvl8       0/1     Completed   0          2d13h
file-passing-pipelines-print-text-4-kfnr7-pod-9rfxq …
```
> Remove persistentVolumeClaim by volumeClaimTemplate

- backend/src/agent/persistence/worker/metrics_reporter.go
Fix issue with persistence agent crashes on nil `nodeStatus.Status`.
Resolves 334
The failure scenarios when Status in PipelineRunTaskRunStatus is nil is ignored.
**Checklist:**
Use `chore` to indicate that this PR makes some changes …
> fix(backend): MetricsReporter fails on `nil` nodeStatus.Status

- sdk/python/kfp_tekton/compiler/_k8s_helper.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/k8s_helper_tests.py
Resolves #332
Added process and testcases for recursively sanitizing k8s container object type based on the kubernetes.client.models definition. Currently primitive types of string, integer, boolean, list of string are all the types included in kubernetes.client.models.V1Container and its children attributes.
* Python Version (use `python --version`): 3.7.7
* Tekton Version (use `tkn version`): 0.13.1
* Kubernetes Version (use `kubectl version`): v1.16.15
* OS (e.g. from `/etc/os-release`): Ubuntu 18.04
**Checklist:**
* `feat(backend): configurable service account. …
> feat(sdk): added sanitizing k8s object process and test. Fixes: #332

- .travis.yml
- Makefile
- guides/kfp_tekton_install.md
- samples/kfp-tfx/tfx-taxi-on-prem/README.md
- samples/logging_s3/pipeline_log_to_s3_by_banzaicloud/pipeline_logging_output_s3_banzaicloud.md
- sdk/FEATURES.md
- sdk/python/setup.py
- tools/python/verify_doc_links.py
**Description of changes:**
* Add Python script `tools/python/`[`verify_doc_links.py`](https://github.com/kubeflow/kfp-tekton/blob/d4b1d06/tools/python/verify_doc_links.py) to verify links in Markdown files are valid
* Add [`check_doc_links`](https://github.com/kubeflow/kfp-tekton/blob/d4b1d06/Makefile#L104-L108) target to `Makefile`
* Add doc link check [job](https://github.com/kubeflow/kfp-tekton/blob/d4b1d06/.travis.yml#L56-L62) to **[Travis/CI](https://github.com/kubeflow/kfp-tekton/pull/363/checks?check_run_id=1392818301)**
**Script details:**
1. Find all Markdown files based on predefined path expressions:
- `./guides/**/*.md`
- `./samples/**/*.md`
- `./sdk/**/*.md`
- `./*.md`
2. Extract all Markdown links of form `[link text](url)`
3. Complete relative links with path to GitHub …
> Verify all Markdown links are valid

- frontend/src/lib/ParserUtils.ts
- frontend/src/lib/StaticGraphParser.ts
- frontend/src/lib/WorkflowParser.ts
- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/set_display_name.py
- sdk/python/tests/compiler/testdata/set_display_name.yaml
Resolves #368 
The set_display_name creates an annotation for the ui to detect and replace the node name without changing any runtime dependency. This wasn't implemented previously because task wise metadata is introduced at Tekton 0.16.3. 
* Tekton Version (use `tkn version`): 0.16.3
**Checklist:**
* …
> fix(ui and sdk): Support display name annotations

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/kfp_tekton/compiler/yaml_utils.py
Resolves #389.
When dumping strings such as `y`, `n`, `Y`, `N` etc, explicit `"` should be added around them.
* Python Version: 3.9.0
* SDK Version: 0.4.0
Seems like it can be cherry-picked.
> fix(sdk): dump "y" and "n" in enforced string mode

- tools/python/verify_doc_links.py
Limit the scope to the Markdown link verification to URLs that return a 404: Not Found error. Ignore rate limited URLs.
https://github.com/kubeflow/kfp-tekton/pull/395#issuecomment-747739862
/cc @Tomcli
> Limit scope of Markdown link verification to 404 errors

- scripts/check_diff.sh
Resolves https://github.com/kubeflow/kfp-tekton/issues/405
Fix notation to loop over bash array. Previous version works on mac but not ubuntu/xenial, which is what travis runs in.
**Checklist:**
Use `chore` to indicate that this PR …
> test: fix backend docker build used in travis. Fixes #405

- sdk/FEATURES.md
- sdk/python/kfp_tekton/compiler/_tekton_hander.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.py
- sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
- sdk/python/tests/compiler/testdata/tekton_pipeline_variables.py
- sdk/python/tests/compiler/testdata/tekton_pipeline_variables.yaml
/feature
The PR is going to resolve the problem:
If we used the tekton pipeline level variables,  such as `context.pipelineRun.name` or `context.pipelineRun.namespace`, see detail of tekton variable [here](https://github.com/tektoncd/pipeline/blob/master/docs/variables.md) . 
Currently even if we defined those variables in inputs section of components,  after compiled by dsl, the variables is not loaded, and only replace value in containerOps. In fact, that's pipeline level variables, we need to pass that by `params`, cannot use ``context.pipelineRun.namespace` in containerOps directly, see the example for details: https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/using_context_variables.yaml
**Description of …
> Handle Tekton pipeline level variables

- backend/Dockerfile
- backend/update_requirements.sh
fix get-pip.py error while using old version
of python (3.5)
Its origin is this [commit](https://github.com/kubeflow/pipelines/commit/a8b7fc97b177b8fd835315d116482bf293cfa8a4)
Resolves #
**Checklist:**
> fix(backend): Update python version in Dockerfile

- sdk/python/requirements-test.txt
- sdk/python/requirements.in
- sdk/python/requirements.txt
- sdk/python/setup.py
Move `kubernetes` from SDK requirements to test requirements. This became apparent during [conda-forge build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=270749&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=619). 
/cc @Tomcli
> Move kubernetes from SDK requirements to test requirements

- Makefile
- guides/developer_guide.md
- manifests/kustomize/base/kustomization.yaml
- manifests/kustomize/env/kfp-template/kustomization.yaml
Resolves #
Let Travis to also run tests against the new cache server code.
**Checklist:**
> Add CI and makefile tests for cache server

- backend/Dockerfile
Some python dependencies changes cause the api-server image
failure. Some dependencies of kfp sdk need higher version then
the requirement.txt in `backend` directory. Since the second
stage is to compile the samples by using kfp sdk, directly
install the requirements.txt from `sdk/python` instead of
`backend`.
Resolves #
**Checklist:**
[Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull …
> fix: failed to build api-server image

- .travis.yml
- sdk/README.md
- sdk/python/README.md
Related https://github.com/kubeflow/pipelines/issues/4584
Remove python 3.5 support since it's no longer supported in kfp. Move travis test to python 3.8 instead.
* Python Version (use `python --version`): 
**Checklist:**
> Remove python 3.5 support

- guides/kfp_tekton_install.md
- sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.log
- sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.py
- sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
Resolves #470
Added the missing quote character to terminate the workflow.name variable string. Regenerated the corresponding YAML and log file.
* Python Version (use `python --version`): `3.9`
* Tekton Version (use `tkn version`): `0.20`
* Kubernetes Version (use `kubectl version`): `1.18`
> Fix parallel_join_with_argo_vars pipeline (#470)

- sdk/python/kfp_tekton/compiler/yaml_utils.py
> Roll back the default_flow_style to fix the double quote issue

- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/artifacts_of_ops_with_long_names.py
Resolves #540
1. Add a test to check if the issue is fixed.
2. Sanitise artefact name before searching for it in the artefact name mapping (where it's sanitised already).
3. Remove limit on the length of sanitised artefact name.
* Python Version (use `python --version`): 3.9
________
Please add `cherrypick-approved` label.
> fix(sdk): fix artifacts of ops with long names

- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Resolves #
Add extra label `custom.tekton.dev/parentPipelineRun` to sub pr which created by pipeliine loop. 
the label make a content which is the name of original pipeline.
It's help management server to know the relationship between `pr`s.
**Checklist:**
> Add extra label to sub pr

- backend/src/apiserver/common/config.go
- backend/src/apiserver/resource/resource_manager.go
- guides/kfp-admin-guide.md
Resolves #536
Fix viper flag to the standard format and update cache flag and istio injections to the Tekton pipeline level. 
**Checklist:**
> Fix viper flags and labels/annotations injections on custom task

- backend/src/apiserver/storage/run_store.go
- frontend/src/lib/StatusUtils.ts
Resolves #
Tekton introduced a new status "PipelineRunStopping" when the pipeline is still running with one or more tasks failed. This behavior used to be part of the "Running" status. Therefore, we need to update the UI and the API to treat this status as a "Running" pipeline. (e.g. terminable) 
* Tekton Version (use `tkn version`): 0.23.0
**Checklist:**
> Support Tekton PipelineRunStopping status

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/artifacts_of_ops_with_long_names.py
- sdk/python/tests/compiler/testdata/long_param_name.py
- sdk/python/tests/compiler/testdata/long_param_name.yaml
Resolves #548
This PR introduced few changes:
1. Parameters at the param section are now capped at 128 characters (according to the kfp api requirements for displaying node id) https://github.com/kubeflow/pipelines/blob/master/frontend/src/apis/run/api.ts#L424-L429
2. The whole string size for Tekton parameters are capped at 253 because they have the same requirements as the annotation/label keys
3. The maximum op name for each opsgroup is 57 characters. Because in Tekton, opsgroup name is the same as Tekton task name which has to follow the K8S DNS label standard (with < 63 characters for the taskrun name) https://github.com/tektoncd/pipeline/blob/main/pkg/apis/pipeline/v1beta1/pipeline_types.go#L256-L262 …
> Fix long param compile errors

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/recur_cond.py
- sdk/python/tests/compiler/testdata/recur_cond.yaml
- sdk/python/tests/compiler/testdata/recur_cond_pipelineloop_cr1.yaml
related #547 
Fix the first bug on #547 related to omitted recursive task when there's no sub_group.ops inside a condition branch. 
**Checklist:**
> Fix recursive loop bug with no sub_group.ops

- sdk/python/README.md
Resolves #
Fix broken Kubeflow doc links due to the KF 1.3 website release.
**Checklist:**
> Fix broken Kubeflow doc links to map with the KF 1.3 website

- install/v0.8.0/kfp-tekton.yaml
- manifests/kustomize/base/cache/kustomization.yaml
- manifests/kustomize/base/installs/generic/kustomization.yaml
- manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
Resolves #
The 1.5.0 rebase overwrite our default cache image in the manifests which causes some issue on certain Kubernetes version and Openshift. Thus revert it back to the redhat UBI image we use to make it work on all platform.
Also clean up the manifests on the image patching section.
**Checklist:**
> Clean up and revert cache image env on manifests

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/testdata/tekton_custom_task.log
- sdk/python/tests/compiler/testdata/tekton_custom_task.py
- sdk/python/tests/compiler/testdata/tekton_custom_task.yaml
Resolves #577 
When passing the Tekton result parameters with underscore keys to custom tasks, the Tekton variables are not properly sanitized. Thus, this PR fix the sanitization for custom task inputs.
**Checklist:**
> Sanitize Tekton result parameters when passing to custom task inputs

- backend/src/apiserver/resource/resource_manager.go
- backend/src/apiserver/resource/resource_manager_test.go
Resolves #578 
This PR address the API log issue with standard Tekton tasks. For standard Tekton tasks on KFP, we name the main container as "main" following the Argo convention. However, the Tekton controller will always inject the `step-` prefix to all the user steps when translating them into containers because it may inject initial containers and sidecars under certain settings. 
As for custom task, there's no concept of steps anymore because the workload is not always backed by a new single pod. Thus, currently it will return an error message to let any client know the log api for custom task is not valid rather than of panic. e.g. for CEL custom task, there's no dedicated pod backing for this task …
> Fix /logs api and add tests

- .tekton/listener.yaml
- .tekton/pipeline.yaml
- .tekton/task.yaml
- scripts/deploy/iks/e2e-test.sh
- scripts/deploy/iks/tekton-catalog/deploy-any-sequencer-e2e.sh
- scripts/deploy/iks/test-flip-coin.sh
- scripts/deploy/iks/test-trusted-ai.sh
Add trusted-ai into the e2e testing and a flag (extra-test-cases)
to enable it. Also refactor the e2e-test task to support more test cases.
**Checklist:**
> [test] Add trusted-ai into e2e testing

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/kfp_tekton/tekton.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/cond_recur_pipelineloop_cr1.yaml
- sdk/python/tests/compiler/testdata/condition.yaml
- sdk/python/tests/compiler/testdata/condition_custom_task.yaml
- sdk/python/tests/compiler/testdata/condition_dependency.yaml
- sdk/python/tests/compiler/testdata/conditions_and_loops_pipelineloop_cr1.yaml
- sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml
- sdk/python/tests/compiler/testdata/custom_task_recur_with_cond.py
- sdk/python/tests/compiler/testdata/custom_task_recur_with_cond.yaml
- sdk/python/tests/compiler/testdata/custom_task_recur_with_cond_pipelineloop_cr1.yaml
- sdk/python/tests/compiler/testdata/recur_cond.py
- sdk/python/tests/compiler/testdata/recur_cond.yaml
- sdk/python/tests/compiler/testdata/recursion_while_pipelineloop_cr1.yaml
- sdk/python/tests/compiler/testdata/tekton_custom_task.yaml
- sdk/python/tests/compiler/testdata/withitem_nested_pipelineloop_cr2.yaml
Resolves #584 
When using custom task with conditions as I/O for recursion and for loop, we need to update the following to make it work
1. Change the default condition outputs from `status` to `outcome` because `status` is a keyword for pipelineloop custom task to look for pipeline status. Thus producing the following errors
```
invalid value: pipeline tasks can not refer to execution status of any other pipeline task
```
Other keywords such as `results` and `outputs` are keywords for tekton variables which can also have conflicts when passing it to different pipelineRun. Therefore we rename the default condition output to `outcome` to avoid any Tekton/custom task controller conflicts.
2. Overwrite the …
> Fix custom task condition I/O behaviors on recursion and for loop

- tekton-catalog/pipeline-loops/README.md
- tekton-catalog/pipeline-loops/examples/loop-example-with-parallelism.yaml
- tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_defaults.go
- tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go
- tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_validation.go
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
- Parallelism is defaulted to 1
- if Parallelism is bigger then total iteration numbers, then start all
- normally start the same number of pipelineruns as Parallelism value
Resolves #542
> Add Parallelism support on backend.

- scripts/check_diff.sh
- sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/custom_task_spec.py
- sdk/python/tests/compiler/testdata/custom_task_spec.yaml
- sdk/python/tests/compiler/testdata/custom_task_spec_customtask_cr1.yaml
- sdk/python/tests/e2e_test_config.yaml
Resolves #590 
Detect new field `taskSpec` for defining custom task CR spec in literal format. Right now custom task CRs are generated as separate yaml similar to loop until we get support for embedded custom task (planned Tekton 0.25). 
See #588 for the new usage
**Checklist:**
> Add support to generate custom task with custom task cr

- manifests/kustomize/base/pipeline/pipeline-runner-role.yaml
After PR #583, any-sequencer can watch runs but during test using pipeline-runner it complains lack of permission.This PR solve the issue. 
BTW, not sure whether we should add it for kfp-tekton.yaml under install directory. @Tomcli
> Permit pipeline-runner to operate on runs

- tekton-catalog/pipeline-loops/README.md
- tekton-catalog/pipeline-loops/cmd/webhook/main.go
- tekton-catalog/pipeline-loops/examples/loop-example-basic_taskspec.yaml
- tekton-catalog/pipeline-loops/examples/simplepipelineloop_taskspec.yaml
- tekton-catalog/pipeline-loops/go.mod
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Resolves #
Updated to latest tektoncd version.
go mod tidy
and passed all tests.
**Checklist:**
> feat(pipelineloop) : Support latest tektoncd pipeline version.

- .tekton/listener.yaml
- .tekton/pipeline.yaml
- scripts/deploy/iks/tekton-catalog/deploy-pipeline-loops-e2e.sh
Add a flag to turn on/off the pipeline-loop e2e test case.
By default, the pipeline-loop test case is turned on. Use
`skip-pipeline-loop:1` to turn it off.
Currently, `pipeline-loop` test case depends on the latest tekton. However, the latest version is not final yet and the manifest is not updated either. For now, the e2e testing should skip `pipeline-loop` test case and resume it when the tekton release is available.  
**Checklist:**
> [test] Add pipeline-loop flag

- sdk/python/README.md
- sdk/python/kfp_tekton/__init__.py
- sdk/python/requirements.in
- sdk/python/requirements.txt
- sdk/python/setup.py
- sdk/python/tests/README.md
- sdk/python/tests/compiler/testdata/resourceop_basic.yaml
- sdk/python/tests/compiler/testdata/volume_op.yaml
- sdk/python/tests/compiler/testdata/volume_snapshot_op.yaml
- sdk/python/tests/test_kfp_samples.sh
Resolves #595
Because KFP skipped the `1.5.0` release for the SDK, we built the `kfp-tekton` `0.8.0` SDK based on the KFP SDK sources in the KFP repo (instead of depending on the proper pip-installable `kfp==1.5.0` release). 
However, `pip install kfp-tekton==0.8.0` will fail since no PyPI package is allowed to depend on packages built from GitHub. 
So in this PR we need to decide if we should create a "fix-patch" release `kfp-tekton==0.8.1` based on `kfp==1.4.0` or `kfp==1.6.3` ([`sdk/python/requirements.in`](https://github.com/kubeflow/kfp-tekton/pull/617/files#diff-63a2db662374dbedfd8bcec50462e9460017527f7efc41d5f5b80ef702f179e3L2-R1)):
```diff
diff --git a/sdk/python/requirements.in b/sdk/python/requirements.in
index 9743334a..8a1727e2 100644
--- a/sdk/python/requirements.in
+++ …
```
> Upgrade Python SDK to kfp==1.6.3

- tekton-catalog/pipeline-loops/Makefile
- tekton-catalog/pipeline-loops/README.md
- tekton-catalog/pipeline-loops/cmd/cli/main.go
Resolves #611
Added a cli to pipelineLoop for detecting validation errors in embedded Spec in a Run, Pipeline or a PipelineRun.
/kind feature
**Checklist:**
> feat(pipelineLoop): Create a validation CLI for commonly used Tekton custom task CRDs

- scripts/deploy/iks/deploy-ibm-vpc.sh
Resolves #
A VPC may have more than one public gateways and they may be in
different cluster zones. So now filtering on `cluster_zone` and
picking the first public gateway.
Mac OSX
* Tekton Version (use `tkn version`): v0.25.0
**Checklist:**
> fix(scripts): deploy-ibm-vpc.sh public gateway detection.

- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Ralated with https://github.ibm.com/AILifecycle/tracker/issues/1658
For Loop, there may be create a sub pipelineRun, and the sub PR (children PR) may create a grandchildren PR. we need to a key (labels) for all pipelineRuns which is created by original PR to save global user variables.
**Checklist:**
> Add original PipelineRun name

- manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-config.yaml
Resolves #
The kubeflow/manifests instruction uses the old v3.2 kustomize in order to support istio and other old manifests. Thus, we need to force our kustomize patch to work on v3.2 to support the kubeflow/manifests instruction. 
**Checklist:**
> Make kustomize patch backward compatible with v3.2

- tekton-catalog/pipeline-loops/cmd/cli/main.go
- tekton-catalog/pipeline-loops/examples/pipelinespec-with-nested-loop-embedded.yaml
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Added missing enablement of feature-flag enable-custom-task.
Also added nested task validation.
Resolves #637 
**Checklist:**
> fix: PipelineLoop nested validation logic fixed.

- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Resolves #488 
I figured out #488 issue sometimes occur because the pipeline loop controller also copy the runid label to its child pipelineruns. The runid label should be unique across all pipelineruns because the KFP persistent agent is using that as the key to persistent pipelinerun spec into the mysql database. The spec in the database is the source for all the KFP API calls.
Thus, removing the `runid` will stop persistent agent copying the wrong pipelinerun into the mysql database which stop causing inconsistent results from the API.
* OS (e.g. from …
> Remove runid labels from pipelineloop's child pipelinerun 

- guides/kfp-user-guide/README.md
Resolves #
Argo project is renamed to argo-workflows, and the Github redirect link is not longer working. Thus update the link to fix the tests.
**Checklist:**
> Fix argo redirect link in the docs

- sdk/python/kfp_tekton/compiler/compiler.py
Resolves #656
For `dsl.ParallelFor` loop arguments, always `json.dump` instead of `str`ingifying in some cases.
* SDK Version: master's HEAD 77963c3ceaf042bba1278797c349fe83dc79701b
________
Please add `cherrypick-approved` label.
> fix(sdk): loop argument jsonified, not stringified

- frontend/src/pages/RunDetails.tsx
Resolves #678
Add a catch for when a pod can not be fetched even though caching is enabled for that pipeline.
**Checklist:**
> Add check for missing pod in cache

- sdk/README.md
The current Argo link now redirects to the Github repo for the website https://github.com/argoproj/argocon21. It should point to https://github.com/argoproj/argo-workflows
KFP updated the same link a month ago [https://github.com/kubeflow/pipelines/commit/ade3454](https://github.com/kubeflow/pipelines/commit/ade3454#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R56)
> Update Argo link

- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
define cancel patch as global var and initialize it at package init func
* Tekton Version (use `tkn version`): Client version: 0.17.2 Pipeline version: v0.25.0
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"} …
> define cancel patch as global var and initialize it at package init

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/custom_task_ref_timeout.py
- sdk/python/tests/compiler/testdata/custom_task_ref_timeout.yaml
Resolves #704
Added a case for timeout to be added when it is configured for custom tasks. 
**Checklist:**
> feat(sdk): Update SDK to support custom task timeout on Tekton 0.27

- .tekton/pipeline.yaml
Resolves #
With the new license check, KFP core image build cannot have other go vendor in the workspace. Hence, we need to finish building all the KFP core image first before build the other Tekton task/controller binaries that generates go vendor.
**Checklist:**
> Update CI pipeline with new dependency flow

- sdk/python/README.md
- sdk/python/setup.py
I came across some slightly outadate versions while creating the [v1.0.0 PyPI distribution](https://pypi.org/project/kfp-tekton/1.0.0/):
* Reference to `kfp` SDK from 1.7.1 to 1.7.2 in sdk/python/README.md
* PyPI distro comment in sdk/python/setup.py
@Tomcli
> Update SDK versions

- frontend/src/lib/v2/WorkflowUtils.ts
- frontend/src/pages/PipelineDetails.tsx
Resolves #
There are some new logics to check for Argo yaml when the pipeline could be in v2 compatible mode. Remove the Argo condition so if V2 and V2 compatible mode are not valid, it fails back to render with our Tekton DAG library.
**Checklist:**
> Remove Argo template UI reference to avoid UX conflicts with v2 compatible mode

- sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/data_passing_pipeline_param_as_file.py
- sdk/python/tests/compiler/testdata/data_passing_pipeline_param_as_file.yaml
- sdk/python/tests/compiler/testdata/data_passing_pipeline_param_as_file_noninlined.yaml
Resolves #733 
Remove the limitations for the pipeline parameter consumed as file.
* Python Version (use `python --version`): Python 3.8.6
* Kubernetes Version (use `kubectl version`): v1.21.1
* OS (e.g. from `/etc/os-release`): RHEL8.4
**Checklist:**
> [Only review]Fix #733 the pipeline parameter consumed as file

- sdk/python/kfp_tekton/compiler/compiler.py
In some rare cases (difficult to reproduce), pipeline params in custom tasks are not recognised as `orig_params` and therefore `$(inputs.params.foo-bar)` is produced instead of `$(params.foo-bar)`.
When custom task spec is overwritten from its `taskSpec`, all fields were pasted as-is. However, one of those was `"orig_params": task_ref["params"]` --- which works differently the first and the second time it's called, thus dropping the actual information on original parameters.
This PR factors out that variable and pastes it in both places without dropping its previous value.
* Kubernetes …
> fix(sdk) orig_params being overwritten in custom-tasks

- scripts/deploy/iks/deploy-kfp.sh
- scripts/deploy/iks/tekton-catalog/setup-kubectl-wrapper-deploy.sh
rename the variable in the script to avoid using the variable in
the build.properties
also add more time for waiting the kfp-tekton deployment
> [test] fix variable overriding

- frontend/src/lib/WorkflowParser.ts
- sdk/python/kfp_tekton/compiler/compiler.py
Resolves #767 
The UI backward compatibility for dsl.container syntax was broken because there's some new metadata introduced for the cached workloads. So we add a dummy annotation template when users didn't create the pipeline using the component.yaml.
**Checklist:**
> Add UI backward compatibility for dsl.container syntax

- sdk/python/tests/compiler/performance_tests.py
Adding a rudimentary performance test script, to be improved over time.
The script loads a small set of pipelines, currently from the compiler testdata.
For each pipeline it times ...
* pipeline compilation
* pipeline run submit
* pipeline run time
And adds the records to a CSV file:
|Pipeline|Compile|Submit|Run|
|-|-|-|-|
|sequential_pipeline|0:00:00.081066|0:00:00.322569|0:00:29.895088|
|flipcoin|0:00:00.123511|0:00:00.646792|0:01:42.271202|
|save_most_frequent_word|0:00:00.042771|0:00:00.369670|0:01:29.414623|
|retry_sample_pipeline|0:00:00.072874|0:00:00.277650|0:00:40.157533|
|pipeline|0:00:00.103826|0:00:00.322516|0:00:26.575043|
|conditions_and_loops|0:00:00.144815|0:00:00.483953|0:02:06.636966|
|...| | | |
**Environment variables to set:** …
> Add performance test script

- backend/src/apiserver/resource/resource_manager.go
Resolves #774 
The current archived logs has to mount on kubelet in order to get the log files. However, in custom tasks, all workloads are ran inside the same controller that shares the same log file. Archived logs for custom task probably needs to be controller specific because only the controller knows how to capture the logs inside the reconciler and push them to object storage for archive. 
Remove kubelet mounting from custom task to prevent potential conflicts because custom tasks are not pods. They are just another entry in the k8s etcd. 
* OS (e.g. …
> Fix archived logs for custom tasks

- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Resolves #
We want to get the current iteration item in the pipeline's task node for condition check and any other purpose.
Any task run created by this pipeline will inherit the annotation list.  In our customer run we can get the item value and to our logic.
Get the current iteration item and add it to the pipelinerun's annotation list.
> expose current iteration item to pipelinerun's annotation

- tekton-catalog/pipeline-loops/cmd/webhook/main.go
- tekton-catalog/pipeline-loops/examples/loop-example-basic.yaml
- tekton-catalog/pipeline-loops/go.mod
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Part I of #765 
Added support for retry to pipeline loop controller. In order to retry, it disposes off the failed pipeline run and creates a fresh one.
**Checklist:**
> feat(pipelineloop): Implement retry for pipelineloop controller.

- tekton-catalog/pipeline-loops/examples/loop-example-basic-retry.yaml
Resolves #
Right now the e2e test cannot handle the new retry feature. Move the retry test out of the e2e flow for now.
**Checklist:**
> Move loop retry test as a different example

- sdk/python/kfp_tekton/compiler/main.py
- sdk/python/tests/perf_test_config.yaml
- sdk/python/tests/performance_tests.py
Updates to the performance test script:
* Move the the `performance_test.py` outside of the `compiler` folder (since the scope is beyond compiler testing) 
* Add `perf_test_config.yaml` with paths of test pipelines
* Add a `Status` column to output CSV file
* Update `compile_pyfile` to remove loaded pipeline module after compilation to allow subsequent imports of another module with the same name
**Output:**
| Pipeline | Status | Compile\_Time | Submit\_Time | Run\_Time | Num\_TaskRuns | Num\_Runs | Total\_TaskRun\_Time | Total\_Run\_Time |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| trusted-ai | Failed | 0:00:00.370032 | 0:00:08.471185 | 0:05:27.214805 | 1 | 0 | 0:04:26 | 0:00:00 |
| calc\_pipeline | Succeeded | 0:00:00.163394 | …
> Load performance test pipelines from files

- sdk/python/kfp_tekton/tekton.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/tekton_loop_dsl.py
- sdk/python/tests/compiler/testdata/tekton_loop_dsl.yaml
- sdk/python/tests/compiler/testdata/tekton_loop_dsl_noninlined.yaml
Related #791
Add SDK skeleton for Tekton specific DSL extensions.
**Checklist:**
> Add tekton loop dsl extension skeleton

- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Resolves #807 
PR #807 only checks "run" name with the break task "pipelineloop-break-operation", we should also check "taskrun" name to find the break task as well.
**Checklist:**
> update pipelineloop operator to check break tasks with taskrun

- manifests/kustomize/base/installs/multi-user/api-service/cluster-role-binding.yaml
- manifests/kustomize/base/installs/multi-user/api-service/cluster-role.yaml
- manifests/kustomize/base/pipeline/cluster-scoped/scheduled-workflow-crd.yaml
- manifests/kustomize/base/pipeline/cluster-scoped/viewer-crd.yaml
- manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/201-rolebinding.yaml
- manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/202-clusterrolebinding.yaml
- manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/300-pipelineloop.yaml
- tekton-catalog/pipeline-loops/config/201-rolebinding.yaml
- tekton-catalog/pipeline-loops/config/202-clusterrolebinding.yaml
- tekton-catalog/pipeline-loops/config/300-pipelineloop.yaml
Resolves #
The current pipelineloop and some manifests are still using v1beta1, we need to update them to work on k8s 1.22+.
This should make standalone deployment works on k8s 1.22. 
**Checklist:**
> Update pipelineloop and manifests with k8s 1.22 API

- manifests/kustomize/base/installs/multi-user/api-service/cluster-role.yaml
- manifests/kustomize/base/installs/multi-user/pipelines-ui/cluster-role.yaml
- manifests/kustomize/base/installs/multi-user/scheduled-workflow/cluster-role.yaml
- manifests/kustomize/base/pipeline/ml-pipeline-apiserver-role.yaml
- manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
- manifests/kustomize/base/pipeline/ml-pipeline-ui-role.yaml
- manifests/kustomize/base/pipeline/pipeline-runner-role.yaml
- samples/flip-coin/condition-with-taskref.py
- sdk/python/kfp_tekton/compiler/compiler.py
Resolves #804 
Have an alternative option to convert taskspec to taskref for reducing maximum yaml size. For kfp-tekton, the default behavior will stay with a single pipelinerun yaml spec because KFP cannot manage tasks on a namespace level.
The original issue here listed the cons for using taskref, such as:
https://github.com/kubeflow/kfp-tekton/issues/143
- KFP UI and API cannot manage and render taskref resources
- Task templates are shared with all users in the same namespace (used sha1 to encode the spec as task template name in order to minimize the conflict)
* Kubernetes Version (use `kubectl …
> Add option to produce pipelinerun taskspec as taskref

- sdk/python/kfp_tekton/compiler/_k8s_helper.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/pipelineparam_env.py
- sdk/python/tests/compiler/testdata/pipelineparam_env.yaml
Resolves #
When `sanitize_k8s_object` first introduced to sanitize k8s object for Tekton, Tekton's variable substitution wasn't allow. Now that limitation has been fixed, so we should enable pipelineparam for container env in Tekton.
**Checklist:**
> Enable pipelineparam for container env

- sdk/python/tests/perf_test_config.yaml
- sdk/python/tests/performance_tests.py
Signed-off-by: ted chang <htchang@us.ibm.com>
Resolves # 780
Add additional param, `copies`, to enable running N copies of same pipeline concurrently.  
* Python Version (use `python --version`): 3.9.6
* Tekton Version (use `tkn version`): v0.27.0
* Kubernetes Version (use `kubectl version`): v1.21.7
* OS (e.g. from `/etc/os-release`): OSX 12.1
> Additional param to enable running copies of same pipeline concurrently

- guides/kfp_tekton_install.md
Resolves #
When running Tekton pipelines with mixture of GPU and CPU workloads, our users gave feedbacks that the Tekton affinity assistant schedule too many workloads on the GPU nodes. Thus update the installation guide to disable affinity assistant for GPU clusters.
**Checklist:**
> Update KFP-Tekton installation to give guidance on GPU worker nodes.

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/loop_literal_separator.yaml
- sdk/python/tests/compiler/testdata/loop_literal_separator_noninlined.yaml
- sdk/python/tests/compiler/testdata/loop_with_params_in_json.py
- sdk/python/tests/compiler/testdata/loop_with_params_in_json.yaml
- sdk/python/tests/test_kfp_samples_report.txt
Resolves #
Parsing pipeline params in json string was not supported for loops in KFP-Tekton SDK. Thus we need to add regular expression to parse the pipeline params inside the json string and replace them with Tekton variable.
This also help covering one new test case from KFP.
**Checklist:**
> Add support to parse pipeline param in json string

- sdk/python/kfp_tekton/compiler/_tekton_handler.py
- sdk/python/tests/compiler/testdata/loop_literal_separator.yaml
- sdk/python/tests/compiler/testdata/loop_literal_separator_noninlined.yaml
**Which issue is resolved by this Pull Request:**
A fix to the previous partial solution (PR #837) of #791.
Remove separator field from params inside of the loop spec. Separator shouldn't be available inside of the spec.
As noted by Tommy Li in PR #838 for range-loop support, and as confirmed by checking the PipelineLoop [test for text-separator](https://github.com/kubeflow/kfp-tekton/tree/master/tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go#L251-L281):
```go
var aPipeline = &v1beta1.Pipeline{
ObjectMeta: metav1.ObjectMeta{Name: "a-pipeline", Namespace: "foo"},
Spec: v1beta1.PipelineSpec{
Params: []v1beta1.ParamSpec{{
Name: "current-item",
Type: v1beta1.ParamTypeString,
}, {
Name: "additional-parameter",
Type: …
```
> fix(sdk) separator param. Part of #791

- manifests/kustomize/base/cache-deployer/kustomization.yaml
- manifests/kustomize/third-party/application/cluster-scoped/application-crd.yaml
- manifests/kustomize/third-party/metacontroller/base/crd.yaml
Resolves #
There are some third party apps that are not yet k8s 1.22 certified on kubeflow multi-users install. Therefore, we want to patch the necessary fixes to make kubeflow multi-users work on k8s 1.22.
**Checklist:**
> Update manifests for multi-users k8s 1.22 support

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/testdata/big_data_passing.yaml
- sdk/python/tests/compiler/testdata/conditions_and_loops.yaml
- sdk/python/tests/compiler/testdata/long_pipeline_name.yaml
- sdk/python/tests/compiler/testdata/loop_empty.yaml
- sdk/python/tests/compiler/testdata/loop_in_recursion.yaml
- sdk/python/tests/compiler/testdata/loop_literal_separator.yaml
- sdk/python/tests/compiler/testdata/loop_over_lightweight_output.yaml
- sdk/python/tests/compiler/testdata/loop_static.yaml
- sdk/python/tests/compiler/testdata/loop_static_with_parallelism.yaml
- sdk/python/tests/compiler/testdata/loop_with_conditional_dependency.yaml
- sdk/python/tests/compiler/testdata/loop_with_numeric.yaml
- sdk/python/tests/compiler/testdata/loop_with_params_in_json.yaml
- sdk/python/tests/compiler/testdata/loop_with_step.yaml
- sdk/python/tests/compiler/testdata/nested_recur_runafter.yaml
- sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
- sdk/python/tests/compiler/testdata/recur_nested.yaml
- sdk/python/tests/compiler/testdata/recursion_while.yaml
- sdk/python/tests/compiler/testdata/tekton_loop_dsl.yaml
- sdk/python/tests/compiler/testdata/withitem_multi_nested.yaml
- sdk/python/tests/compiler/testdata/withitem_nested.yaml
- sdk/python/tests/compiler/testdata/withparam_global.yaml
- sdk/python/tests/compiler/testdata/withparam_global_dict.yaml
- sdk/python/tests/compiler/testdata/withparam_output.yaml
- sdk/python/tests/compiler/testdata/withparam_output_dict.yaml
Resolves #853
Add caching labels for inline loops and custom tasks. This can enable the new custom task caching features as well as passing any missing labels in the sub-pipelines. So all the pod/controller workloads that are from KFP can be cached.
**Checklist:**
> Add caching labels for inline loops and custom tasks

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/literal_params_test.py
- sdk/python/tests/compiler/testdata/literal_params_test.yaml
Resolves #880.
Adding a test for the issue.
Changing:
```python
if task.get('orig_params', []):  # custom task
```
to:
```python
if 'orig_params' in task:  # custom task
```
...as "normal" Tekton tasks don't have `'orig_params'` key at all --- now at the moment at least. An additional parameter (e.g. `'custom_task': true`), removed at the end of this `if` could be added too.
**Checklist:**
> fix(sdk) add test for custom-tasks with literals. Fixes #880

- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
fix integer divide by zero in PipelineLoop
Resolves #882
- Use default `step` value: `1` in case of `0` provided in `PipelineLoop`.
**Checklist:**
> fix(PipelineLoop): integer divide by zero

- tekton-catalog/objectstore/pkg/writer/objectstorelogger.go
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go
> fix: objectstore refactoring

- tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Resolves #
The current `PipelineLoopPipelineRunStatus` only has the `Iteration` which is an integer value, sometimes it is meaningless for the user.  We should have IterationItem in the status as well. 
Unit test passed.
**Checklist:**
> Add current iteration item to the PipelineLoopPipelineRunStatus

- manifests/kustomize/third-party/openshift/standalone/anyuid-scc.yaml
- manifests/kustomize/third-party/openshift/standalone/privileged-scc.yaml
Resolves #
There are reports that the standalone Tekton deployment needs the privilege and anyuid permission on the worker service account, thus adding standalone deployment service account `pipeline-runner` to the list of scc.
**Checklist:**
> Add missing openshift standalone permission

- manifests/kustomize/env/plain-multi-user/kustomization.yaml
Resolves #
Some users reported the s3 csi is not installed by default in the multi-user deployment. Hence adding the s3 plugin as part of the default multi-user deployment.
**Checklist:**
> Add missing csi plugin for multi-user manifests

- tekton-catalog/pipeline-loops/examples/loop-example-numeric-param.yaml
- tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Resolves #889 
Added new variable `iterationNumberParam` to track current item.
**Checklist:**
> feat: New variable iterationNumberParam to track current item.

- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Resolves #
For our use case, we don't set `podTemplate` and `serviceAccount` in the loopSpec, we only set them for the parent pipelinerun. The run created by Tekton controller will inherit the above two fields from the pipelinerun.
But the loop controller doesn't pass the above two fields to pipelineLoopSpec.
get `podTemplate` and `serviceAccount` from `run` and set them to pipelineLoopSpec if they are not configured.
All unit tests passed.
> pass down the podTemplate and serviceAccount from run to loopSpec

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/imagepullsecrets_with_node_selector.py
- sdk/python/tests/compiler/testdata/imagepullsecrets_with_node_selector.yaml
- sdk/python/tests/compiler/testdata/node_selector_from_pipeline.yaml
- sdk/python/tests/compiler/testdata/node_selector_from_pipeline_override.yaml
- tekton-catalog/pipeline-loops/Makefile
Apply the node_selector in PipelineConf to spec.podTemplate
instead of taskPodTemplate of each task.
Resolves #915
leverage spec.podTemplate for storing nodeSelector info
instead of propagating the nodeSelector of PipelineConf
to each task.
* Python Version (use `python --version`): 3.9
**Checklist:**
> fix(sdk): Apply node_selector in PipelineConf

- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Resolves #
We have a use case like that:
The iteration parameter string value is `1,2,3,4,5`, but the separator is not set.
User wants the default separator should be a comma `(,)`
Try the default separator `,` in the last when `interationParam` string is not empty and contains the comma.
Unit test passed.
**Checklist:**
> Support the comma as default string param separator

- sdk/python/kfp_tekton/compiler/_k8s_helper.py
- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/custom_task_long_name.py
- sdk/python/tests/compiler/testdata/custom_task_long_name.yaml
Resolves #914 
For kfp output parameter sanitization, the length is being trimmed by the original kfp dsl sanitization function by length and later on reduced the number of repeated dashes. However, in our Tekton compiler sanitization, it reduced the number of  repeated dashes first then sanitize by the length. This can make certain edge cases where long name output parameters that have multiple repeated dashes can be resulted with a different length in the Tekton results vs Tekton input parameters. Hence, we need to update the sanitization to work the same way as KFP DSL.
* Kubernetes Version (use …
> fix(SDK): Update sanitization logic to sync with kfp dsl

- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/tests/compiler/testdata/resourceop_basic.yaml
Related #922 
When setting up owner reference as a Tekton task, it needs to know the pod name, namespace, and uid which the pod itself doesn't know. We should pass these information to the pod so it doesn't need cluster-admin to get these information.
**Checklist:**
> Add necessary env variables for resource op owner reference

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/multi_nested_loop_condi.py
- sdk/python/tests/compiler/testdata/multi_nested_loop_condi.yaml
Resolves #924 
In Tekton, we don't put our condition dag as a sub graph because it will forbidden task level dependencies as this is a limitation on Argo. Therefore, we need some logics to traverse all the ops inside the condition graph to figure out all the nested condition and ops that have to stay inside the loop dag.
**Checklist:**
> Fix multiple nested condition in loops issue

- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Wait for pipelineloop-break-operation task final status before breaking the loop.
Resolves #
https://github.com/kubeflow/kfp-tekton/issues/800#issuecomment-1123277062
wait until the break operation task is done, then cancel the looprun and break the loop.
**Checklist:**
> wait for pipelineloop-break-operation task final status

- .github/workflows/kfp-tekton-unittests.yml
- tekton-catalog/pipeline-loops/Makefile
the whole repo needs go v1.17 now.
> [build] update github workflow to use go v1.17

- backend/src/apiserver/common/config.go
- backend/src/apiserver/common/const.go
- backend/src/apiserver/template/tekton_template.go
- manifests/kustomize/base/pipeline/kfp-pipeline-config.yaml
to avoid result duplication in the copy-artifacts step, add a step
to move result files to /tekton/home/tep-results.
> fix(backend): refine copy-artifacts step

- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Resolves # https://github.com/kubeflow/kfp-tekton/issues/954
1. Trim space and newline char for range input and validate it
2. Allow whitespace as iteration string.
**Checklist:**
> fix 954, trim whitespace and newline char for range input

- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Resolves #962
Storing PipelineSpec and TaskSpec in PipelineRunStatus is a source of significant memory consumption and OOM failures.
PipelineSpec and TaskSpec seems to be redundant in this place.
**Checklist:**
> fix(pipeline-loops): PipelineLoop consumes significant amount of memory

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/testdata/condition.yaml
- sdk/python/tests/compiler/testdata/condition_dependency.yaml
- sdk/python/tests/compiler/testdata/conditions_and_loops.yaml
- sdk/python/tests/compiler/testdata/conditions_and_loops_noninlined.yaml
- sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml
- sdk/python/tests/compiler/testdata/loop_in_recursion.yaml
- sdk/python/tests/compiler/testdata/loop_in_recursion_noninlined.yaml
- sdk/python/tests/compiler/testdata/nested_recur_runafter.yaml
- sdk/python/tests/compiler/testdata/nested_recur_runafter_noninlined.yaml
- sdk/python/tests/compiler/testdata/recur_nested.yaml
- sdk/python/tests/compiler/testdata/recur_nested_noninlined.yaml
- sdk/python/tests/compiler/testdata/recursion_while.yaml
- sdk/python/tests/compiler/testdata/recursion_while_noninlined.yaml
eliminate the use of `script`, replace it with
command and args. this also removes the init container that
prepares the script.
**Checklist:**
> fix(sdk): update condition template

- backend/src/agent/persistence/client/workflow_client.go
- backend/src/agent/persistence/main.go
- backend/src/agent/persistence/persistence_agent.go
- frontend/src/lib/WorkflowParser.ts
- guides/advanced_user_guide.md
- manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-role.yaml
- manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-config.yaml
- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Add logic to support `embedded-status` feature when using
the `minimal` setting. For now, the TaskRun/Run status is retrieved
and inserted to PipelineRun.Status and stored into ml-pipeline
backend storage.
**Checklist:**
> feature(backend): support embedded-status: minimal

- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Resolves #981
Add a `nil` check for run status.
Without that, the status will eventually be wrapped into `ConditionsAccessor` interface, which means the `nil` will be transformed into `(*RunStatus)(nil)` (i.e. the method table is non-nil, but the data table of the interface fat-pointer is nil). A casual `nil` check done in `GetCondition` cannot detect typed nils.
That kind of cases should be avoided and are generally quite [bothersome to detect](https://go.dev/play/p/WBawQ4ujB1s):
```go
var i interface{} = nil
assert.Equal(t, i, nil)
var s *string = nil
i = s
assert.NoEqual(t, i, nil)
assert.True(t, reflect.ValueOf(i).Kind() == reflect.Ptr && reflect.ValueOf(i).IsNil())
```
Instead, it would be best not to …
> fix(backend): nil ptr exception for empty run status in pipeline-loops, fixes #981

- sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/tests/compiler/testdata/artifact_outputs.yaml
- sdk/python/tests/compiler/testdata/big_data_passing.yaml
- sdk/python/tests/compiler/testdata/create_component_from_func.yaml
- sdk/python/tests/compiler/testdata/data_passing_pipeline_complete.yaml
- sdk/python/tests/compiler/testdata/data_passing_pipeline_param_as_file.yaml
- sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
- sdk/python/tests/compiler/testdata/many_results.yaml
- sdk/python/tests/compiler/testdata/many_results_with_warnings.yaml
- sdk/python/tests/compiler/testdata/nested_custom_conditions.yaml
Resolves #989 
when using script, it generates an init container to process the script.
we'd like to avoid the init container in pipelinerun.
remove `script` and use `command` and `arg` instead.
**Checklist:**
> eliminate the use of `taskSpec.script`

- backend/src/apiserver/client/minio.go
- backend/src/apiserver/client_manager.go
- backend/src/apiserver/common/config.go
- manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
- manifests/kustomize/base/pipeline/apiserver-deployment.yaml
- v2/objectstore/object_store.go
- v2/objectstore/object_store_test.go
N/A
Removes any reference to minio to make object storage access abstract
* Python Version (use `python --version`): 3.10.4
* Tekton Version (use `tkn version`): 0.33.2
* Kubernetes Version (use `kubectl version`): 1.22.3
* OS (e.g. from `/etc/os-release`): Fedora 35
**Checklist:**
> chore(apiserver): Object Storage connection abstraction

- manifests/kustomize/base/pipeline/kfp-pipeline-config.yaml
- sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
- sdk/python/tests/compiler/testdata/artifact_outputs.yaml
- sdk/python/tests/compiler/testdata/big_data_passing.yaml
- sdk/python/tests/compiler/testdata/create_component_from_func.yaml
- sdk/python/tests/compiler/testdata/data_passing_pipeline_complete.yaml
- sdk/python/tests/compiler/testdata/many_results.yaml
- sdk/python/tests/compiler/testdata/many_results_with_warnings.yaml
Resolves #996 
1. To add support to directories in step-copy-artifacts script, I added check [ -d "$2" ] to allow directories to be transmitted as artifacts
2. To add support to directories in step-copy-results-artifacts script, I check if the provided result (src) is a directory; if so, create a tar.gz archive and compute the ARTIFACT_SIZE on {src}.tar.gz.
Moreover, print on {dst} file the list of files in {src}.tar.gz (namely, the result of `tar -tzf {src}.tar.gz`) instead of copying directly {src} into {dst}
* Python Version (use `python --version`): Python 3.10.5
* Tekton Version (use `tkn version`): kfp-tekton v1.2.1
* Kubernetes Version (use `kubectl version`): client v1.23.6, …
> fix(sdk): Support passing directories in step-copy-results-artifacts and step-copy-artifacts. Fixes #996

- backend/src/cache/server/mutation.go
Resolves #
cache deployer caching output and set to the wrong go type. Updating the caching value to the current Tekton type. 
**Checklist:**
> fix(backend): fix cache server output

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/kfp_tekton/tekton.py
- sdk/python/tests/compiler/testdata/loop_with_step.py
- sdk/python/tests/compiler/testdata/loop_with_step_noninlined.yaml
Resolves #986 
Looping and sub-pipeline in Tekton is considered as a custom task which can have its own metadata for annotations and labels. In order to further reduce the duplicated annotations and labels yaml definition in the sub-pipeline level. 
**Checklist:**
> sdk(feat): add metadata support for loop

- sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
Resolves #
Add alpha env flag to opt out artifact tracking annotations to further reduce Tekton yaml size for pipelines that need high throughputs without tracking.
Usage:
Enable the following env variable flag before compiling the pipeline
```
export DISABLE_ARTIFACT_TRACKING=true
```
**Checklist:**
> feat(sdk): Add alpha env flag to opt out artifact tracking annotations

- sdk/python/kfp_tekton/compiler/_tekton_handler.py
Resolves #1034.
Include `finally` tasks in `_handle_tekton_pipeline_variables`.
* Tekton Version (use `tkn version`): 8bcb27213e1a6a0b75e133f2acb60e9be51827e5
* Kubernetes Version (use `kubectl version`): 0.36.0
**Checklist:**
> fix(sdk) include finally tasks in placeholder indir

- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Resolves #
inconsistent run status, 
when hit failed PR, we mark the status failed immediately and don't care the running sub prs.
do not mark failed status until all running PRs are done.
**Checklist:**
> do not mark failed until all running PRs are done

- backend/Dockerfile.persistenceagent
- backend/src/agent/persistence/client/workflow_client.go
- manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
- manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
When using `embedded-status: minimal`, the nested pipelineloop status
is missing. Add logic in persistence agent to retrieve runs and taskruns
statuses for nested pipelineloop.
**Checklist:**
> feat(backend): handle pipelineloop status

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
- sdk/python/tests/compiler/testdata/compose.yaml
Resolves #
The caching labels were only added when the tekton/kfp config flag is enabled. Hence update the default set of labels when those config are omitted in the compiler function.
**Checklist:**
> fix(sdk): add default labels for caching

- sdk/python/kfp_tekton/compiler/_tekton_handler.py
- sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested.yaml
- sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested_noninlined.yaml
- sdk/python/tests/compiler/testdata/nested_loop_counter.yaml
- sdk/python/tests/compiler/testdata/nested_loop_counter_noninlined.yaml
- sdk/python/tests/compiler/testdata/nested_loop_global_param.yaml
- sdk/python/tests/compiler/testdata/nested_loop_global_param_noninlined.yaml
- sdk/python/tests/compiler/testdata/nested_loop_param.yaml
- sdk/python/tests/compiler/testdata/nested_loop_param_noninlined.yaml
- sdk/python/tests/compiler/testdata/nested_loop_same_arg.yaml
- sdk/python/tests/compiler/testdata/nested_loop_same_arg_noninlined.yaml
- sdk/python/tests/compiler/testdata/nested_loop_with_underscore.yaml
- sdk/python/tests/compiler/testdata/nested_loop_with_underscore_noninlined.yaml
- sdk/python/tests/compiler/testdata/withitem_multi_nested.yaml
- sdk/python/tests/compiler/testdata/withitem_multi_nested_noninlined.yaml
> cherrypick(sdk): fix nested param logic for pl (#1091)

- backend/src/apiserver/common/config.go
- backend/src/apiserver/common/const.go
- backend/src/apiserver/template/tekton_template.go
- manifests/kustomize/base/pipeline/apiserver-deployment.yaml
- manifests/kustomize/base/pipeline/kfp-pipeline-config.yaml
Allow users to specify the image for `step-move-all-results-to-tekton-home` step. Add an env variable for the custom image: `MOVERESULTS_IMAGE` in the api server.
Resolves #1103 
**Checklist:**
> feat(backend): specify the image for result step

- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/timeout.py
- sdk/python/tests/compiler/testdata/timeout_config.py
- sdk/python/tests/compiler/testdata/timeout_config.yaml
Resolves #1100
Add pipeline level timeout config via kfp pipeline_conf object.
**Checklist:**
> feat(sdk): add pipeline_conf.timeout sdk support

- sdk/python/kfp_tekton/compiler/_tekton_handler.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/kfp_tekton/k8s_client_helper.py
Resolves #
Experimenting with the latest codex trial model to enhance/produce comments for some of the sdk python functions we have.
**Checklist:**
> chore(sdk): Update sdk comments

- manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-controller.yaml
- manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-webhook.yaml
For k8s 1.25, a securityContext definition is needed for a pod. Add proper security context to pipelineloop controler and webhook
**Checklist:**
> fix(backend): Add securitycontext for k8s 1.25

- backend/src/cache/server/mutation.go
add format arg to printf command to avoid cached string being interpreted.
**Checklist:**
> fix(backend): Add format arg to printf command

- scripts/deploy/iks/test-cache.sh
- scripts/deploy/iks/test-condition-depend.sh
- scripts/deploy/iks/test-flip-coin.sh
- scripts/deploy/iks/test-many-edges.sh
- scripts/deploy/iks/test-trusted-ai.sh
> fix(tests): update e2e tests with new api commands

- guides/advanced_user_guide.md
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/kfp_tekton/compiler/pipeline_utils.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/tekton_pipeline_conf.py
- sdk/python/tests/compiler/testdata/tekton_pipeline_conf.yaml
Resolves #1130 
Add env support for podtemplate in sdk to support new Tekton env in podtemplate from Tekton 0.43+. This can help our product reduce duplicated env variables by significant amounts.
Also fixing a bug in securityContext to properly convert Python object name to yaml object name.
* Tekton Version (use `tkn version`): 0.43+
**Checklist:**
> feat(sdk): Add env support for podtemplate in sdk

- manifests/kustomize/third-party/tekton/README.md
Resolves #
Tekton Dashboard yamls are no longer hosted on Github. Instead they all hosted on GCS.
**Checklist:**
> chore(manifests): Fix broken github link

- .github/workflows/kfp-tekton-unittests.yml
- Makefile
- tekton-catalog/pipeline-loops/Makefile
- tekton-catalog/pipeline-loops/cmd/cli/main.go
Resolves #1143
Added examples to the validation and made the checker more verbose and stricter.
**Checklist:**
> Feat(pipelineloop-cli): support customruns validation as well.

- sdk/python/kfp_tekton/__init__.py
- sdk/python/setup.py
Resolves #
Update package dependency source as our current publication tools twine doesn't work with sourcing the requirements.in for some pip install. Will open another issue to migrate our release tools in another issue.
**Checklist:**
> chore(sdk): update package dependency source

- guides/advanced_user_guide.md
- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/kfp_tekton/compiler/compiler.py
- sdk/python/kfp_tekton/compiler/pipeline_utils.py
- sdk/python/tests/compiler/compiler_tests.py
- sdk/python/tests/compiler/testdata/pipelineparam_env.yaml
- sdk/python/tests/compiler/testdata/resourceop_basic.yaml
- sdk/python/tests/compiler/testdata/tekton_pipeline_conf.py
- sdk/python/tests/compiler/testdata/tekton_pipeline_conf.yaml
- sdk/python/tests/compiler/testdata/volume_op.yaml
Resolves #
The flag for disabling component spec annotation metadata was only available on package level, we want to expose this flag on pipeline level as well so our users can control what pipeline is allowed to be tracked for metadata.
**Checklist:**
> feat(sdk): make metadata component spec gen flag configurable on pipeline level

- sdk/python/kfp_tekton/compiler/main.py
Resolves #
The version print statement for every time we compile the pipeline can create a significant log size when we are running the sdk in a server for a log time. We have been skipping info logs but removing this print statement can help us get back useful info logs that doesn't grow big over time.
This print statement was not in argo version as well so it make sense to remove it.
**Checklist:**
> fix(sdk): Remove print statement for compiler to reduce log size

- .tekton/pipeline.yaml
- scripts/deploy/iks/expect-condition-depend.json
- scripts/deploy/iks/helper-functions.sh
- scripts/deploy/iks/test-cache.sh
- scripts/deploy/iks/test-condition-depend.sh
- scripts/deploy/iks/test-flip-coin.sh
- scripts/deploy/iks/test-many-edges.sh
enhance toolchains scripts to avoid build failures we observed recently
**Checklist:**
> fix(test): enhance build scripts

- .github/workflows/codeql.yml
Resolves #
Create periodic code scan to give us better insights on what static bugs are in our code. Not all commits need to be scan every time so we are running it as cronjob first to give us some ideas on the initial scan.
**Checklist:**
> feat(CI): Create periodic codeql code scan to detect possible static bugs

- backend/src/agent/persistence/worker/metrics_reporter.go
- backend/src/common/util/workflow.go
After tekton 0.45. status.taskRuns will be removed. Switch to status.childReferences since we can use
them to get all taskRuns and their pipelineTaskNames.
**Checklist:**
> fix(backend): Use childReference instead of taskRuns

- backend/test/integration/pipeline_api_test.go
- backend/test/integration/pipeline_version_api_test.go
- backend/test/integration/upgrade_test.go
Resolves #
Fix integration test template object bugs, it should not be the value of the template object as Tekton library not returning the object as references.
**Checklist:**
> fix(backend): Fix integration test template object bugs

- backend/src/apiserver/common/config.go
- backend/src/apiserver/template/tekton_template.go
Resolves #
The global cache flag was modified in one of the old rebase. Since it wasn't reported for a while and some users might depended on the mistaken flag, updating global cache flag to work both ways and also in scheduled workflows.
**Checklist:**
> fix(backend): Fix global cache flag

- guides/kfp_tekton_install.md
> chore(docs): Update kfp_tekton_install.md with new compatibility map

- backend/src/v2/compiler/tektoncompiler/container.go
- manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
- manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml
- manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
Propagate the Env vars in ml-pipeline to executor pods, and the launcher can use them to set up MLMD and ml-pipeline endpoints. This change assumes the ml-pipeline and MLMD are using the following service names:
- ml-pipeline
- metadata-grpc-service
**Checklist:**
> v2(tekton compiler): add env vars for caching

- README.md
- backend/third_party_licenses/apiserver.csv
- backend/third_party_licenses/cache_server.csv
- backend/third_party_licenses/persistence_agent.csv
- backend/third_party_licenses/swf.csv
- go.mod
- go.sum
- guides/kfp_tekton_install.md
- manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
- sdk/README.md
- tekton-catalog/pipeline-loops/go.mod
> Fix(backend): Upgrade Tekton 0.47.1 to address timeout bug

- manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
- manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-controller.yaml
- manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-webhook.yaml
Resolves #1298 
1.7.0 images include a version of Tekton that has a dependency on config-trusted-resources, config-artifact-pvc and config-artifact-bucket ConfigMap. These have been removed in the most recent versions of Tekton that deprecate PipelineResources.
Updating to 1.7.1 of the images resolves the need for these ConfigMap to exist and allows the pipelineloop controllers to boot.
**Checklist:**
> fix(deployment): Update image name and version for pipelineloop controllers

- backend/src/agent/persistence/client/pipeline_client.go
- backend/src/agent/persistence/worker/swf_saver.go
- backend/src/apiserver/main.go
persistence agent can't properly report scheduledworkflow and cause errors on both the persistence agent and apiserver. fix the error by using v2beta1 API to report scheduledworkflow. still need upstream to update scheduledworkflow to v2beta1.
**Checklist:**
> v2(backend): fix persistence agent

- backend/src/crd/controller/scheduledworkflow/client/kube_client.go
- backend/src/crd/controller/scheduledworkflow/controller.go
- manifests/kustomize/base/installs/multi-user/scheduled-workflow/cluster-role.yaml
- manifests/kustomize/base/installs/multi-user/scheduled-workflow/deployment-patch.yaml
- manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
When calling the `CreateRun` API in multi-user mode, a kubeflow-user id needs to inject to gRPC metadata.
**Checklist:**
> v2(backend): fix multi-user issue in swf

- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Resolves #
Fix the one place where the pipeline is updated with v1beta1 during pipeline cancellation. Somehow it was able to pass all the unit tests with the v1beta1 to v1 conversion but randomly converted into the wrong v1 spec in 1/10 chance with the real tekton controller
**Checklist:**
> fix(pipelineloop): update pipelineloop v1 bug

- backend/src/apiserver/common/config.go
- backend/src/apiserver/common/const.go
- backend/src/apiserver/template/tekton_template.go
Resolves #
There is a hard-coded reference to a Secret named `mlpipeline-minio-artifact` that contains credentials metadata to the Object Store.  This is the only instance of this, so sourcing the metadata from the apiserver's Env Vars (where it is already provided) will make deployments more flexible and is better practice, in general.
Also updates a viper config variable to match/target what is used across the rest of the project and manifests.  It was also the only instance of this (`_SECRETKEY` rather than `_SECRETACCESSKEY`), so likely was a typo.
* Python Version (use `python --version`): 3.11.1
* Tekton Version (use `tkn version`): v0.31.4
* Kubernetes Version (use `kubectl …
> feat(backend): Source ObjStore Creds from Env in Tekton Template

- sdk/README.md
- sdk/python/kfp_tekton/compiler/_op_to_template.py
- sdk/python/kfp_tekton/compiler/compiler.py
Resolves #1335 
**Checklist:**
> feat(sdk): update new image config via env variables

- backend/src/crd/controller/scheduledworkflow/controller.go
- backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
- go.mod
- go.sum
Resolves #1343 
The change ensures instanes of `ORIG_PR_NAME` are properly substituted for scheduled runs, just like in manually triggered runs. It also adds the missing `custom.tekton.dev/originalPipelineRun`. Both cases are handled in SWF controller, since workflow names for recurring runs are generated there.
**Checklist:**
> fix(backend): add PR name substitution for scheduled runs.

- backend/src/v2/compiler/tektoncompiler/container.go
- backend/src/v2/compiler/tektoncompiler/tekton.go
Resolves #1358 
Parameterizing the v2 launcher image so it's possible to extend/provide fixes to the code.
**Checklist:**
> feat(backend): Parameterizing v2 Launcher Image. Resolves #1358 

- .github/workflows/backend.yml
- backend/src/v2/compiler/tektoncompiler/container.go
- backend/src/v2/compiler/tektoncompiler/testdata/exit_handler.yaml
- backend/src/v2/compiler/tektoncompiler/testdata/hello_world.yaml
- backend/src/v2/compiler/tektoncompiler/testdata/importer.yaml
- backend/src/v2/compiler/tektoncompiler/testdata/loop_static.yaml
- backend/src/v2/compiler/tektoncompiler/testdata/mnist_pipeline.yaml
- backend/src/v2/compiler/tektoncompiler/testdata/nestedloop.yaml
- manifests/kustomize/cluster-scoped-resources-tekton/kustomization.yaml
- manifests/kustomize/cluster-scoped-resources-tekton/namespace.yaml
- manifests/kustomize/cluster-scoped-resources-tekton/params.yaml
- manifests/kustomize/env/plain/kustomization.yaml
- manifests/kustomize/env/platform-agnostic-tekton-multi-user/kustomization.yaml
- manifests/kustomize/env/platform-agnostic-tekton-multi-user/tekton-config.yaml
- manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
- manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
- manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-config.yaml
- scripts/deploy/github/build-images.sh
- scripts/deploy/github/deploy-kfp.sh
- scripts/deploy/github/manifests/kustomization.yaml
- scripts/deploy/github/re-tag.sh
- scripts/deploy/github/test-dynamic-loop.sh
- scripts/deploy/github/test-static-loop.sh
> fix(ci): update v2 deployment and ci tests

- backend/src/v2/compiler/tektoncompiler/container.go
- backend/src/v2/compiler/tektoncompiler/testdata/exit_handler.yaml
- backend/src/v2/compiler/tektoncompiler/testdata/hello_world.yaml
- backend/src/v2/compiler/tektoncompiler/testdata/loop_static.yaml
- backend/src/v2/compiler/tektoncompiler/testdata/mnist_pipeline.yaml
- backend/src/v2/compiler/tektoncompiler/testdata/nestedloop.yaml
N/A
In our multi-stack architecture for Kubeflow Pipelines, we need the kfp-driver to support parametrization of the MLMD location.
* Python Version (use `python --version`): Python 3.10.12
* Tekton Version (use `tkn version`): N/A
* Kubernetes Version (use `kubectl version`): v1.25.2
* OS (e.g. from `/etc/os-release`): Fedora 37
**Checklist:**
> feat(Tekton-compiler): Add env vars in kfp-driver to parametrize Object storage host and port

- backend/src/apiserver/common/config.go
- backend/src/apiserver/template/tekton_template.go
Resolves https://github.com/kubeflow/kfp-tekton/issues/1394
This PR adds the option to pull in a trusted bundle that gets mounted to the step-copy artifact steps added by the api server when generating the tekton template. It assumes default location of /etc/ssl/certs. 
* Python Version (use `python --version`): Python 3.11, tested with kfp sdk 1.8
* Tekton Version (use `tkn version`): 0.50
* Kubernetes Version (use `kubectl version`): OC stable-4.13 / k8s 1.26
**Checklist:**
> feat(backend): Add CA injection to step-copy-artifacts step. Fixes #1394.

- guides/kfp_tekton_install.md
Resolves #
Openshift pipelines 1.12 and kfp-tekton 2.0.2 is out. Updating the installation docs with the corresponding changes.
**Checklist:**
> chore(docs): Update kfp-tekton install versions

- backend/src/v2/compiler/tektoncompiler/testdata/mnist_pipeline.yaml
- manifests/kustomize/env/platform-agnostic-tekton-multi-user/kustomization.yaml
- manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
- manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
- scripts/deploy/github/build-images.sh
- scripts/deploy/github/manifests/kustomization.yaml
> chore(CI/manifests): Update CI and move manifests to 2.0.3

- tekton-catalog/tekton-kfptask/go.mod
- tekton-catalog/tekton-kfptask/go.sum
- tekton-catalog/tekton-kfptask/pkg/reconciler/kfptask/reconciler.go
Resolves #
Our current publisher only being executed when the dag is completed. Thus it make sense to also update mlmd status as complete for that dag. 
For failing status, caching entry, and dag output artifacts, it only make sense to implement it after we merged the publisher as part of the sub-dag reconciliation logic. Otherwise any failed sub-dag will never run the publisher task and the cache entry and output artifacts info has different logic when it became part of the sub-dag reconciliation logic.
**Checklist:**
> feat(tekton-kfptask): Update kfptask to publish completed dag status

- backend/src/v2/compiler/tektoncompiler/dag.go
- backend/src/v2/compiler/tektoncompiler/testdata/condition_ir.yaml
- backend/src/v2/compiler/tektoncompiler/testdata/exit_handler.yaml
- backend/src/v2/compiler/tektoncompiler/testdata/exit_handler_ir.yaml
- backend/src/v2/compiler/tektoncompiler/testdata/loop_static.yaml
- backend/src/v2/compiler/tektoncompiler/testdata/loop_static_ir.yaml
- backend/src/v2/compiler/tektoncompiler/testdata/mnist_pipeline.yaml
- backend/src/v2/compiler/tektoncompiler/testdata/mnist_pipeline_ir.yaml
- backend/src/v2/compiler/tektoncompiler/testdata/nestedloop.yaml
> fix(backend): Update compiler with new test sdk and fix dag publisher execution id

- tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
> feat(pipelineloop): Update pipelineloop v2 to have failed and cancelled status

- manifests/kustomize/env/platform-agnostic-tekton-multi-user/kustomization.yaml
- manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
- manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
> chore(release): kfp-tekton 2.0.5 backend release

- guides/kfp_tekton_install.md
> Chore(docs) Update kfp_tekton_install V2 instructions for KFP-Tekton 2.0.5 release

- guides/kfp_tekton_install.md
Resolves #
Updating install instructions to use kubectl -k. kustomize is now a de facto part of kubectl and it make sense to let users install the manifests from it's true source rather than the release yaml we created. That way when master branch is cleaned up, users can still get the source file from each release tag.
**Checklist:**
> fix(README): Update instructions to only use kustomize
